// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveOrdersAsBuyer = `-- name: CountActiveOrdersAsBuyer :one
SELECT count(*) FROM work_order
WHERE buyer_id = $1
  AND status IN ('accepted', 'production', 'completed', 'shipped', 'in_mediation')
`

// CountActiveOrdersAsBuyer counts a profile's orders that are not terminal, on
// the buyer side. Revoking the buyer role while any of these exist is refused,
// because it would strip a party from an order still in flight.
func (q *Queries) CountActiveOrdersAsBuyer(ctx context.Context, buyerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOrdersAsBuyer, buyerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveOrdersAsSubcontractor = `-- name: CountActiveOrdersAsSubcontractor :one
SELECT count(*) FROM work_order
WHERE subcontractor_id = $1
  AND status IN ('accepted', 'production', 'completed', 'shipped', 'in_mediation')
`

// CountActiveOrdersAsSubcontractor counts a profile's non-terminal orders on the
// subcontractor side, guarding subcontractor-role revocation the same way.
func (q *Queries) CountActiveOrdersAsSubcontractor(ctx context.Context, subcontractorID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOrdersAsSubcontractor, subcontractorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO user_account (
    id, email, phone, password_hash,
    role_subcontractor, role_buyer,
    created_at, updated_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $6
)
RETURNING id, email, phone, password_hash, email_verified, phone_verified, role_subcontractor, role_buyer, role_admin, notif_nontx_email, notif_nontx_whatsapp, created_at, updated_at
`

type CreateAccountParams struct {
	Email             string
	Phone             string
	PasswordHash      string
	RoleSubcontractor bool
	RoleBuyer         bool
	CreatedAt         pgtype.Timestamptz
}

// CreateAccount inserts a new account. business role columns default false at
// the table level; the caller passes only the roles chosen at registration.
// password_hash is a bcrypt digest, never the plaintext password.
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.RoleSubcontractor,
		arg.RoleBuyer,
		arg.CreatedAt,
	)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.RoleSubcontractor,
		&i.RoleBuyer,
		&i.RoleAdmin,
		&i.NotifNontxEmail,
		&i.NotifNontxWhatsapp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS (SELECT 1 FROM user_account WHERE email = $1)
`

// EmailExists reports whether an email is already registered, so registration
// can answer 409 without leaking through a full row read.
func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, phone, password_hash, email_verified, phone_verified, role_subcontractor, role_buyer, role_admin, notif_nontx_email, notif_nontx_whatsapp, created_at, updated_at FROM user_account WHERE email = $1
`

// GetAccountByEmail loads one account by its case-insensitive email. Used by
// login and recovery; both must run the rate limit before this lookup.
func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.RoleSubcontractor,
		&i.RoleBuyer,
		&i.RoleAdmin,
		&i.NotifNontxEmail,
		&i.NotifNontxWhatsapp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, phone, password_hash, email_verified, phone_verified, role_subcontractor, role_buyer, role_admin, notif_nontx_email, notif_nontx_whatsapp, created_at, updated_at FROM user_account WHERE id = $1
`

// GetAccountByID loads one account by id, backing GET /me and session refresh.
func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.RoleSubcontractor,
		&i.RoleBuyer,
		&i.RoleAdmin,
		&i.NotifNontxEmail,
		&i.NotifNontxWhatsapp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByPhone = `-- name: GetAccountByPhone :one
SELECT id, email, phone, password_hash, email_verified, phone_verified, role_subcontractor, role_buyer, role_admin, notif_nontx_email, notif_nontx_whatsapp, created_at, updated_at FROM user_account WHERE phone = $1
`

// GetAccountByPhone loads one account by phone, backing WhatsApp verification
// and the emergency user:verify --phone subcommand.
func (q *Queries) GetAccountByPhone(ctx context.Context, phone string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByPhone, phone)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.RoleSubcontractor,
		&i.RoleBuyer,
		&i.RoleAdmin,
		&i.NotifNontxEmail,
		&i.NotifNontxWhatsapp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileIDByAccount = `-- name: GetProfileIDByAccount :one
SELECT id FROM business_profile WHERE account_id = $1
`

// GetProfileIDByAccount returns the business profile id for an account, or no
// rows when none exists yet. MyAccount carries profile_id as nullable, so the
// caller treats pgx.ErrNoRows as a null profile_id rather than an error.
func (q *Queries) GetProfileIDByAccount(ctx context.Context, accountID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getProfileIDByAccount, accountID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const phoneExists = `-- name: PhoneExists :one
SELECT EXISTS (SELECT 1 FROM user_account WHERE phone = $1)
`

// PhoneExists reports whether a phone is already registered.
func (q *Queries) PhoneExists(ctx context.Context, phone string) (bool, error) {
	row := q.db.QueryRow(ctx, phoneExists, phone)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE user_account
SET email_verified = true, updated_at = $2
WHERE id = $1
`

type SetEmailVerifiedParams struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

// SetEmailVerified marks the email verified after a valid code is consumed.
func (q *Queries) SetEmailVerified(ctx context.Context, arg SetEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, setEmailVerified, arg.ID, arg.UpdatedAt)
	return err
}

const setPhoneVerified = `-- name: SetPhoneVerified :exec
UPDATE user_account
SET phone_verified = true, updated_at = $2
WHERE id = $1
`

type SetPhoneVerifiedParams struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

// SetPhoneVerified marks the phone verified after a valid code is consumed.
func (q *Queries) SetPhoneVerified(ctx context.Context, arg SetPhoneVerifiedParams) error {
	_, err := q.db.Exec(ctx, setPhoneVerified, arg.ID, arg.UpdatedAt)
	return err
}

const updateBusinessRoles = `-- name: UpdateBusinessRoles :one
UPDATE user_account
SET role_subcontractor = $2, role_buyer = $3, updated_at = $4
WHERE id = $1
RETURNING id, email, phone, password_hash, email_verified, phone_verified, role_subcontractor, role_buyer, role_admin, notif_nontx_email, notif_nontx_whatsapp, created_at, updated_at
`

type UpdateBusinessRolesParams struct {
	ID                pgtype.UUID
	RoleSubcontractor bool
	RoleBuyer         bool
	UpdatedAt         pgtype.Timestamptz
}

// UpdateBusinessRoles sets the two business role flags. admin is never touched
// here; the admin_has_no_business_role constraint rejects granting a business
// role to an admin account, so the update fails loudly instead of silently
// corrupting the role model.
func (q *Queries) UpdateBusinessRoles(ctx context.Context, arg UpdateBusinessRolesParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, updateBusinessRoles,
		arg.ID,
		arg.RoleSubcontractor,
		arg.RoleBuyer,
		arg.UpdatedAt,
	)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.RoleSubcontractor,
		&i.RoleBuyer,
		&i.RoleAdmin,
		&i.NotifNontxEmail,
		&i.NotifNontxWhatsapp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE user_account
SET password_hash = $2, updated_at = $3
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           pgtype.UUID
	PasswordHash string
	UpdatedAt    pgtype.Timestamptz
}

// UpdatePassword replaces the bcrypt hash during recovery confirmation.
func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash, arg.UpdatedAt)
	return err
}
