// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listing.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveCatalogItemsOfType = `-- name: CountActiveCatalogItemsOfType :one
SELECT count(*)::bigint
FROM catalog_item
WHERE type = $1 AND active AND id = ANY($2::uuid[])
`

type CountActiveCatalogItemsOfTypeParams struct {
	Type    ItemType
	Column2 []pgtype.UUID
}

// CountActiveCatalogItemsOfType counts how many of the given ids are active
// items of the expected type. The service compares this to the number of ids it
// sent: any shortfall means an unknown, inactive, or wrong-type id, which it
// reports as a 422 before the type-checking trigger would raise a bare 500.
func (q *Queries) CountActiveCatalogItemsOfType(ctx context.Context, arg CountActiveCatalogItemsOfTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCatalogItemsOfType, arg.Type, arg.Column2)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createListing = `-- name: CreateListing :one

INSERT INTO capacity_listing (
    id, profile_id, weekly_capacity, readiness_lead_days,
    published, calendar_updated_at, horizon_until, created_at, updated_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, true, $4, $5, $4, $4
)
RETURNING id, profile_id, weekly_capacity, readiness_lead_days, published, calendar_updated_at, horizon_until, created_at, updated_at
`

type CreateListingParams struct {
	ProfileID         pgtype.UUID
	WeeklyCapacity    int32
	ReadinessLeadDays int32
	CalendarUpdatedAt pgtype.Timestamptz
	HorizonUntil      pgtype.Date
}

// Capacity listing and its availability calendar. One listing per profile
// (one_listing_per_profile); the weekly capacity is the central number
// (FR-012/FR-014) propagated to future periods on edit (FR-089). Periods are
// stored as the Monday date of each week (week_start_is_monday); the horizon is
// the furthest Monday that already has a period.
// CreateListing inserts the single listing a profile may own. horizon_until is
// seeded to the current week's Monday (it is NOT NULL and must be a Monday);
// EnsureHorizon raises it and generates the calendar in the same transaction.
// calendar_updated_at starts at creation time; only an owner edit to the
// calendar advances it afterward (FR-021).
func (q *Queries) CreateListing(ctx context.Context, arg CreateListingParams) (CapacityListing, error) {
	row := q.db.QueryRow(ctx, createListing,
		arg.ProfileID,
		arg.WeeklyCapacity,
		arg.ReadinessLeadDays,
		arg.CalendarUpdatedAt,
		arg.HorizonUntil,
	)
	var i CapacityListing
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WeeklyCapacity,
		&i.ReadinessLeadDays,
		&i.Published,
		&i.CalendarUpdatedAt,
		&i.HorizonUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteListingMachines = `-- name: DeleteListingMachines :exec
DELETE FROM listing_machine WHERE listing_id = $1
`

// DeleteListingMachines clears a listing's machine links before rewriting them.
func (q *Queries) DeleteListingMachines(ctx context.Context, listingID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteListingMachines, listingID)
	return err
}

const deleteListingProducts = `-- name: DeleteListingProducts :exec
DELETE FROM listing_product WHERE listing_id = $1
`

// DeleteListingProducts clears a listing's product links before rewriting them
// on an edit.
func (q *Queries) DeleteListingProducts(ctx context.Context, listingID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteListingProducts, listingID)
	return err
}

const findFutureAllocatedPeriodOverCapacity = `-- name: FindFutureAllocatedPeriodOverCapacity :one
SELECT p.week_start, p.used_capacity
FROM availability_period p
WHERE p.listing_id = $1
  AND p.week_start >= $3
  AND p.used_capacity > $2
ORDER BY p.week_start
LIMIT 1
`

type FindFutureAllocatedPeriodOverCapacityParams struct {
	ListingID    pgtype.UUID
	UsedCapacity int32
	WeekStart    pgtype.Date
}

type FindFutureAllocatedPeriodOverCapacityRow struct {
	WeekStart    pgtype.Date
	UsedCapacity int32
}

// FindFutureAllocatedPeriodOverCapacity returns the earliest future period whose
// used capacity already exceeds the proposed new weekly capacity, so a listing
// edit that would strand a running order is rejected with a 409 that names the
// offending week and amount rather than silently corrupting the calendar.
func (q *Queries) FindFutureAllocatedPeriodOverCapacity(ctx context.Context, arg FindFutureAllocatedPeriodOverCapacityParams) (FindFutureAllocatedPeriodOverCapacityRow, error) {
	row := q.db.QueryRow(ctx, findFutureAllocatedPeriodOverCapacity, arg.ListingID, arg.UsedCapacity, arg.WeekStart)
	var i FindFutureAllocatedPeriodOverCapacityRow
	err := row.Scan(&i.WeekStart, &i.UsedCapacity)
	return i, err
}

const getListingByID = `-- name: GetListingByID :one
SELECT id, profile_id, weekly_capacity, readiness_lead_days, published, calendar_updated_at, horizon_until, created_at, updated_at FROM capacity_listing WHERE id = $1
`

// GetListingByID loads any listing by its own id, for the public profile join.
func (q *Queries) GetListingByID(ctx context.Context, id pgtype.UUID) (CapacityListing, error) {
	row := q.db.QueryRow(ctx, getListingByID, id)
	var i CapacityListing
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WeeklyCapacity,
		&i.ReadinessLeadDays,
		&i.Published,
		&i.CalendarUpdatedAt,
		&i.HorizonUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListingByProfile = `-- name: GetListingByProfile :one
SELECT id, profile_id, weekly_capacity, readiness_lead_days, published, calendar_updated_at, horizon_until, created_at, updated_at FROM capacity_listing WHERE profile_id = $1
`

// GetListingByProfile loads a profile's listing, backing GET /listing/me. A
// missing row is a genuine 404 (the profile has not created a listing yet), not
// an invariant violation.
func (q *Queries) GetListingByProfile(ctx context.Context, profileID pgtype.UUID) (CapacityListing, error) {
	row := q.db.QueryRow(ctx, getListingByProfile, profileID)
	var i CapacityListing
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WeeklyCapacity,
		&i.ReadinessLeadDays,
		&i.Published,
		&i.CalendarUpdatedAt,
		&i.HorizonUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertListingMachine = `-- name: InsertListingMachine :exec
INSERT INTO listing_machine (listing_id, item_id, machine_count) VALUES ($1, $2, $3)
`

type InsertListingMachineParams struct {
	ListingID    pgtype.UUID
	ItemID       pgtype.UUID
	MachineCount int32
}

// InsertListingMachine links a machine item and its unit count to the listing.
func (q *Queries) InsertListingMachine(ctx context.Context, arg InsertListingMachineParams) error {
	_, err := q.db.Exec(ctx, insertListingMachine, arg.ListingID, arg.ItemID, arg.MachineCount)
	return err
}

const insertListingProduct = `-- name: InsertListingProduct :exec
INSERT INTO listing_product (listing_id, item_id) VALUES ($1, $2)
`

type InsertListingProductParams struct {
	ListingID pgtype.UUID
	ItemID    pgtype.UUID
}

// InsertListingProduct links a product item to the listing. The
// trg_reject_wrong_product_item trigger rejects a machine id here, but the
// service checks the item type first so a mismatch is a 422, not a 500.
func (q *Queries) InsertListingProduct(ctx context.Context, arg InsertListingProductParams) error {
	_, err := q.db.Exec(ctx, insertListingProduct, arg.ListingID, arg.ItemID)
	return err
}

const insertPeriodsUpToWeek = `-- name: InsertPeriodsUpToWeek :exec

INSERT INTO availability_period (
    id, listing_id, week_start, total_capacity, used_capacity, marked_full,
    created_at, updated_at
)
SELECT gen_random_uuid(), $1, gs::date, $4, 0, false, $5, $5
FROM generate_series($2::date, $3::date, interval '7 day') AS gs
ON CONFLICT (listing_id, week_start) DO NOTHING
`

type InsertPeriodsUpToWeekParams struct {
	ListingID     pgtype.UUID
	Column2       pgtype.Date
	Column3       pgtype.Date
	TotalCapacity int32
	CreatedAt     pgtype.Timestamptz
}

// ── availability calendar ──
// InsertPeriodsUpToWeek generates every missing weekly period from the current
// horizon forward to untilWeek in one statement. The series runs on date, not
// timestamptz, so there is no timezone shift that could nudge a Monday to
// Sunday. Each new period starts at the listing's weekly_capacity, zero used.
// ON CONFLICT keeps it idempotent and safe under concurrent calls: a week that
// already exists is left untouched (one_period_per_week). The lower bound is
// passed in already clamped to at least the current week's Monday so past weeks
// are never created.
func (q *Queries) InsertPeriodsUpToWeek(ctx context.Context, arg InsertPeriodsUpToWeekParams) error {
	_, err := q.db.Exec(ctx, insertPeriodsUpToWeek,
		arg.ListingID,
		arg.Column2,
		arg.Column3,
		arg.TotalCapacity,
		arg.CreatedAt,
	)
	return err
}

const listListingMachines = `-- name: ListListingMachines :many
SELECT i.id, i.type, i.name, i.active, lm.machine_count
FROM listing_machine lm
JOIN catalog_item i ON i.id = lm.item_id
WHERE lm.listing_id = $1
ORDER BY i.sort_order, i.name
`

type ListListingMachinesRow struct {
	ID           pgtype.UUID
	Type         ItemType
	Name         string
	Active       bool
	MachineCount int32
}

// ListListingMachines returns the machine items of a listing with their counts.
func (q *Queries) ListListingMachines(ctx context.Context, listingID pgtype.UUID) ([]ListListingMachinesRow, error) {
	rows, err := q.db.Query(ctx, listListingMachines, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListingMachinesRow{}
	for rows.Next() {
		var i ListListingMachinesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Active,
			&i.MachineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListingProducts = `-- name: ListListingProducts :many
SELECT i.id, i.type, i.name, i.active
FROM listing_product lp
JOIN catalog_item i ON i.id = lp.item_id
WHERE lp.listing_id = $1
ORDER BY i.sort_order, i.name
`

type ListListingProductsRow struct {
	ID     pgtype.UUID
	Type   ItemType
	Name   string
	Active bool
}

// ListListingProducts returns the product items of a listing joined to their
// catalog rows, so the response carries names, not bare ids.
func (q *Queries) ListListingProducts(ctx context.Context, listingID pgtype.UUID) ([]ListListingProductsRow, error) {
	rows, err := q.db.Query(ctx, listListingProducts, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListingProductsRow{}
	for rows.Next() {
		var i ListListingProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriodsInRange = `-- name: ListPeriodsInRange :many
SELECT
    p.week_start,
    p.total_capacity,
    p.used_capacity,
    p.marked_full,
    COALESCE((
        SELECT sum(a.quantity)::bigint
        FROM capacity_allocation a
        WHERE a.period_id = p.id AND a.reversed_at IS NULL
    ), 0) AS allocated
FROM availability_period p
WHERE p.listing_id = $1
  AND p.week_start >= $2
  AND p.week_start <= $3
ORDER BY p.week_start
`

type ListPeriodsInRangeParams struct {
	ListingID   pgtype.UUID
	WeekStart   pgtype.Date
	WeekStart_2 pgtype.Date
}

type ListPeriodsInRangeRow struct {
	WeekStart     pgtype.Date
	TotalCapacity int32
	UsedCapacity  int32
	MarkedFull    bool
	Allocated     interface{}
}

// ListPeriodsInRange returns the periods of a listing within an inclusive
// week_start range, ordered ascending, for GET /listing/me/periods. allocated
// is the sum of active allocation quantities on each period; remaining is the
// capacity left, floored at zero and forced to zero when the week is marked
// full.
func (q *Queries) ListPeriodsInRange(ctx context.Context, arg ListPeriodsInRangeParams) ([]ListPeriodsInRangeRow, error) {
	rows, err := q.db.Query(ctx, listPeriodsInRange, arg.ListingID, arg.WeekStart, arg.WeekStart_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPeriodsInRangeRow{}
	for rows.Next() {
		var i ListPeriodsInRangeRow
		if err := rows.Scan(
			&i.WeekStart,
			&i.TotalCapacity,
			&i.UsedCapacity,
			&i.MarkedFull,
			&i.Allocated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockListingByProfile = `-- name: LockListingByProfile :one
SELECT id, profile_id, weekly_capacity, readiness_lead_days, published, calendar_updated_at, horizon_until, created_at, updated_at FROM capacity_listing WHERE profile_id = $1 FOR UPDATE
`

// LockListingByProfile takes a row lock on the profile's listing so a capacity
// edit and its propagation to future periods run as one serialized unit. The
// listing row is always locked before any availability_period row, and that
// order is fixed across the codebase to prevent deadlocks.
func (q *Queries) LockListingByProfile(ctx context.Context, profileID pgtype.UUID) (CapacityListing, error) {
	row := q.db.QueryRow(ctx, lockListingByProfile, profileID)
	var i CapacityListing
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WeeklyCapacity,
		&i.ReadinessLeadDays,
		&i.Published,
		&i.CalendarUpdatedAt,
		&i.HorizonUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPeriodByWeek = `-- name: LockPeriodByWeek :one
SELECT id, listing_id, week_start, total_capacity, used_capacity, marked_full, created_at, updated_at FROM availability_period
WHERE listing_id = $1 AND week_start = $2
FOR UPDATE
`

type LockPeriodByWeekParams struct {
	ListingID pgtype.UUID
	WeekStart pgtype.Date
}

// LockPeriodByWeek locks a single period row for an owner edit, returning its
// current capacity and usage. A missing row means the week is beyond the
// horizon and must be generated first. Taken only after the listing row is
// locked, keeping the fixed lock order.
func (q *Queries) LockPeriodByWeek(ctx context.Context, arg LockPeriodByWeekParams) (AvailabilityPeriod, error) {
	row := q.db.QueryRow(ctx, lockPeriodByWeek, arg.ListingID, arg.WeekStart)
	var i AvailabilityPeriod
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.WeekStart,
		&i.TotalCapacity,
		&i.UsedCapacity,
		&i.MarkedFull,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const periodHasActiveAllocation = `-- name: PeriodHasActiveAllocation :one
SELECT EXISTS (
    SELECT 1 FROM capacity_allocation a
    WHERE a.period_id = $1 AND a.reversed_at IS NULL
)
`

// PeriodHasActiveAllocation reports whether a period carries any unreversed
// allocation, gating the "cannot mark full" and "cannot lower below used" edits.
func (q *Queries) PeriodHasActiveAllocation(ctx context.Context, periodID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, periodHasActiveAllocation, periodID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const propagateCapacityToFuturePeriods = `-- name: PropagateCapacityToFuturePeriods :exec
UPDATE availability_period p
SET total_capacity = $2, updated_at = $4
WHERE p.listing_id = $1
  AND p.week_start >= $3
  AND NOT EXISTS (
      SELECT 1 FROM capacity_allocation a
      WHERE a.period_id = p.id AND a.reversed_at IS NULL
  )
`

type PropagateCapacityToFuturePeriodsParams struct {
	ListingID     pgtype.UUID
	TotalCapacity int32
	WeekStart     pgtype.Date
	UpdatedAt     pgtype.Timestamptz
}

// PropagateCapacityToFuturePeriods sets total_capacity on every future period
// that carries no active allocation (FR-089): a capacity change flows to weeks
// the owner has not committed yet, while allocated weeks keep their agreed
// number. The EXISTS predicate uses idx_allocation_period. week_start >= the
// current Monday keeps past weeks frozen.
func (q *Queries) PropagateCapacityToFuturePeriods(ctx context.Context, arg PropagateCapacityToFuturePeriodsParams) error {
	_, err := q.db.Exec(ctx, propagateCapacityToFuturePeriods,
		arg.ListingID,
		arg.TotalCapacity,
		arg.WeekStart,
		arg.UpdatedAt,
	)
	return err
}

const raiseHorizonUntil = `-- name: RaiseHorizonUntil :exec
UPDATE capacity_listing
SET horizon_until = GREATEST(horizon_until, $2), updated_at = $3
WHERE id = $1
`

type RaiseHorizonUntilParams struct {
	ID           pgtype.UUID
	HorizonUntil pgtype.Date
	UpdatedAt    pgtype.Timestamptz
}

// RaiseHorizonUntil moves the horizon forward, never back: GREATEST keeps the
// result independent of commit order when two requests extend it at once.
func (q *Queries) RaiseHorizonUntil(ctx context.Context, arg RaiseHorizonUntilParams) error {
	_, err := q.db.Exec(ctx, raiseHorizonUntil, arg.ID, arg.HorizonUntil, arg.UpdatedAt)
	return err
}

const setListingPublished = `-- name: SetListingPublished :one
UPDATE capacity_listing
SET published = $2, updated_at = $3
WHERE id = $1
RETURNING id, profile_id, weekly_capacity, readiness_lead_days, published, calendar_updated_at, horizon_until, created_at, updated_at
`

type SetListingPublishedParams struct {
	ID        pgtype.UUID
	Published bool
	UpdatedAt pgtype.Timestamptz
}

// SetListingPublished toggles visibility for PUT /listing/me/visibility. A
// hidden listing keeps its calendar and allocations; it simply drops out of
// search until re-enabled.
func (q *Queries) SetListingPublished(ctx context.Context, arg SetListingPublishedParams) (CapacityListing, error) {
	row := q.db.QueryRow(ctx, setListingPublished, arg.ID, arg.Published, arg.UpdatedAt)
	var i CapacityListing
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WeeklyCapacity,
		&i.ReadinessLeadDays,
		&i.Published,
		&i.CalendarUpdatedAt,
		&i.HorizonUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchCalendarUpdatedAt = `-- name: TouchCalendarUpdatedAt :exec
UPDATE capacity_listing
SET calendar_updated_at = $2, updated_at = $2
WHERE id = $1
`

type TouchCalendarUpdatedAtParams struct {
	ID                pgtype.UUID
	CalendarUpdatedAt pgtype.Timestamptz
}

// TouchCalendarUpdatedAt stamps the calendar as freshly edited. This is the
// only path that advances calendar_updated_at, so a listing whose owner never
// edits the calendar reads as stale and FR-021 keeps working.
func (q *Queries) TouchCalendarUpdatedAt(ctx context.Context, arg TouchCalendarUpdatedAtParams) error {
	_, err := q.db.Exec(ctx, touchCalendarUpdatedAt, arg.ID, arg.CalendarUpdatedAt)
	return err
}

const updateListing = `-- name: UpdateListing :one
UPDATE capacity_listing
SET weekly_capacity     = $2,
    readiness_lead_days = $3,
    updated_at          = $4
WHERE id = $1
RETURNING id, profile_id, weekly_capacity, readiness_lead_days, published, calendar_updated_at, horizon_until, created_at, updated_at
`

type UpdateListingParams struct {
	ID                pgtype.UUID
	WeeklyCapacity    int32
	ReadinessLeadDays int32
	UpdatedAt         pgtype.Timestamptz
}

// UpdateListing writes the owner-editable listing fields. Publication state is
// changed through SetListingPublished, not here, so a capacity edit never flips
// visibility by accident.
func (q *Queries) UpdateListing(ctx context.Context, arg UpdateListingParams) (CapacityListing, error) {
	row := q.db.QueryRow(ctx, updateListing,
		arg.ID,
		arg.WeeklyCapacity,
		arg.ReadinessLeadDays,
		arg.UpdatedAt,
	)
	var i CapacityListing
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WeeklyCapacity,
		&i.ReadinessLeadDays,
		&i.Published,
		&i.CalendarUpdatedAt,
		&i.HorizonUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPeriod = `-- name: UpsertPeriod :exec
INSERT INTO availability_period (
    id, listing_id, week_start, total_capacity, used_capacity, marked_full,
    created_at, updated_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, 0, $4, $5, $5
)
ON CONFLICT (listing_id, week_start) DO UPDATE
SET total_capacity = EXCLUDED.total_capacity,
    marked_full    = EXCLUDED.marked_full,
    updated_at     = EXCLUDED.updated_at
`

type UpsertPeriodParams struct {
	ListingID     pgtype.UUID
	WeekStart     pgtype.Date
	TotalCapacity int32
	MarkedFull    bool
	CreatedAt     pgtype.Timestamptz
}

// UpsertPeriod writes one period's capacity and full flag on an owner edit. The
// period row is expected to exist (EnsureHorizon generated it); ON CONFLICT
// updates it in place, keeping used_capacity untouched so an in-flight order is
// never disturbed.
func (q *Queries) UpsertPeriod(ctx context.Context, arg UpsertPeriodParams) error {
	_, err := q.db.Exec(ctx, upsertPeriod,
		arg.ListingID,
		arg.WeekStart,
		arg.TotalCapacity,
		arg.MarkedFull,
		arg.CreatedAt,
	)
	return err
}
