// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: masterdata.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCatalogByType = `-- name: CountCatalogByType :one
SELECT count(*)::bigint FROM catalog_item WHERE type = $1
`

func (q *Queries) CountCatalogByType(ctx context.Context, type_ ItemType) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogByType, type_)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countCities = `-- name: CountCities :one
SELECT count(*)::bigint FROM city
`

func (q *Queries) CountCities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCities)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countProvinces = `-- name: CountProvinces :one
SELECT count(*)::bigint FROM province
`

// CountProvinces, CountCities, CountCatalogByType back the seed verification and
// the "count is greater than zero" done-check.
func (q *Queries) CountProvinces(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProvinces)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listActiveCatalogItems = `-- name: ListActiveCatalogItems :many
SELECT id, type, name, active FROM catalog_item
WHERE type = $1 AND active
ORDER BY sort_order, name
`

type ListActiveCatalogItemsRow struct {
	ID     pgtype.UUID
	Type   ItemType
	Name   string
	Active bool
}

// ListActiveCatalogItems returns the active items of one type ordered for
// display, for GET /master/products and /master/machines.
func (q *Queries) ListActiveCatalogItems(ctx context.Context, type_ ItemType) ([]ListActiveCatalogItemsRow, error) {
	rows, err := q.db.Query(ctx, listActiveCatalogItems, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCatalogItemsRow{}
	for rows.Next() {
		var i ListActiveCatalogItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCities = `-- name: ListCities :many
SELECT code, province_code, name FROM city ORDER BY code
`

// ListCities returns every city ordered by code, for GET /regions/cities with no
// province filter.
func (q *Queries) ListCities(ctx context.Context) ([]City, error) {
	rows, err := q.db.Query(ctx, listCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(&i.Code, &i.ProvinceCode, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCitiesByProvince = `-- name: ListCitiesByProvince :many
SELECT code, province_code, name FROM city WHERE province_code = $1 ORDER BY code
`

// ListCitiesByProvince returns the cities of one province, for
// GET /regions/cities?province=.
func (q *Queries) ListCitiesByProvince(ctx context.Context, provinceCode string) ([]City, error) {
	rows, err := q.db.Query(ctx, listCitiesByProvince, provinceCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(&i.Code, &i.ProvinceCode, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvinces = `-- name: ListProvinces :many
SELECT code, name FROM province ORDER BY code
`

// ListProvinces returns every province ordered by code, for GET /regions/provinces.
func (q *Queries) ListProvinces(ctx context.Context) ([]Province, error) {
	rows, err := q.db.Query(ctx, listProvinces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Province{}
	for rows.Next() {
		var i Province
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCatalogItem = `-- name: UpsertCatalogItem :exec
INSERT INTO catalog_item (id, type, name, active, sort_order, created_at)
VALUES (gen_random_uuid(), $1, $2, true, $3, $4)
ON CONFLICT (type, name) DO UPDATE SET active = true, sort_order = EXCLUDED.sort_order
`

type UpsertCatalogItemParams struct {
	Type      ItemType
	Name      string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
}

// UpsertCatalogItem inserts a baseline product or machine type, or reactivates
// and reorders an existing one. Idempotent on (type, name): the seed can run
// twice without duplicating. created_at is supplied by the caller from the Clock
// since the column has no DB default.
func (q *Queries) UpsertCatalogItem(ctx context.Context, arg UpsertCatalogItemParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogItem,
		arg.Type,
		arg.Name,
		arg.SortOrder,
		arg.CreatedAt,
	)
	return err
}

const upsertCity = `-- name: UpsertCity :exec
INSERT INTO city (code, province_code, name)
VALUES ($1, $2, $3)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, province_code = EXCLUDED.province_code
`

type UpsertCityParams struct {
	Code         string
	ProvinceCode string
	Name         string
}

// UpsertCity inserts a city or updates its name. The code is already normalized
// (dots stripped, four digits) by the seeder before it reaches here, so the
// city_code_format and city_belongs_to_province constraints hold.
func (q *Queries) UpsertCity(ctx context.Context, arg UpsertCityParams) error {
	_, err := q.db.Exec(ctx, upsertCity, arg.Code, arg.ProvinceCode, arg.Name)
	return err
}

const upsertProvince = `-- name: UpsertProvince :exec

INSERT INTO province (code, name)
VALUES ($1, $2)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name
`

type UpsertProvinceParams struct {
	Code string
	Name string
}

// Master data queries: reference regions (province, city) and the baseline
// catalog of product and machine types. The seeders upsert by code/name so
// running them twice never duplicates and never deletes; business_profile
// references these rows, so a delete would orphan real data.
// UpsertProvince inserts a province or updates its name when the code already
// exists. Idempotent on code: the seed can run repeatedly without duplicating.
func (q *Queries) UpsertProvince(ctx context.Context, arg UpsertProvinceParams) error {
	_, err := q.db.Exec(ctx, upsertProvince, arg.Code, arg.Name)
	return err
}
