// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type CandidateStatus string

const (
	CandidateStatusAwaitingReply CandidateStatus = "awaiting_reply"
	CandidateStatusOffered       CandidateStatus = "offered"
	CandidateStatusRejected      CandidateStatus = "rejected"
	CandidateStatusExpired       CandidateStatus = "expired"
	CandidateStatusNotContinued  CandidateStatus = "not_continued"
	CandidateStatusAgreed        CandidateStatus = "agreed"
)

func (e *CandidateStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CandidateStatus(s)
	case string:
		*e = CandidateStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CandidateStatus: %T", src)
	}
	return nil
}

type NullCandidateStatus struct {
	CandidateStatus CandidateStatus
	Valid           bool // Valid is true if CandidateStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCandidateStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CandidateStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CandidateStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCandidateStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CandidateStatus), nil
}

type DeliveryStatus string

const (
	DeliveryStatusPending         DeliveryStatus = "pending"
	DeliveryStatusSent            DeliveryStatus = "sent"
	DeliveryStatusFailedPermanent DeliveryStatus = "failed_permanent"
)

func (e *DeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryStatus(s)
	case string:
		*e = DeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryStatus: %T", src)
	}
	return nil
}

type NullDeliveryStatus struct {
	DeliveryStatus DeliveryStatus
	Valid          bool // Valid is true if DeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryStatus), nil
}

type DisputeResult string

const (
	DisputeResultCancelled DisputeResult = "cancelled"
	DisputeResultContinued DisputeResult = "continued"
	DisputeResultConfirmed DisputeResult = "confirmed"
)

func (e *DisputeResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisputeResult(s)
	case string:
		*e = DisputeResult(s)
	default:
		return fmt.Errorf("unsupported scan type for DisputeResult: %T", src)
	}
	return nil
}

type NullDisputeResult struct {
	DisputeResult DisputeResult
	Valid         bool // Valid is true if DisputeResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisputeResult) Scan(value interface{}) error {
	if value == nil {
		ns.DisputeResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisputeResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisputeResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisputeResult), nil
}

type DisputeStatus string

const (
	DisputeStatusReported    DisputeStatus = "reported"
	DisputeStatusInMediation DisputeStatus = "in_mediation"
	DisputeStatusResolved    DisputeStatus = "resolved"
)

func (e *DisputeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisputeStatus(s)
	case string:
		*e = DisputeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DisputeStatus: %T", src)
	}
	return nil
}

type NullDisputeStatus struct {
	DisputeStatus DisputeStatus
	Valid         bool // Valid is true if DisputeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisputeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DisputeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisputeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisputeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisputeStatus), nil
}

type EventType string

const (
	EventTypeRequestReceived            EventType = "request_received"
	EventTypeOfferReceived              EventType = "offer_received"
	EventTypeCounterOffer               EventType = "counter_offer"
	EventTypeAgreementFormed            EventType = "agreement_formed"
	EventTypeOrderStatusChanged         EventType = "order_status_changed"
	EventTypePaymentRecord              EventType = "payment_record"
	EventTypeDeadlineApproaching        EventType = "deadline_approaching"
	EventTypeDeadlinePassed             EventType = "deadline_passed"
	EventTypeVerificationDecision       EventType = "verification_decision"
	EventTypeRatingRequest              EventType = "rating_request"
	EventTypeOrderCancelled             EventType = "order_cancelled"
	EventTypeConfirmationDueApproaching EventType = "confirmation_due_approaching"
	EventTypeOrderAutoClosed            EventType = "order_auto_closed"
	EventTypeItemProposalDecision       EventType = "item_proposal_decision"
	EventTypeCalendarStale              EventType = "calendar_stale"
	EventTypeRequestExpired             EventType = "request_expired"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType
	Valid     bool // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

type FileType string

const (
	FileTypeIdentityDocument FileType = "identity_document"
	FileTypeLocationPhoto    FileType = "location_photo"
)

func (e *FileType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileType(s)
	case string:
		*e = FileType(s)
	default:
		return fmt.Errorf("unsupported scan type for FileType: %T", src)
	}
	return nil
}

type NullFileType struct {
	FileType FileType
	Valid    bool // Valid is true if FileType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileType) Scan(value interface{}) error {
	if value == nil {
		ns.FileType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileType), nil
}

type ItemType string

const (
	ItemTypeProduct ItemType = "product"
	ItemTypeMachine ItemType = "machine"
)

func (e *ItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemType(s)
	case string:
		*e = ItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemType: %T", src)
	}
	return nil
}

type NullItemType struct {
	ItemType ItemType
	Valid    bool // Valid is true if ItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemType) Scan(value interface{}) error {
	if value == nil {
		ns.ItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemType), nil
}

type NotificationChannelType string

const (
	NotificationChannelTypeEmail    NotificationChannelType = "email"
	NotificationChannelTypeWhatsapp NotificationChannelType = "whatsapp"
)

func (e *NotificationChannelType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationChannelType(s)
	case string:
		*e = NotificationChannelType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationChannelType: %T", src)
	}
	return nil
}

type NullNotificationChannelType struct {
	NotificationChannelType NotificationChannelType
	Valid                   bool // Valid is true if NotificationChannelType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationChannelType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationChannelType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationChannelType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationChannelType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationChannelType), nil
}

type OfferParty string

const (
	OfferPartySubcontractor OfferParty = "subcontractor"
	OfferPartyBuyer         OfferParty = "buyer"
)

func (e *OfferParty) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OfferParty(s)
	case string:
		*e = OfferParty(s)
	default:
		return fmt.Errorf("unsupported scan type for OfferParty: %T", src)
	}
	return nil
}

type NullOfferParty struct {
	OfferParty OfferParty
	Valid      bool // Valid is true if OfferParty is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOfferParty) Scan(value interface{}) error {
	if value == nil {
		ns.OfferParty, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OfferParty.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOfferParty) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OfferParty), nil
}

type PaymentDirection string

const (
	PaymentDirectionSent     PaymentDirection = "sent"
	PaymentDirectionReceived PaymentDirection = "received"
)

func (e *PaymentDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentDirection(s)
	case string:
		*e = PaymentDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentDirection: %T", src)
	}
	return nil
}

type NullPaymentDirection struct {
	PaymentDirection PaymentDirection
	Valid            bool // Valid is true if PaymentDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentDirection) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentDirection), nil
}

type ProposalStatus string

const (
	ProposalStatusPending  ProposalStatus = "pending"
	ProposalStatusApproved ProposalStatus = "approved"
	ProposalStatusRejected ProposalStatus = "rejected"
)

func (e *ProposalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProposalStatus(s)
	case string:
		*e = ProposalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProposalStatus: %T", src)
	}
	return nil
}

type NullProposalStatus struct {
	ProposalStatus ProposalStatus
	Valid          bool // Valid is true if ProposalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProposalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProposalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProposalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProposalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProposalStatus), nil
}

type RateLimitTarget string

const (
	RateLimitTargetLoginAccount RateLimitTarget = "login_account"
	RateLimitTargetOtpPhone     RateLimitTarget = "otp_phone"
	RateLimitTargetOtpAddress   RateLimitTarget = "otp_address"
	RateLimitTargetQuotaRequest RateLimitTarget = "quota_request"
)

func (e *RateLimitTarget) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RateLimitTarget(s)
	case string:
		*e = RateLimitTarget(s)
	default:
		return fmt.Errorf("unsupported scan type for RateLimitTarget: %T", src)
	}
	return nil
}

type NullRateLimitTarget struct {
	RateLimitTarget RateLimitTarget
	Valid           bool // Valid is true if RateLimitTarget is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRateLimitTarget) Scan(value interface{}) error {
	if value == nil {
		ns.RateLimitTarget, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RateLimitTarget.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRateLimitTarget) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RateLimitTarget), nil
}

type VerificationPurpose string

const (
	VerificationPurposeEmail    VerificationPurpose = "email"
	VerificationPurposePhone    VerificationPurpose = "phone"
	VerificationPurposeRecovery VerificationPurpose = "recovery"
)

func (e *VerificationPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationPurpose(s)
	case string:
		*e = VerificationPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationPurpose: %T", src)
	}
	return nil
}

type NullVerificationPurpose struct {
	VerificationPurpose VerificationPurpose
	Valid               bool // Valid is true if VerificationPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationPurpose), nil
}

type VerificationStatus string

const (
	VerificationStatusPending  VerificationStatus = "pending"
	VerificationStatusApproved VerificationStatus = "approved"
	VerificationStatusRejected VerificationStatus = "rejected"
)

func (e *VerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationStatus(s)
	case string:
		*e = VerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationStatus: %T", src)
	}
	return nil
}

type NullVerificationStatus struct {
	VerificationStatus VerificationStatus
	Valid              bool // Valid is true if VerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationStatus), nil
}

type WorkOrderStatus string

const (
	WorkOrderStatusAccepted    WorkOrderStatus = "accepted"
	WorkOrderStatusProduction  WorkOrderStatus = "production"
	WorkOrderStatusCompleted   WorkOrderStatus = "completed"
	WorkOrderStatusShipped     WorkOrderStatus = "shipped"
	WorkOrderStatusConfirmed   WorkOrderStatus = "confirmed"
	WorkOrderStatusCancelled   WorkOrderStatus = "cancelled"
	WorkOrderStatusInMediation WorkOrderStatus = "in_mediation"
)

func (e *WorkOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkOrderStatus(s)
	case string:
		*e = WorkOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkOrderStatus: %T", src)
	}
	return nil
}

type NullWorkOrderStatus struct {
	WorkOrderStatus WorkOrderStatus
	Valid           bool // Valid is true if WorkOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorkOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkOrderStatus), nil
}

type AvailabilityPeriod struct {
	ID            pgtype.UUID
	ListingID     pgtype.UUID
	WeekStart     pgtype.Date
	TotalCapacity int32
	UsedCapacity  int32
	MarkedFull    bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type BusinessProfile struct {
	ID           pgtype.UUID
	AccountID    pgtype.UUID
	BusinessName string
	CityCode     string
	Latitude     pgtype.Numeric
	Longitude    pgtype.Numeric
	Description  pgtype.Text
	Verified     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type CapacityAllocation struct {
	ID          pgtype.UUID
	WorkOrderID pgtype.UUID
	PeriodID    pgtype.UUID
	Quantity    int32
	CreatedAt   pgtype.Timestamptz
	ReversedAt  pgtype.Timestamptz
}

type CapacityListing struct {
	ID                pgtype.UUID
	ProfileID         pgtype.UUID
	WeeklyCapacity    int32
	ReadinessLeadDays int32
	Published         bool
	CalendarUpdatedAt pgtype.Timestamptz
	HorizonUntil      pgtype.Date
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	StaleNotifiedAt   pgtype.Timestamptz
}

type CatalogItem struct {
	ID        pgtype.UUID
	Type      ItemType
	Name      string
	Active    bool
	SortOrder int32
	CreatedAt pgtype.Timestamptz
}

type City struct {
	Code         string
	ProvinceCode string
	Name         string
}

type Dispute struct {
	ID                 pgtype.UUID
	WorkOrderID        pgtype.UUID
	ReporterID         pgtype.UUID
	ReportBody         string
	Status             DisputeStatus
	AdminNote          pgtype.Text
	AllocationReversed pgtype.Bool
	LiablePartyID      pgtype.UUID
	HandledBy          pgtype.UUID
	ResolvedAt         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	Result             NullDisputeResult
}

type ItemProposal struct {
	ID           pgtype.UUID
	ProfileID    pgtype.UUID
	Type         ItemType
	ProposedName string
	Status       ProposalStatus
	AdminNote    pgtype.Text
	DecidedBy    pgtype.UUID
	DecidedAt    pgtype.Timestamptz
	ItemID       pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type ListingMachine struct {
	ListingID    pgtype.UUID
	ItemID       pgtype.UUID
	MachineCount int32
}

type ListingProduct struct {
	ListingID pgtype.UUID
	ItemID    pgtype.UUID
}

type Notification struct {
	ID            pgtype.UUID
	AccountID     pgtype.UUID
	Event         EventType
	Transactional bool
	Title         string
	Body          string
	Link          pgtype.Text
	ReadAt        pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type NotificationChannel struct {
	ID             pgtype.UUID
	NotificationID pgtype.UUID
	Channel        NotificationChannelType
	Status         DeliveryStatus
	Attempts       int16
	LastError      pgtype.Text
	AttemptedAt    pgtype.Timestamptz
	SentAt         pgtype.Timestamptz
}

type Offer struct {
	ID                pgtype.UUID
	CandidateID       pgtype.UUID
	Sequence          int32
	ProposedBy        OfferParty
	TotalPrice        int64
	ReadinessLeadDays int32
	Note              pgtype.Text
	CreatedAt         pgtype.Timestamptz
}

type PaymentRecord struct {
	ID          pgtype.UUID
	WorkOrderID pgtype.UUID
	ProfileID   pgtype.UUID
	Direction   PaymentDirection
	Date        pgtype.Date
	Note        pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type Province struct {
	Code string
	Name string
}

type QuotaRequest struct {
	ID            pgtype.UUID
	BuyerID       pgtype.UUID
	ProductItemID pgtype.UUID
	Quantity      int32
	Material      string
	Deadline      pgtype.Date
	Note          pgtype.Text
	ReplyDueAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type RateLimit struct {
	ID          pgtype.UUID
	Target      RateLimitTarget
	Key         string
	WindowStart pgtype.Timestamptz
	Count       int32
}

type RequestCandidate struct {
	ID              pgtype.UUID
	RequestID       pgtype.UUID
	ListingID       pgtype.UUID
	SubcontractorID pgtype.UUID
	Status          CandidateStatus
	RejectionReason pgtype.Text
	UpdatedAt       pgtype.Timestamptz
}

type Review struct {
	ID           pgtype.UUID
	WorkOrderID  pgtype.UUID
	ReviewerID   pgtype.UUID
	RevieweeID   pgtype.UUID
	Rating       int16
	Text         pgtype.Text
	Hidden       bool
	HiddenBy     pgtype.UUID
	HiddenAt     pgtype.Timestamptz
	HiddenReason pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type Session struct {
	ID            pgtype.UUID
	AccountID     pgtype.UUID
	TokenHash     []byte
	SourceAddress *netip.Addr
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	AccessedAt    pgtype.Timestamptz
}

type UploadedFile struct {
	ID             pgtype.UUID
	OwnerProfileID pgtype.UUID
	Type           FileType
	OriginalName   string
	MimeType       string
	SizeBytes      int32
	StoragePath    string
	CreatedAt      pgtype.Timestamptz
}

type UserAccount struct {
	ID                 pgtype.UUID
	Email              string
	Phone              string
	PasswordHash       string
	EmailVerified      bool
	PhoneVerified      bool
	RoleSubcontractor  bool
	RoleBuyer          bool
	RoleAdmin          bool
	NotifNontxEmail    bool
	NotifNontxWhatsapp bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type VerificationCode struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	Purpose    VerificationPurpose
	CodeHash   []byte
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type VerificationRequest struct {
	ID                     pgtype.UUID
	ProfileID              pgtype.UUID
	IdentityNumber         string
	IdentityFileID         pgtype.UUID
	LocationFileID         pgtype.UUID
	Status                 VerificationStatus
	AdminNote              pgtype.Text
	DecidedBy              pgtype.UUID
	DecidedAt              pgtype.Timestamptz
	ApplicantSourceAddress *netip.Addr
	CreatedAt              pgtype.Timestamptz
}

type WorkOrder struct {
	ID                 pgtype.UUID
	CandidateID        pgtype.UUID
	OfferID            pgtype.UUID
	BuyerID            pgtype.UUID
	SubcontractorID    pgtype.UUID
	Quantity           int32
	TotalPrice         int64
	Deadline           pgtype.Date
	ReadinessWeekStart pgtype.Date
	Status             WorkOrderStatus
	ShippedAt          pgtype.Timestamptz
	ConfirmedAt        pgtype.Timestamptz
	AutoConfirmed      bool
	CancelledByID      pgtype.UUID
	CancellationReason pgtype.Text
	CancelledAt        pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	ConfirmWarnSentAt  pgtype.Timestamptz
	LateNotifiedAt     pgtype.Timestamptz
	AutoConfirmBaseAt  pgtype.Timestamptz
	DeadlineWarnSentAt pgtype.Timestamptz
}

type WorkOrderStatusHistory struct {
	ID          pgtype.UUID
	WorkOrderID pgtype.UUID
	OldStatus   NullWorkOrderStatus
	NewStatus   WorkOrderStatus
	ChangedBy   pgtype.UUID
	BySystem    bool
	Note        pgtype.Text
	CreatedAt   pgtype.Timestamptz
}
