// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingChannels = `-- name: ClaimPendingChannels :many
SELECT
    nc.id            AS channel_id,
    nc.channel       AS channel,
    nc.attempts      AS attempts,
    n.title          AS title,
    n.body           AS body,
    ua.email         AS email,
    ua.phone         AS phone
FROM notification_channel nc
JOIN notification n  ON n.id = nc.notification_id
JOIN user_account ua ON ua.id = n.account_id
WHERE nc.status = 'pending' AND nc.attempts < 3
ORDER BY nc.attempted_at NULLS FIRST, nc.id
LIMIT $1
`

type ClaimPendingChannelsRow struct {
	ChannelID pgtype.UUID
	Channel   NotificationChannelType
	Attempts  int16
	Title     string
	Body      string
	Email     string
	Phone     string
}

// ClaimPendingChannels returns channels still awaiting delivery, oldest first
// (attempted_at NULLS FIRST puts never-tried rows ahead of retried ones), with
// the recipient address and message text joined in so the delivery job needs no
// second query. The attempts < 3 guard skips rows already exhausted; the
// delivery job runs under an advisory lock, so no row lock is needed to keep two
// instances off the same channel.
func (q *Queries) ClaimPendingChannels(ctx context.Context, limit int32) ([]ClaimPendingChannelsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingChannels, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingChannelsRow{}
	for rows.Next() {
		var i ClaimPendingChannelsRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.Channel,
			&i.Attempts,
			&i.Title,
			&i.Body,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notification WHERE account_id = $1 AND read_at IS NULL
`

// CountUnreadNotifications backs the unread_count field of NotificationList. It
// rides the partial idx_notification_unread index.
func (q *Queries) CountUnreadNotifications(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNotifPreferences = `-- name: GetNotifPreferences :one
SELECT notif_nontx_email, notif_nontx_whatsapp
FROM user_account
WHERE id = $1
`

type GetNotifPreferencesRow struct {
	NotifNontxEmail    bool
	NotifNontxWhatsapp bool
}

// GetNotifPreferences reads the two non-transactional channel toggles for one
// account, backing GET /notifications/preferences (FR-054).
func (q *Queries) GetNotifPreferences(ctx context.Context, id pgtype.UUID) (GetNotifPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getNotifPreferences, id)
	var i GetNotifPreferencesRow
	err := row.Scan(&i.NotifNontxEmail, &i.NotifNontxWhatsapp)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notification (id, account_id, event, transactional, title, body, link, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertNotificationParams struct {
	AccountID     pgtype.UUID
	Event         EventType
	Transactional bool
	Title         string
	Body          string
	Link          pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

// InsertNotification writes the in-platform notification row. It is always
// called inside the triggering event's transaction (Enqueue takes a pgx.Tx),
// so the notification is committed with the event or not at all (FR-086): a
// rolled-back order change leaves no orphan notification. created_at comes from
// the Clock, never a DB default (Rule 5).
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.AccountID,
		arg.Event,
		arg.Transactional,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.CreatedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertNotificationChannel = `-- name: InsertNotificationChannel :exec
INSERT INTO notification_channel (id, notification_id, channel, status, attempts)
VALUES (gen_random_uuid(), $1, $2, 'pending', 0)
`

type InsertNotificationChannelParams struct {
	NotificationID pgtype.UUID
	Channel        NotificationChannelType
}

// InsertNotificationChannel queues one external delivery channel for a
// notification. The row starts pending with zero attempts; the delivery job
// claims it later. The in-platform notification itself needs no channel row,
// it is always visible (FR-054); these rows track only email and WhatsApp fan
// out.
func (q *Queries) InsertNotificationChannel(ctx context.Context, arg InsertNotificationChannelParams) error {
	_, err := q.db.Exec(ctx, insertNotificationChannel, arg.NotificationID, arg.Channel)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, account_id, event, transactional, title, body, link, read_at, created_at FROM notification
WHERE account_id = $1
  AND (NOT $2::boolean OR read_at IS NULL)
  AND (
    $3::timestamptz IS NULL
    OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5::int
`

type ListNotificationsParams struct {
	AccountID     pgtype.UUID
	UnreadOnly    bool
	BeforeCreated pgtype.Timestamptz
	BeforeID      pgtype.UUID
	PageLimit     int32
}

// ListNotifications returns one account's notifications newest first, keyset
// paginated on (created_at, id) so the order is stable across pages even as new
// rows arrive. unread_only filters to still-unread rows (FR-051 list). A null
// before_created is the first page; later pages pass the last row's cursor.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.AccountID,
		arg.UnreadOnly,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Event,
			&i.Transactional,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChannelFailed = `-- name: MarkChannelFailed :exec
UPDATE notification_channel
SET attempts     = attempts + 1,
    last_error   = $2,
    attempted_at = $3,
    status       = CASE WHEN attempts + 1 >= 3
                        THEN 'failed_permanent'::delivery_status
                        ELSE 'pending'::delivery_status END
WHERE id = $1
`

type MarkChannelFailedParams struct {
	ID          pgtype.UUID
	LastError   pgtype.Text
	AttemptedAt pgtype.Timestamptz
}

// MarkChannelFailed records a failed attempt: attempts bumped, last_error and
// attempted_at stamped. The third failure (attempts reaching 3) flips status to
// failed_permanent (FR-085); earlier failures stay pending for the next tick.
// The CASE keeps status and attempts consistent with failed_after_three_attempts.
func (q *Queries) MarkChannelFailed(ctx context.Context, arg MarkChannelFailedParams) error {
	_, err := q.db.Exec(ctx, markChannelFailed, arg.ID, arg.LastError, arg.AttemptedAt)
	return err
}

const markChannelSent = `-- name: MarkChannelSent :exec
UPDATE notification_channel
SET status = 'sent', attempts = attempts + 1, attempted_at = $2, sent_at = $2
WHERE id = $1
`

type MarkChannelSentParams struct {
	ID          pgtype.UUID
	AttemptedAt pgtype.Timestamptz
}

// MarkChannelSent records a successful delivery: status sent, attempts bumped to
// reflect the try that worked, sent_at and attempted_at stamped from the Clock.
// A claimed row had attempts <= 2, so the +1 stays within attempts_max_three.
func (q *Queries) MarkChannelSent(ctx context.Context, arg MarkChannelSentParams) error {
	_, err := q.db.Exec(ctx, markChannelSent, arg.ID, arg.AttemptedAt)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notification
SET read_at = COALESCE(read_at, $3)
WHERE id = $1 AND account_id = $2
`

type MarkNotificationReadParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	ReadAt    pgtype.Timestamptz
}

// MarkNotificationRead stamps read_at on one notification the caller owns. The
// account_id predicate is the ownership check: a caller marking another
// account's id affects zero rows, which the handler turns into a 404, so the
// endpoint never confirms a notification the caller cannot see. COALESCE keeps
// the first read time, so re-marking an already-read notification still matches
// one row (idempotent 204) instead of a false 404.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.AccountID, arg.ReadAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateNotifPreferences = `-- name: UpdateNotifPreferences :one
UPDATE user_account
SET notif_nontx_email = $2, notif_nontx_whatsapp = $3, updated_at = $4
WHERE id = $1
RETURNING notif_nontx_email, notif_nontx_whatsapp
`

type UpdateNotifPreferencesParams struct {
	ID                 pgtype.UUID
	NotifNontxEmail    bool
	NotifNontxWhatsapp bool
	UpdatedAt          pgtype.Timestamptz
}

type UpdateNotifPreferencesRow struct {
	NotifNontxEmail    bool
	NotifNontxWhatsapp bool
}

// UpdateNotifPreferences writes the two non-transactional channel toggles and
// returns them, backing PUT /notifications/preferences. Transactional
// notifications ignore these flags, so only the non-transactional channels are
// affected (FR-091).
func (q *Queries) UpdateNotifPreferences(ctx context.Context, arg UpdateNotifPreferencesParams) (UpdateNotifPreferencesRow, error) {
	row := q.db.QueryRow(ctx, updateNotifPreferences,
		arg.ID,
		arg.NotifNontxEmail,
		arg.NotifNontxWhatsapp,
		arg.UpdatedAt,
	)
	var i UpdateNotifPreferencesRow
	err := row.Scan(&i.NotifNontxEmail, &i.NotifNontxWhatsapp)
	return i, err
}
