// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelWorkOrder = `-- name: CancelWorkOrder :one
UPDATE work_order
SET status = 'cancelled',
    cancelled_by_id = $2,
    cancellation_reason = $3,
    cancelled_at = $4
WHERE id = $1
RETURNING id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at
`

type CancelWorkOrderParams struct {
	ID                 pgtype.UUID
	CancelledByID      pgtype.UUID
	CancellationReason pgtype.Text
	CancelledAt        pgtype.Timestamptz
}

// Records a pre-production self-cancellation on the order itself (FR-065): the
// cancelling party's profile id, the reason, and the moment, moving status to
// 'cancelled'. Together the four columns satisfy the cancellation_complete
// CHECK. The allocation reversal (FR-020) runs separately under the same tx.
func (q *Queries) CancelWorkOrder(ctx context.Context, arg CancelWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, cancelWorkOrder,
		arg.ID,
		arg.CancelledByID,
		arg.CancellationReason,
		arg.CancelledAt,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const closeOtherCandidates = `-- name: CloseOtherCandidates :exec
UPDATE request_candidate
SET status = 'not_continued', updated_at = $3
WHERE request_id = $1 AND id <> $2 AND status NOT IN ('rejected', 'expired', 'agreed')
`

type CloseOtherCandidatesParams struct {
	RequestID pgtype.UUID
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

// Closes the request's other candidates once one is agreed (FR-034): they move to
// not_continued, leaving already rejected, expired, or agreed rows untouched.
func (q *Queries) CloseOtherCandidates(ctx context.Context, arg CloseOtherCandidatesParams) error {
	_, err := q.db.Exec(ctx, closeOtherCandidates, arg.RequestID, arg.ID, arg.UpdatedAt)
	return err
}

const estimateCapacityInRange = `-- name: EstimateCapacityInRange :one
WITH param AS (
    SELECT
        $1::uuid    AS listing_id,
        $2::date AS readiness_week,
        $3::date  AS deadline_week
)
SELECT
    coalesce(sum(pk.total_capacity - pk.used_capacity), 0)::bigint AS recorded_remaining,
    (greatest(0, (p.deadline_week - greatest(p.readiness_week, l.horizon_until + 7)) / 7 + 1) * l.weekly_capacity)::bigint AS uncreated_remaining
FROM capacity_listing l
CROSS JOIN param p
LEFT JOIN availability_period pk
       ON pk.listing_id = l.id
      AND NOT pk.marked_full
      AND pk.week_start BETWEEN p.readiness_week AND p.deadline_week
WHERE l.id = p.listing_id
GROUP BY l.id, l.weekly_capacity, l.horizon_until, p.readiness_week, p.deadline_week
`

type EstimateCapacityInRangeParams struct {
	ListingID     pgtype.UUID
	ReadinessWeek pgtype.Date
	DeadlineWeek  pgtype.Date
}

type EstimateCapacityInRangeRow struct {
	RecordedRemaining  int64
	UncreatedRemaining int64
}

// Optimistic remaining capacity across the readiness..deadline range, read BEFORE
// the accept path takes any lock. It mirrors search's formula (search.sql,
// FR-080/FR-088): recorded remaining over not-full periods plus an optimistic
// estimate for weeks past horizon_until counted at weekly_capacity. A shortfall
// here means the offer never had enough capacity, so accept fails fast with
// INSUFFICIENT_CAPACITY without locking. If this passes but the post-lock read is
// short, the capacity was definitively taken between the two reads
// (CAPACITY_ALREADY_TAKEN). Deadline is rounded to Monday in Go before calling.
func (q *Queries) EstimateCapacityInRange(ctx context.Context, arg EstimateCapacityInRangeParams) (EstimateCapacityInRangeRow, error) {
	row := q.db.QueryRow(ctx, estimateCapacityInRange, arg.ListingID, arg.ReadinessWeek, arg.DeadlineWeek)
	var i EstimateCapacityInRangeRow
	err := row.Scan(&i.RecordedRemaining, &i.UncreatedRemaining)
	return i, err
}

const getOfferForAccept = `-- name: GetOfferForAccept :one
SELECT
    o.id                        AS offer_id,
    o.candidate_id,
    o.total_price,
    o.readiness_lead_days,
    o.proposed_by,
    o.sequence,
    (SELECT max(sequence) FROM offer WHERE candidate_id = o.candidate_id)::int AS latest_sequence,
    c.status                    AS candidate_status,
    c.subcontractor_id,
    r.id                        AS request_id,
    r.buyer_id,
    r.product_item_id,
    r.quantity,
    r.deadline,
    r.reply_due_at,
    buyer.account_id            AS buyer_account,
    sub.account_id              AS subcontractor_account,
    l.id                        AS listing_id,
    l.weekly_capacity,
    l.horizon_until,
    EXISTS (
        SELECT 1 FROM request_candidate rc
        WHERE rc.request_id = r.id AND rc.status = 'agreed'
    ) AS request_has_agreement
FROM offer o
JOIN request_candidate c    ON c.id = o.candidate_id
JOIN quota_request r        ON r.id = c.request_id
JOIN capacity_listing l     ON l.id = c.listing_id
JOIN business_profile buyer ON buyer.id = r.buyer_id
JOIN business_profile sub   ON sub.id = c.subcontractor_id
WHERE o.id = $1
`

type GetOfferForAcceptRow struct {
	OfferID              pgtype.UUID
	CandidateID          pgtype.UUID
	TotalPrice           int64
	ReadinessLeadDays    int32
	ProposedBy           OfferParty
	Sequence             int32
	LatestSequence       int32
	CandidateStatus      CandidateStatus
	SubcontractorID      pgtype.UUID
	RequestID            pgtype.UUID
	BuyerID              pgtype.UUID
	ProductItemID        pgtype.UUID
	Quantity             int32
	Deadline             pgtype.Date
	ReplyDueAt           pgtype.Timestamptz
	BuyerAccount         pgtype.UUID
	SubcontractorAccount pgtype.UUID
	ListingID            pgtype.UUID
	WeeklyCapacity       int32
	HorizonUntil         pgtype.Date
	RequestHasAgreement  bool
}

// Loads everything the accept path needs about one offer: the offer terms, the
// candidate and its owning listing, the request and both parties, the listing
// capacity fields, whether the offer is the standing (latest) one, and whether
// any candidate of the request already reached an agreement. Keyed on the offer
// id the buyer accepts.
func (q *Queries) GetOfferForAccept(ctx context.Context, id pgtype.UUID) (GetOfferForAcceptRow, error) {
	row := q.db.QueryRow(ctx, getOfferForAccept, id)
	var i GetOfferForAcceptRow
	err := row.Scan(
		&i.OfferID,
		&i.CandidateID,
		&i.TotalPrice,
		&i.ReadinessLeadDays,
		&i.ProposedBy,
		&i.Sequence,
		&i.LatestSequence,
		&i.CandidateStatus,
		&i.SubcontractorID,
		&i.RequestID,
		&i.BuyerID,
		&i.ProductItemID,
		&i.Quantity,
		&i.Deadline,
		&i.ReplyDueAt,
		&i.BuyerAccount,
		&i.SubcontractorAccount,
		&i.ListingID,
		&i.WeeklyCapacity,
		&i.HorizonUntil,
		&i.RequestHasAgreement,
	)
	return i, err
}

const getWorkOrderForView = `-- name: GetWorkOrderForView :one
SELECT
    wo.id,
    wo.candidate_id,
    wo.offer_id,
    wo.buyer_id,
    wo.subcontractor_id,
    wo.quantity,
    wo.total_price,
    wo.deadline,
    wo.readiness_week_start,
    wo.status,
    wo.shipped_at,
    wo.confirmed_at,
    wo.auto_confirmed,
    wo.cancelled_by_id,
    wo.cancellation_reason,
    wo.cancelled_at,
    wo.created_at,
    buyer.account_id AS buyer_account,
    sub.account_id   AS subcontractor_account,
    r.product_item_id,
    o.readiness_lead_days
FROM work_order wo
JOIN business_profile buyer ON buyer.id = wo.buyer_id
JOIN business_profile sub   ON sub.id = wo.subcontractor_id
JOIN request_candidate c    ON c.id = wo.candidate_id
JOIN quota_request r        ON r.id = c.request_id
JOIN offer o                ON o.id = wo.offer_id
WHERE wo.id = $1
`

type GetWorkOrderForViewRow struct {
	ID                   pgtype.UUID
	CandidateID          pgtype.UUID
	OfferID              pgtype.UUID
	BuyerID              pgtype.UUID
	SubcontractorID      pgtype.UUID
	Quantity             int32
	TotalPrice           int64
	Deadline             pgtype.Date
	ReadinessWeekStart   pgtype.Date
	Status               WorkOrderStatus
	ShippedAt            pgtype.Timestamptz
	ConfirmedAt          pgtype.Timestamptz
	AutoConfirmed        bool
	CancelledByID        pgtype.UUID
	CancellationReason   pgtype.Text
	CancelledAt          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	BuyerAccount         pgtype.UUID
	SubcontractorAccount pgtype.UUID
	ProductItemID        pgtype.UUID
	ReadinessLeadDays    int32
}

// Loads one work order with the fields WorkOrderDetail needs beyond the row
// itself: both parties' account ids (for the party guard), the request's product
// item, and the offer's readiness lead. Keyed on the work order id; the caller
// checks the account ids against the principal so a non-party sees a 404.
func (q *Queries) GetWorkOrderForView(ctx context.Context, id pgtype.UUID) (GetWorkOrderForViewRow, error) {
	row := q.db.QueryRow(ctx, getWorkOrderForView, id)
	var i GetWorkOrderForViewRow
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.BuyerAccount,
		&i.SubcontractorAccount,
		&i.ProductItemID,
		&i.ReadinessLeadDays,
	)
	return i, err
}

const insertAllocation = `-- name: InsertAllocation :one
INSERT INTO capacity_allocation (work_order_id, period_id, quantity, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, work_order_id, period_id, quantity, created_at, reversed_at
`

type InsertAllocationParams struct {
	WorkOrderID pgtype.UUID
	PeriodID    pgtype.UUID
	Quantity    int32
	CreatedAt   pgtype.Timestamptz
}

// One capacity allocation row per used period (FR-077).
func (q *Queries) InsertAllocation(ctx context.Context, arg InsertAllocationParams) (CapacityAllocation, error) {
	row := q.db.QueryRow(ctx, insertAllocation,
		arg.WorkOrderID,
		arg.PeriodID,
		arg.Quantity,
		arg.CreatedAt,
	)
	var i CapacityAllocation
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.PeriodID,
		&i.Quantity,
		&i.CreatedAt,
		&i.ReversedAt,
	)
	return i, err
}

const insertOrderStatusHistory = `-- name: InsertOrderStatusHistory :exec
INSERT INTO work_order_status_history (
    work_order_id, old_status, new_status, changed_by, by_system, note, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOrderStatusHistoryParams struct {
	WorkOrderID pgtype.UUID
	OldStatus   NullWorkOrderStatus
	NewStatus   WorkOrderStatus
	ChangedBy   pgtype.UUID
	BySystem    bool
	Note        pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

// Records the opening status transition of a work order for its history trail.
func (q *Queries) InsertOrderStatusHistory(ctx context.Context, arg InsertOrderStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, insertOrderStatusHistory,
		arg.WorkOrderID,
		arg.OldStatus,
		arg.NewStatus,
		arg.ChangedBy,
		arg.BySystem,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const insertWorkOrder = `-- name: InsertWorkOrder :one
INSERT INTO work_order (
    candidate_id, offer_id, buyer_id, subcontractor_id,
    quantity, total_price, deadline, readiness_week_start, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at
`

type InsertWorkOrderParams struct {
	CandidateID        pgtype.UUID
	OfferID            pgtype.UUID
	BuyerID            pgtype.UUID
	SubcontractorID    pgtype.UUID
	Quantity           int32
	TotalPrice         int64
	Deadline           pgtype.Date
	ReadinessWeekStart pgtype.Date
	CreatedAt          pgtype.Timestamptz
}

// Inserts the work order at agreement formation. readiness_week_start is stored,
// not recomputed later (FR-084); status takes its 'accepted' default.
func (q *Queries) InsertWorkOrder(ctx context.Context, arg InsertWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, insertWorkOrder,
		arg.CandidateID,
		arg.OfferID,
		arg.BuyerID,
		arg.SubcontractorID,
		arg.Quantity,
		arg.TotalPrice,
		arg.Deadline,
		arg.ReadinessWeekStart,
		arg.CreatedAt,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAllocationsForReversal = `-- name: ListActiveAllocationsForReversal :many
SELECT a.id AS allocation_id, a.period_id, a.quantity, p.week_start
FROM capacity_allocation a
JOIN availability_period p ON p.id = a.period_id
WHERE a.work_order_id = $1 AND a.reversed_at IS NULL
ORDER BY p.week_start
FOR UPDATE OF a, p
`

type ListActiveAllocationsForReversalRow struct {
	AllocationID pgtype.UUID
	PeriodID     pgtype.UUID
	Quantity     int32
	WeekStart    pgtype.Date
}

// Locks the order's still-active allocation rows together with their periods,
// ordered ascending by week_start. The order mirrors the formation lock order of
// R-04 (LockPeriodsInRange), the deadlock preventer: two transactions touching
// the same periods always take them in the same order. Already reversed rows are
// left out, so a repeat reversal refunds nothing rather than double-crediting.
func (q *Queries) ListActiveAllocationsForReversal(ctx context.Context, workOrderID pgtype.UUID) ([]ListActiveAllocationsForReversalRow, error) {
	rows, err := q.db.Query(ctx, listActiveAllocationsForReversal, workOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAllocationsForReversalRow{}
	for rows.Next() {
		var i ListActiveAllocationsForReversalRow
		if err := rows.Scan(
			&i.AllocationID,
			&i.PeriodID,
			&i.Quantity,
			&i.WeekStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOtherCandidatesToNotify = `-- name: ListOtherCandidatesToNotify :many
SELECT c.id AS candidate_id, sub.account_id AS subcontractor_account
FROM request_candidate c
JOIN business_profile sub ON sub.id = c.subcontractor_id
WHERE c.request_id = $1 AND c.id <> $2 AND c.status NOT IN ('rejected', 'expired')
`

type ListOtherCandidatesToNotifyParams struct {
	RequestID pgtype.UUID
	ID        pgtype.UUID
}

type ListOtherCandidatesToNotifyRow struct {
	CandidateID          pgtype.UUID
	SubcontractorAccount pgtype.UUID
}

// The other still-open candidates of the request, so their subcontractors learn
// the request was agreed elsewhere. Rejected and expired candidates are left out.
func (q *Queries) ListOtherCandidatesToNotify(ctx context.Context, arg ListOtherCandidatesToNotifyParams) ([]ListOtherCandidatesToNotifyRow, error) {
	rows, err := q.db.Query(ctx, listOtherCandidatesToNotify, arg.RequestID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOtherCandidatesToNotifyRow{}
	for rows.Next() {
		var i ListOtherCandidatesToNotifyRow
		if err := rows.Scan(&i.CandidateID, &i.SubcontractorAccount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkOrderAllocations = `-- name: ListWorkOrderAllocations :many
SELECT p.week_start, p.total_capacity, p.used_capacity, p.marked_full
FROM capacity_allocation a
JOIN availability_period p ON p.id = a.period_id
WHERE a.work_order_id = $1 AND a.reversed_at IS NULL
ORDER BY p.week_start
`

type ListWorkOrderAllocationsRow struct {
	WeekStart     pgtype.Date
	TotalCapacity int32
	UsedCapacity  int32
	MarkedFull    bool
}

// The still-active allocation periods of one work order with the period figures
// WorkOrderDetail renders, ordered ascending by week_start. Reversed rows are
// left out so a cancelled order shows no live allocation.
func (q *Queries) ListWorkOrderAllocations(ctx context.Context, workOrderID pgtype.UUID) ([]ListWorkOrderAllocationsRow, error) {
	rows, err := q.db.Query(ctx, listWorkOrderAllocations, workOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkOrderAllocationsRow{}
	for rows.Next() {
		var i ListWorkOrderAllocationsRow
		if err := rows.Scan(
			&i.WeekStart,
			&i.TotalCapacity,
			&i.UsedCapacity,
			&i.MarkedFull,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkOrderStatusHistory = `-- name: ListWorkOrderStatusHistory :many
SELECT new_status, created_at, note
FROM work_order_status_history
WHERE work_order_id = $1
ORDER BY created_at, id
`

type ListWorkOrderStatusHistoryRow struct {
	NewStatus WorkOrderStatus
	CreatedAt pgtype.Timestamptz
	Note      pgtype.Text
}

// The status trail of one work order, oldest first, for WorkOrderDetail. Rides
// idx_status_history_order (work_order_id, created_at) so it stays ordered
// without a sort.
func (q *Queries) ListWorkOrderStatusHistory(ctx context.Context, workOrderID pgtype.UUID) ([]ListWorkOrderStatusHistoryRow, error) {
	rows, err := q.db.Query(ctx, listWorkOrderStatusHistory, workOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkOrderStatusHistoryRow{}
	for rows.Next() {
		var i ListWorkOrderStatusHistoryRow
		if err := rows.Scan(&i.NewStatus, &i.CreatedAt, &i.Note); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkOrdersForParty = `-- name: ListWorkOrdersForParty :many
SELECT id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at
FROM work_order wo
WHERE (
        ($1::text = 'as_buyer' AND wo.buyer_id = $2::uuid)
        OR ($1::text = 'as_subcontractor' AND wo.subcontractor_id = $2::uuid)
        OR ($1::text NOT IN ('as_buyer', 'as_subcontractor')
            AND (wo.buyer_id = $2::uuid OR wo.subcontractor_id = $2::uuid))
    )
  AND (
        cardinality($3::work_order_status[]) = 0
        OR wo.status = ANY($3::work_order_status[])
    )
  AND (
        $4::timestamptz IS NULL
        OR (wo.created_at, wo.id) < ($4::timestamptz, $5::uuid)
    )
ORDER BY wo.created_at DESC, wo.id DESC
LIMIT $6::int
`

type ListWorkOrdersForPartyParams struct {
	RoleFilter    string
	ProfileID     pgtype.UUID
	StatusFilter  []WorkOrderStatus
	BeforeCreated pgtype.Timestamptz
	BeforeID      pgtype.UUID
	PageLimit     int32
}

// One party's work orders newest first, keyset paginated on (created_at, id) so
// the order is stable across pages (FR-038). role_filter selects the side:
// 'as_buyer' matches the buyer profile, 'as_subcontractor' the subcontractor
// profile, any other value matches either. An empty status_filter array means no
// status restriction; otherwise only the listed statuses pass. A null
// before_created is the first page.
func (q *Queries) ListWorkOrdersForParty(ctx context.Context, arg ListWorkOrdersForPartyParams) ([]WorkOrder, error) {
	rows, err := q.db.Query(ctx, listWorkOrdersForParty,
		arg.RoleFilter,
		arg.ProfileID,
		arg.StatusFilter,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkOrder{}
	for rows.Next() {
		var i WorkOrder
		if err := rows.Scan(
			&i.ID,
			&i.CandidateID,
			&i.OfferID,
			&i.BuyerID,
			&i.SubcontractorID,
			&i.Quantity,
			&i.TotalPrice,
			&i.Deadline,
			&i.ReadinessWeekStart,
			&i.Status,
			&i.ShippedAt,
			&i.ConfirmedAt,
			&i.AutoConfirmed,
			&i.CancelledByID,
			&i.CancellationReason,
			&i.CancelledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockListingByID = `-- name: LockListingByID :one
SELECT id, profile_id, weekly_capacity, readiness_lead_days, published, calendar_updated_at, horizon_until, created_at, updated_at FROM capacity_listing WHERE id = $1 FOR UPDATE
`

// Takes a row lock on a listing by its own id, so the accept path can extend the
// calendar horizon (FR-088) under the same lock the listing owner's edits take.
func (q *Queries) LockListingByID(ctx context.Context, id pgtype.UUID) (CapacityListing, error) {
	row := q.db.QueryRow(ctx, lockListingByID, id)
	var i CapacityListing
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WeeklyCapacity,
		&i.ReadinessLeadDays,
		&i.Published,
		&i.CalendarUpdatedAt,
		&i.HorizonUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPeriodsInRange = `-- name: LockPeriodsInRange :many
SELECT id, listing_id, week_start, total_capacity, used_capacity, marked_full, created_at, updated_at FROM availability_period
WHERE listing_id = $1 AND week_start BETWEEN $2 AND $3
ORDER BY week_start
FOR UPDATE
`

type LockPeriodsInRangeParams struct {
	ListingID   pgtype.UUID
	WeekStart   pgtype.Date
	WeekStart_2 pgtype.Date
}

// Locks every candidate period in the readiness..deadline range at once, ordered
// ascending by week_start. The order is the deadlock preventer of R-04, not tidy
// housekeeping: two agreements touching the same periods always lock them in the
// same order, so the second waits and then sees the reduced capacity.
func (q *Queries) LockPeriodsInRange(ctx context.Context, arg LockPeriodsInRangeParams) ([]AvailabilityPeriod, error) {
	rows, err := q.db.Query(ctx, lockPeriodsInRange, arg.ListingID, arg.WeekStart, arg.WeekStart_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilityPeriod{}
	for rows.Next() {
		var i AvailabilityPeriod
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.WeekStart,
			&i.TotalCapacity,
			&i.UsedCapacity,
			&i.MarkedFull,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkOrderForReversal = `-- name: LockWorkOrderForReversal :one
SELECT id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at FROM work_order WHERE id = $1 FOR UPDATE
`

// Takes a row lock on the work order whose allocation is being reversed, so the
// reversal runs under a lock in the same spirit as formation locking the listing.
func (q *Queries) LockWorkOrderForReversal(ctx context.Context, id pgtype.UUID) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, lockWorkOrderForReversal, id)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockWorkOrderForStatusChange = `-- name: LockWorkOrderForStatusChange :one
SELECT id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at FROM work_order WHERE id = $1 FOR UPDATE
`

// Row-locks a work order before a status transition so a concurrent status
// change or cancellation on the same order serializes, matching the reversal
// lock spirit (R-04).
func (q *Queries) LockWorkOrderForStatusChange(ctx context.Context, id pgtype.UUID) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, lockWorkOrderForStatusChange, id)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const lowerUsedCapacity = `-- name: LowerUsedCapacity :one
UPDATE availability_period
SET used_capacity = used_capacity - $2, updated_at = $3
WHERE id = $1
RETURNING id, listing_id, week_start, total_capacity, used_capacity, marked_full, created_at, updated_at
`

type LowerUsedCapacityParams struct {
	ID           pgtype.UUID
	UsedCapacity int32
	UpdatedAt    pgtype.Timestamptz
}

// Returns a period's used_capacity to its pre-order value by subtracting the
// reversed amount. The inverse of RaiseUsedCapacity; the quantity comes from the
// allocation row being reversed, so used_capacity never drops below zero.
func (q *Queries) LowerUsedCapacity(ctx context.Context, arg LowerUsedCapacityParams) (AvailabilityPeriod, error) {
	row := q.db.QueryRow(ctx, lowerUsedCapacity, arg.ID, arg.UsedCapacity, arg.UpdatedAt)
	var i AvailabilityPeriod
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.WeekStart,
		&i.TotalCapacity,
		&i.UsedCapacity,
		&i.MarkedFull,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAllocationReversed = `-- name: MarkAllocationReversed :exec
UPDATE capacity_allocation
SET reversed_at = $2
WHERE id = $1 AND reversed_at IS NULL
`

type MarkAllocationReversedParams struct {
	ID         pgtype.UUID
	ReversedAt pgtype.Timestamptz
}

// Marks one allocation row reversed without deleting it (FR-020), keeping the
// audit trail. The reversed_at guard makes the write idempotent under a repeat.
func (q *Queries) MarkAllocationReversed(ctx context.Context, arg MarkAllocationReversedParams) error {
	_, err := q.db.Exec(ctx, markAllocationReversed, arg.ID, arg.ReversedAt)
	return err
}

const raiseUsedCapacity = `-- name: RaiseUsedCapacity :one
UPDATE availability_period
SET used_capacity = used_capacity + $2, updated_at = $3
WHERE id = $1
RETURNING id, listing_id, week_start, total_capacity, used_capacity, marked_full, created_at, updated_at
`

type RaiseUsedCapacityParams struct {
	ID           pgtype.UUID
	UsedCapacity int32
	UpdatedAt    pgtype.Timestamptz
}

// Raises a period's used_capacity by the allocated amount. The
// used_capacity_within_total CHECK is the FR-079/SC-018 storage-level safety net:
// if the fill logic ever over-allocates, this fails hard instead of corrupting.
func (q *Queries) RaiseUsedCapacity(ctx context.Context, arg RaiseUsedCapacityParams) (AvailabilityPeriod, error) {
	row := q.db.QueryRow(ctx, raiseUsedCapacity, arg.ID, arg.UsedCapacity, arg.UpdatedAt)
	var i AvailabilityPeriod
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.WeekStart,
		&i.TotalCapacity,
		&i.UsedCapacity,
		&i.MarkedFull,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCandidateAgreed = `-- name: SetCandidateAgreed :exec
UPDATE request_candidate
SET status = 'agreed', updated_at = $2
WHERE id = $1
`

type SetCandidateAgreedParams struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

// Marks the winning candidate agreed. The partial unique index
// idx_one_agreement_per_request enforces at most one agreement per request, so a
// concurrent second agreement violates it and the transaction fails (FR-036).
func (q *Queries) SetCandidateAgreed(ctx context.Context, arg SetCandidateAgreedParams) error {
	_, err := q.db.Exec(ctx, setCandidateAgreed, arg.ID, arg.UpdatedAt)
	return err
}

const updateWorkOrderStatus = `-- name: UpdateWorkOrderStatus :one
UPDATE work_order
SET status = $2,
    shipped_at = CASE WHEN $2 = 'shipped'::work_order_status THEN $3 ELSE shipped_at END
WHERE id = $1
RETURNING id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at
`

type UpdateWorkOrderStatusParams struct {
	ID        pgtype.UUID
	Status    WorkOrderStatus
	ShippedAt pgtype.Timestamptz
}

// Advances a work order to its next forward status. shipped_at is stamped only
// on the move into 'shipped' and left untouched otherwise, so it records the
// moment shipment was declared (the auto-confirm clock start, FR-068).
func (q *Queries) UpdateWorkOrderStatus(ctx context.Context, arg UpdateWorkOrderStatusParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, updateWorkOrderStatus, arg.ID, arg.Status, arg.ShippedAt)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}
