// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const autoConfirmWorkOrder = `-- name: AutoConfirmWorkOrder :one
UPDATE work_order
SET status = 'confirmed', auto_confirmed = true, confirmed_at = $2
WHERE work_order.id = $1 AND work_order.status = 'shipped'
  AND NOT EXISTS (
        SELECT 1 FROM dispute d
        WHERE d.work_order_id = work_order.id AND d.status <> 'resolved'
  )
RETURNING id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at, confirm_warn_sent_at, late_notified_at, auto_confirm_base_at
`

type AutoConfirmWorkOrderParams struct {
	ID          pgtype.UUID
	ConfirmedAt pgtype.Timestamptz
}

// Closes one shipped order as system-confirmed (FR-068): status to 'confirmed',
// auto_confirmed true (marking this closure as the system's, not a party's), and
// confirmed_at stamped from the caller's Clock instant. The status = 'shipped'
// guard makes the write a no-op if a party confirmed the order since the scan. The
// NOT EXISTS open-dispute guard closes the race where a dispute is reported between
// the scan and this update: a disputed order stays open even though its status is
// still 'shipped' (FR-070). A returned row means this call did the closing.
// Together the columns satisfy the auto_confirm_needs_confirmation and
// shipped_before_confirmed CHECKs.
func (q *Queries) AutoConfirmWorkOrder(ctx context.Context, arg AutoConfirmWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, autoConfirmWorkOrder, arg.ID, arg.ConfirmedAt)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.ConfirmWarnSentAt,
		&i.LateNotifiedAt,
		&i.AutoConfirmBaseAt,
	)
	return i, err
}

const cancelWorkOrder = `-- name: CancelWorkOrder :one
UPDATE work_order
SET status = 'cancelled',
    cancelled_by_id = $2,
    cancellation_reason = $3,
    cancelled_at = $4
WHERE id = $1
RETURNING id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at, confirm_warn_sent_at, late_notified_at, auto_confirm_base_at
`

type CancelWorkOrderParams struct {
	ID                 pgtype.UUID
	CancelledByID      pgtype.UUID
	CancellationReason pgtype.Text
	CancelledAt        pgtype.Timestamptz
}

// Records a pre-production self-cancellation on the order itself (FR-065): the
// cancelling party's profile id, the reason, and the moment, moving status to
// 'cancelled'. Together the four columns satisfy the cancellation_complete
// CHECK. The allocation reversal (FR-020) runs separately under the same tx.
func (q *Queries) CancelWorkOrder(ctx context.Context, arg CancelWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, cancelWorkOrder,
		arg.ID,
		arg.CancelledByID,
		arg.CancellationReason,
		arg.CancelledAt,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.ConfirmWarnSentAt,
		&i.LateNotifiedAt,
		&i.AutoConfirmBaseAt,
	)
	return i, err
}

const closeOtherCandidates = `-- name: CloseOtherCandidates :exec
UPDATE request_candidate
SET status = 'not_continued', updated_at = $3
WHERE request_id = $1 AND id <> $2 AND status NOT IN ('rejected', 'expired', 'agreed')
`

type CloseOtherCandidatesParams struct {
	RequestID pgtype.UUID
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

// Closes the request's other candidates once one is agreed (FR-034): they move to
// not_continued, leaving already rejected, expired, or agreed rows untouched.
func (q *Queries) CloseOtherCandidates(ctx context.Context, arg CloseOtherCandidatesParams) error {
	_, err := q.db.Exec(ctx, closeOtherCandidates, arg.RequestID, arg.ID, arg.UpdatedAt)
	return err
}

const estimateCapacityInRange = `-- name: EstimateCapacityInRange :one
WITH param AS (
    SELECT
        $1::uuid    AS listing_id,
        $2::date AS readiness_week,
        $3::date  AS deadline_week
)
SELECT
    coalesce(sum(pk.total_capacity - pk.used_capacity), 0)::bigint AS recorded_remaining,
    (greatest(0, (p.deadline_week - greatest(p.readiness_week, l.horizon_until + 7)) / 7 + 1) * l.weekly_capacity)::bigint AS uncreated_remaining
FROM capacity_listing l
CROSS JOIN param p
LEFT JOIN availability_period pk
       ON pk.listing_id = l.id
      AND NOT pk.marked_full
      AND pk.week_start BETWEEN p.readiness_week AND p.deadline_week
WHERE l.id = p.listing_id
GROUP BY l.id, l.weekly_capacity, l.horizon_until, p.readiness_week, p.deadline_week
`

type EstimateCapacityInRangeParams struct {
	ListingID     pgtype.UUID
	ReadinessWeek pgtype.Date
	DeadlineWeek  pgtype.Date
}

type EstimateCapacityInRangeRow struct {
	RecordedRemaining  int64
	UncreatedRemaining int64
}

// Optimistic remaining capacity across the readiness..deadline range, read BEFORE
// the accept path takes any lock. It mirrors search's formula (search.sql,
// FR-080/FR-088): recorded remaining over not-full periods plus an optimistic
// estimate for weeks past horizon_until counted at weekly_capacity. A shortfall
// here means the offer never had enough capacity, so accept fails fast with
// INSUFFICIENT_CAPACITY without locking. If this passes but the post-lock read is
// short, the capacity was definitively taken between the two reads
// (CAPACITY_ALREADY_TAKEN). Deadline is rounded to Monday in Go before calling.
func (q *Queries) EstimateCapacityInRange(ctx context.Context, arg EstimateCapacityInRangeParams) (EstimateCapacityInRangeRow, error) {
	row := q.db.QueryRow(ctx, estimateCapacityInRange, arg.ListingID, arg.ReadinessWeek, arg.DeadlineWeek)
	var i EstimateCapacityInRangeRow
	err := row.Scan(&i.RecordedRemaining, &i.UncreatedRemaining)
	return i, err
}

const forceConfirmWorkOrder = `-- name: ForceConfirmWorkOrder :one
UPDATE work_order
SET status = 'confirmed', auto_confirmed = false, confirmed_at = $2
WHERE id = $1 AND status = 'in_mediation'
RETURNING id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at, confirm_warn_sent_at, late_notified_at, auto_confirm_base_at
`

type ForceConfirmWorkOrderParams struct {
	ID          pgtype.UUID
	ConfirmedAt pgtype.Timestamptz
}

// Forces a mediated order to 'confirmed' when the admin closes the dispute that way
// (FR-067): the admin accepts the order on the buyer's behalf. auto_confirmed stays
// false because this is an admin decision, not the system's 7-day closure, so the
// two are distinguishable in the trail; confirmed_at is the Clock instant. The
// status = 'in_mediation' guard means a returned row confirms this call did the
// move. confirmed_at >= shipped_at holds by shipped_before_confirmed when the order
// had shipped; an order confirmed from an earlier status has shipped_at NULL and the
// CHECK is satisfied vacuously.
func (q *Queries) ForceConfirmWorkOrder(ctx context.Context, arg ForceConfirmWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, forceConfirmWorkOrder, arg.ID, arg.ConfirmedAt)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.ConfirmWarnSentAt,
		&i.LateNotifiedAt,
		&i.AutoConfirmBaseAt,
	)
	return i, err
}

const getDisputeForAdmin = `-- name: GetDisputeForAdmin :one
SELECT id, work_order_id, reporter_id, report_body, status, admin_note, allocation_reversed, liable_party_id, handled_by, resolved_at, created_at, result FROM dispute WHERE id = $1 FOR UPDATE
`

// Loads and row-locks one dispute for the mediate and resolve paths (FR-046,
// FR-067). FOR UPDATE serializes two admins acting on the same dispute: the second
// waits, then sees the resolved status and is rejected by the resolve guard. Keyed
// on the dispute id from the path; a missing row is the handler's 404.
func (q *Queries) GetDisputeForAdmin(ctx context.Context, id pgtype.UUID) (Dispute, error) {
	row := q.db.QueryRow(ctx, getDisputeForAdmin, id)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.ReporterID,
		&i.ReportBody,
		&i.Status,
		&i.AdminNote,
		&i.AllocationReversed,
		&i.LiablePartyID,
		&i.HandledBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.Result,
	)
	return i, err
}

const getOfferForAccept = `-- name: GetOfferForAccept :one
SELECT
    o.id                        AS offer_id,
    o.candidate_id,
    o.total_price,
    o.readiness_lead_days,
    o.proposed_by,
    o.sequence,
    (SELECT max(sequence) FROM offer WHERE candidate_id = o.candidate_id)::int AS latest_sequence,
    c.status                    AS candidate_status,
    c.subcontractor_id,
    r.id                        AS request_id,
    r.buyer_id,
    r.product_item_id,
    r.quantity,
    r.deadline,
    r.reply_due_at,
    buyer.account_id            AS buyer_account,
    sub.account_id              AS subcontractor_account,
    l.id                        AS listing_id,
    l.weekly_capacity,
    l.horizon_until,
    EXISTS (
        SELECT 1 FROM request_candidate rc
        WHERE rc.request_id = r.id AND rc.status = 'agreed'
    ) AS request_has_agreement
FROM offer o
JOIN request_candidate c    ON c.id = o.candidate_id
JOIN quota_request r        ON r.id = c.request_id
JOIN capacity_listing l     ON l.id = c.listing_id
JOIN business_profile buyer ON buyer.id = r.buyer_id
JOIN business_profile sub   ON sub.id = c.subcontractor_id
WHERE o.id = $1
`

type GetOfferForAcceptRow struct {
	OfferID              pgtype.UUID
	CandidateID          pgtype.UUID
	TotalPrice           int64
	ReadinessLeadDays    int32
	ProposedBy           OfferParty
	Sequence             int32
	LatestSequence       int32
	CandidateStatus      CandidateStatus
	SubcontractorID      pgtype.UUID
	RequestID            pgtype.UUID
	BuyerID              pgtype.UUID
	ProductItemID        pgtype.UUID
	Quantity             int32
	Deadline             pgtype.Date
	ReplyDueAt           pgtype.Timestamptz
	BuyerAccount         pgtype.UUID
	SubcontractorAccount pgtype.UUID
	ListingID            pgtype.UUID
	WeeklyCapacity       int32
	HorizonUntil         pgtype.Date
	RequestHasAgreement  bool
}

// Loads everything the accept path needs about one offer: the offer terms, the
// candidate and its owning listing, the request and both parties, the listing
// capacity fields, whether the offer is the standing (latest) one, and whether
// any candidate of the request already reached an agreement. Keyed on the offer
// id the buyer accepts.
func (q *Queries) GetOfferForAccept(ctx context.Context, id pgtype.UUID) (GetOfferForAcceptRow, error) {
	row := q.db.QueryRow(ctx, getOfferForAccept, id)
	var i GetOfferForAcceptRow
	err := row.Scan(
		&i.OfferID,
		&i.CandidateID,
		&i.TotalPrice,
		&i.ReadinessLeadDays,
		&i.ProposedBy,
		&i.Sequence,
		&i.LatestSequence,
		&i.CandidateStatus,
		&i.SubcontractorID,
		&i.RequestID,
		&i.BuyerID,
		&i.ProductItemID,
		&i.Quantity,
		&i.Deadline,
		&i.ReplyDueAt,
		&i.BuyerAccount,
		&i.SubcontractorAccount,
		&i.ListingID,
		&i.WeeklyCapacity,
		&i.HorizonUntil,
		&i.RequestHasAgreement,
	)
	return i, err
}

const getStatusBeforeMediation = `-- name: GetStatusBeforeMediation :one
SELECT old_status
FROM work_order_status_history
WHERE work_order_id = $1 AND new_status = 'in_mediation'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// The status a work order held immediately before it entered mediation, read from
// the old_status of the most recent transition into 'in_mediation' (FR-067). The
// 'continued' resolution restores the order to this status. old_status is read
// straight off the mediation history row rather than inferred, so a restore lands
// on exactly the status the order left, even if it moved through several statuses
// earlier in its life. Newest such row wins in case an order was mediated more
// than once over its lifetime.
func (q *Queries) GetStatusBeforeMediation(ctx context.Context, workOrderID pgtype.UUID) (NullWorkOrderStatus, error) {
	row := q.db.QueryRow(ctx, getStatusBeforeMediation, workOrderID)
	var old_status NullWorkOrderStatus
	err := row.Scan(&old_status)
	return old_status, err
}

const getWorkOrderForView = `-- name: GetWorkOrderForView :one
SELECT
    wo.id,
    wo.candidate_id,
    wo.offer_id,
    wo.buyer_id,
    wo.subcontractor_id,
    wo.quantity,
    wo.total_price,
    wo.deadline,
    wo.readiness_week_start,
    wo.status,
    wo.shipped_at,
    wo.auto_confirm_base_at,
    wo.confirmed_at,
    wo.auto_confirmed,
    wo.cancelled_by_id,
    wo.cancellation_reason,
    wo.cancelled_at,
    wo.created_at,
    buyer.account_id AS buyer_account,
    sub.account_id   AS subcontractor_account,
    r.product_item_id,
    o.readiness_lead_days,
    EXISTS (
        SELECT 1 FROM dispute d
        WHERE d.work_order_id = wo.id AND d.status <> 'resolved'
    ) AS has_open_dispute
FROM work_order wo
JOIN business_profile buyer ON buyer.id = wo.buyer_id
JOIN business_profile sub   ON sub.id = wo.subcontractor_id
JOIN request_candidate c    ON c.id = wo.candidate_id
JOIN quota_request r        ON r.id = c.request_id
JOIN offer o                ON o.id = wo.offer_id
WHERE wo.id = $1
`

type GetWorkOrderForViewRow struct {
	ID                   pgtype.UUID
	CandidateID          pgtype.UUID
	OfferID              pgtype.UUID
	BuyerID              pgtype.UUID
	SubcontractorID      pgtype.UUID
	Quantity             int32
	TotalPrice           int64
	Deadline             pgtype.Date
	ReadinessWeekStart   pgtype.Date
	Status               WorkOrderStatus
	ShippedAt            pgtype.Timestamptz
	AutoConfirmBaseAt    pgtype.Timestamptz
	ConfirmedAt          pgtype.Timestamptz
	AutoConfirmed        bool
	CancelledByID        pgtype.UUID
	CancellationReason   pgtype.Text
	CancelledAt          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	BuyerAccount         pgtype.UUID
	SubcontractorAccount pgtype.UUID
	ProductItemID        pgtype.UUID
	ReadinessLeadDays    int32
	HasOpenDispute       bool
}

// Loads one work order with the fields WorkOrderDetail needs beyond the row
// itself: both parties' account ids (for the party guard), the request's product
// item, and the offer's readiness lead. Keyed on the work order id; the caller
// checks the account ids against the principal so a non-party sees a 404.
// has_open_dispute carries whether any unresolved dispute exists on the order, so
// the read layer feeds it to order.IsAutoConfirmDue: an open dispute halts the
// lazy auto-confirm exactly as the NOT EXISTS guard halts the ticker, so the two
// layers never disagree on a disputed order (FR-070).
func (q *Queries) GetWorkOrderForView(ctx context.Context, id pgtype.UUID) (GetWorkOrderForViewRow, error) {
	row := q.db.QueryRow(ctx, getWorkOrderForView, id)
	var i GetWorkOrderForViewRow
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.AutoConfirmBaseAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.BuyerAccount,
		&i.SubcontractorAccount,
		&i.ProductItemID,
		&i.ReadinessLeadDays,
		&i.HasOpenDispute,
	)
	return i, err
}

const insertAllocation = `-- name: InsertAllocation :one
INSERT INTO capacity_allocation (work_order_id, period_id, quantity, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, work_order_id, period_id, quantity, created_at, reversed_at
`

type InsertAllocationParams struct {
	WorkOrderID pgtype.UUID
	PeriodID    pgtype.UUID
	Quantity    int32
	CreatedAt   pgtype.Timestamptz
}

// One capacity allocation row per used period (FR-077).
func (q *Queries) InsertAllocation(ctx context.Context, arg InsertAllocationParams) (CapacityAllocation, error) {
	row := q.db.QueryRow(ctx, insertAllocation,
		arg.WorkOrderID,
		arg.PeriodID,
		arg.Quantity,
		arg.CreatedAt,
	)
	var i CapacityAllocation
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.PeriodID,
		&i.Quantity,
		&i.CreatedAt,
		&i.ReversedAt,
	)
	return i, err
}

const insertDispute = `-- name: InsertDispute :one
INSERT INTO dispute (
    work_order_id, reporter_id, report_body, created_at
) VALUES ($1, $2, $3, $4)
RETURNING id, work_order_id, reporter_id, report_body, status, admin_note, allocation_reversed, liable_party_id, handled_by, resolved_at, created_at, result
`

type InsertDisputeParams struct {
	WorkOrderID pgtype.UUID
	ReporterID  pgtype.UUID
	ReportBody  string
	CreatedAt   pgtype.Timestamptz
}

// Opens a dispute on a work order (FR-046). status takes its 'reported' default.
// The idx_one_open_dispute partial unique index (work_order_id WHERE status <>
// 'resolved') means at most one dispute may be open per order; a second report
// violates it and the caller turns the 23505 into a readable DISPUTE_ALREADY_OPEN
// 409 (FR-046). reporter_id is the reporting party's business profile id.
func (q *Queries) InsertDispute(ctx context.Context, arg InsertDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, insertDispute,
		arg.WorkOrderID,
		arg.ReporterID,
		arg.ReportBody,
		arg.CreatedAt,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.ReporterID,
		&i.ReportBody,
		&i.Status,
		&i.AdminNote,
		&i.AllocationReversed,
		&i.LiablePartyID,
		&i.HandledBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.Result,
	)
	return i, err
}

const insertOrderStatusHistory = `-- name: InsertOrderStatusHistory :exec
INSERT INTO work_order_status_history (
    work_order_id, old_status, new_status, changed_by, by_system, note, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOrderStatusHistoryParams struct {
	WorkOrderID pgtype.UUID
	OldStatus   NullWorkOrderStatus
	NewStatus   WorkOrderStatus
	ChangedBy   pgtype.UUID
	BySystem    bool
	Note        pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

// Records the opening status transition of a work order for its history trail.
func (q *Queries) InsertOrderStatusHistory(ctx context.Context, arg InsertOrderStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, insertOrderStatusHistory,
		arg.WorkOrderID,
		arg.OldStatus,
		arg.NewStatus,
		arg.ChangedBy,
		arg.BySystem,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const insertPaymentRecord = `-- name: InsertPaymentRecord :one
INSERT INTO payment_record (
    work_order_id, profile_id, direction, date, note, created_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, work_order_id, profile_id, direction, date, note, created_at
`

type InsertPaymentRecordParams struct {
	WorkOrderID pgtype.UUID
	ProfileID   pgtype.UUID
	Direction   PaymentDirection
	Date        pgtype.Date
	Note        pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

// Records one party's payment statement on a work order (FR-041). No money amount
// is stored: the platform neither holds nor verifies funds (FR-040, FR-042), so
// the row carries only the direction (sent/received), the date the party states,
// an optional free note, and the Clock-stamped created_at. The
// one_statement_per_party_per_direction unique constraint means a party can state
// each direction at most once; a repeat violates it and the caller turns the
// 23505 into a readable PAYMENT_STATEMENT_EXISTS 409.
func (q *Queries) InsertPaymentRecord(ctx context.Context, arg InsertPaymentRecordParams) (PaymentRecord, error) {
	row := q.db.QueryRow(ctx, insertPaymentRecord,
		arg.WorkOrderID,
		arg.ProfileID,
		arg.Direction,
		arg.Date,
		arg.Note,
		arg.CreatedAt,
	)
	var i PaymentRecord
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.ProfileID,
		&i.Direction,
		&i.Date,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorkOrder = `-- name: InsertWorkOrder :one
INSERT INTO work_order (
    candidate_id, offer_id, buyer_id, subcontractor_id,
    quantity, total_price, deadline, readiness_week_start, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at, confirm_warn_sent_at, late_notified_at, auto_confirm_base_at
`

type InsertWorkOrderParams struct {
	CandidateID        pgtype.UUID
	OfferID            pgtype.UUID
	BuyerID            pgtype.UUID
	SubcontractorID    pgtype.UUID
	Quantity           int32
	TotalPrice         int64
	Deadline           pgtype.Date
	ReadinessWeekStart pgtype.Date
	CreatedAt          pgtype.Timestamptz
}

// Inserts the work order at agreement formation. readiness_week_start is stored,
// not recomputed later (FR-084); status takes its 'accepted' default.
func (q *Queries) InsertWorkOrder(ctx context.Context, arg InsertWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, insertWorkOrder,
		arg.CandidateID,
		arg.OfferID,
		arg.BuyerID,
		arg.SubcontractorID,
		arg.Quantity,
		arg.TotalPrice,
		arg.Deadline,
		arg.ReadinessWeekStart,
		arg.CreatedAt,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.ConfirmWarnSentAt,
		&i.LateNotifiedAt,
		&i.AutoConfirmBaseAt,
	)
	return i, err
}

const listActiveAllocationsForReversal = `-- name: ListActiveAllocationsForReversal :many
SELECT a.id AS allocation_id, a.period_id, a.quantity, p.week_start
FROM capacity_allocation a
JOIN availability_period p ON p.id = a.period_id
WHERE a.work_order_id = $1 AND a.reversed_at IS NULL
ORDER BY p.week_start
FOR UPDATE OF a, p
`

type ListActiveAllocationsForReversalRow struct {
	AllocationID pgtype.UUID
	PeriodID     pgtype.UUID
	Quantity     int32
	WeekStart    pgtype.Date
}

// Locks the order's still-active allocation rows together with their periods,
// ordered ascending by week_start. The order mirrors the formation lock order of
// R-04 (LockPeriodsInRange), the deadlock preventer: two transactions touching
// the same periods always take them in the same order. Already reversed rows are
// left out, so a repeat reversal refunds nothing rather than double-crediting.
func (q *Queries) ListActiveAllocationsForReversal(ctx context.Context, workOrderID pgtype.UUID) ([]ListActiveAllocationsForReversalRow, error) {
	rows, err := q.db.Query(ctx, listActiveAllocationsForReversal, workOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAllocationsForReversalRow{}
	for rows.Next() {
		var i ListActiveAllocationsForReversalRow
		if err := rows.Scan(
			&i.AllocationID,
			&i.PeriodID,
			&i.Quantity,
			&i.WeekStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisputesForAdmin = `-- name: ListDisputesForAdmin :many
SELECT id, work_order_id, reporter_id, report_body, status, admin_note, allocation_reversed, liable_party_id, handled_by, resolved_at, created_at, result FROM dispute
WHERE (
        $1::text IS NULL
        OR status::text = $1::text
    )
  AND (
        $2::timestamptz IS NULL
        OR (created_at, id) < ($2::timestamptz, $3::uuid)
    )
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type ListDisputesForAdminParams struct {
	StatusFilter  pgtype.Text
	BeforeCreated pgtype.Timestamptz
	BeforeID      pgtype.UUID
	PageLimit     int32
}

// The admin dispute queue, newest first, keyset paginated on (created_at, id) so
// the order is stable across pages (FR-046). An optional status_filter narrows to
// one DisputeStatus (reported / in_mediation / resolved); a null filter returns
// every dispute regardless of status. A null before_created is the first page.
// The unresolved slice of this list rides idx_dispute_queue(created_at); a status
// filter of 'resolved' scans without that partial index, which is acceptable for
// an admin-only review list. Returns the full dispute row so the handler renders
// the contract Dispute shape (reporter_id -> reporter_profile_id, liable_party_id
// -> liable_profile_id) without a second read.
func (q *Queries) ListDisputesForAdmin(ctx context.Context, arg ListDisputesForAdminParams) ([]Dispute, error) {
	rows, err := q.db.Query(ctx, listDisputesForAdmin,
		arg.StatusFilter,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dispute{}
	for rows.Next() {
		var i Dispute
		if err := rows.Scan(
			&i.ID,
			&i.WorkOrderID,
			&i.ReporterID,
			&i.ReportBody,
			&i.Status,
			&i.AdminNote,
			&i.AllocationReversed,
			&i.LiablePartyID,
			&i.HandledBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLateWorkOrdersForAdmin = `-- name: ListLateWorkOrdersForAdmin :many
SELECT wo.id, wo.candidate_id, wo.offer_id, wo.buyer_id, wo.subcontractor_id, wo.quantity, wo.total_price, wo.deadline, wo.readiness_week_start, wo.status, wo.shipped_at, wo.confirmed_at, wo.auto_confirmed, wo.cancelled_by_id, wo.cancellation_reason, wo.cancelled_at, wo.created_at, wo.confirm_warn_sent_at, wo.late_notified_at, wo.auto_confirm_base_at,
    EXISTS (
        SELECT 1 FROM dispute d
        WHERE d.work_order_id = wo.id AND d.status <> 'resolved'
    ) AS has_open_dispute
FROM work_order wo
WHERE wo.status IN ('accepted', 'production', 'completed', 'shipped')
  AND wo.deadline < $1::date
  AND (
        $2::timestamptz IS NULL
        OR (wo.created_at, wo.id) < ($2::timestamptz, $3::uuid)
    )
ORDER BY wo.created_at DESC, wo.id DESC
LIMIT $4::int
`

type ListLateWorkOrdersForAdminParams struct {
	BeforeCutoff  pgtype.Date
	BeforeCreated pgtype.Timestamptz
	BeforeID      pgtype.UUID
	PageLimit     int32
}

type ListLateWorkOrdersForAdminRow struct {
	ID                 pgtype.UUID
	CandidateID        pgtype.UUID
	OfferID            pgtype.UUID
	BuyerID            pgtype.UUID
	SubcontractorID    pgtype.UUID
	Quantity           int32
	TotalPrice         int64
	Deadline           pgtype.Date
	ReadinessWeekStart pgtype.Date
	Status             WorkOrderStatus
	ShippedAt          pgtype.Timestamptz
	ConfirmedAt        pgtype.Timestamptz
	AutoConfirmed      bool
	CancelledByID      pgtype.UUID
	CancellationReason pgtype.Text
	CancelledAt        pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	ConfirmWarnSentAt  pgtype.Timestamptz
	LateNotifiedAt     pgtype.Timestamptz
	AutoConfirmBaseAt  pgtype.Timestamptz
	HasOpenDispute     bool
}

// The active orders whose delivery deadline has passed, newest first, keyset
// paginated on (created_at, id) for the admin monitoring list (FR-045). The
// status set is exactly idx_order_deadline_active's predicate, so the query rides
// that partial index instead of adding a new one: an order counts as late only
// while it is still open (accepted, production, completed, shipped); a confirmed
// or cancelled order is out even if its deadline has long passed, and an
// in-mediation order is excluded because a dispute already has admin attention.
// deadline < before_cutoff::date is the past-deadline test with before_cutoff =
// order.PastDeadlineCutoff(now), the start of now's WIB day, computed by the
// caller from the injected Clock so the boundary matches order.IsPastDeadline and
// no wall clock is read in SQL (Rule 5). has_open_dispute rides along so the admin
// render reuses listItemView with the same lazy auto-confirm as the party list.
func (q *Queries) ListLateWorkOrdersForAdmin(ctx context.Context, arg ListLateWorkOrdersForAdminParams) ([]ListLateWorkOrdersForAdminRow, error) {
	rows, err := q.db.Query(ctx, listLateWorkOrdersForAdmin,
		arg.BeforeCutoff,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLateWorkOrdersForAdminRow{}
	for rows.Next() {
		var i ListLateWorkOrdersForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.CandidateID,
			&i.OfferID,
			&i.BuyerID,
			&i.SubcontractorID,
			&i.Quantity,
			&i.TotalPrice,
			&i.Deadline,
			&i.ReadinessWeekStart,
			&i.Status,
			&i.ShippedAt,
			&i.ConfirmedAt,
			&i.AutoConfirmed,
			&i.CancelledByID,
			&i.CancellationReason,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.ConfirmWarnSentAt,
			&i.LateNotifiedAt,
			&i.AutoConfirmBaseAt,
			&i.HasOpenDispute,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLateWorkOrdersToNotify = `-- name: ListLateWorkOrdersToNotify :many
SELECT wo.id, buyer.account_id AS buyer_account, sub.account_id AS subcontractor_account
FROM work_order wo
JOIN business_profile buyer ON buyer.id = wo.buyer_id
JOIN business_profile sub   ON sub.id = wo.subcontractor_id
WHERE wo.status IN ('accepted', 'production', 'completed', 'shipped')
  AND wo.deadline < $1::date
  AND wo.late_notified_at IS NULL
ORDER BY wo.deadline
`

type ListLateWorkOrdersToNotifyRow struct {
	ID                   pgtype.UUID
	BuyerAccount         pgtype.UUID
	SubcontractorAccount pgtype.UUID
}

// The active orders past their deadline that have not yet had the late-delivery
// notice sent, for the in-process ticker to notify (FR-045). It mirrors
// ListLateWorkOrdersForAdmin's status set and deadline test (both share
// order.PastDeadlineCutoff), adding late_notified_at IS NULL so each late order is
// notified once, not on every tick. Returns each order's id and both parties'
// account ids, since FR-045 alerts both sides. Rides idx_order_deadline_active.
func (q *Queries) ListLateWorkOrdersToNotify(ctx context.Context, beforeCutoff pgtype.Date) ([]ListLateWorkOrdersToNotifyRow, error) {
	rows, err := q.db.Query(ctx, listLateWorkOrdersToNotify, beforeCutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLateWorkOrdersToNotifyRow{}
	for rows.Next() {
		var i ListLateWorkOrdersToNotifyRow
		if err := rows.Scan(&i.ID, &i.BuyerAccount, &i.SubcontractorAccount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOtherCandidatesToNotify = `-- name: ListOtherCandidatesToNotify :many
SELECT c.id AS candidate_id, sub.account_id AS subcontractor_account
FROM request_candidate c
JOIN business_profile sub ON sub.id = c.subcontractor_id
WHERE c.request_id = $1 AND c.id <> $2 AND c.status NOT IN ('rejected', 'expired')
`

type ListOtherCandidatesToNotifyParams struct {
	RequestID pgtype.UUID
	ID        pgtype.UUID
}

type ListOtherCandidatesToNotifyRow struct {
	CandidateID          pgtype.UUID
	SubcontractorAccount pgtype.UUID
}

// The other still-open candidates of the request, so their subcontractors learn
// the request was agreed elsewhere. Rejected and expired candidates are left out.
func (q *Queries) ListOtherCandidatesToNotify(ctx context.Context, arg ListOtherCandidatesToNotifyParams) ([]ListOtherCandidatesToNotifyRow, error) {
	rows, err := q.db.Query(ctx, listOtherCandidatesToNotify, arg.RequestID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOtherCandidatesToNotifyRow{}
	for rows.Next() {
		var i ListOtherCandidatesToNotifyRow
		if err := rows.Scan(&i.CandidateID, &i.SubcontractorAccount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentRecordsForWorkOrder = `-- name: ListPaymentRecordsForWorkOrder :many
SELECT id, work_order_id, profile_id, direction, date, note, created_at
FROM payment_record
WHERE work_order_id = $1
ORDER BY created_at, id
`

// Every payment statement on one work order for WorkOrderDetail (FR-041). Ordered
// by created_at so the two parties' statements read in the order they were made;
// both directions from both parties are visible, so a disagreement (one party
// states sent, the counterparty never states received) is apparent to the parties
// and to admin when a dispute is reported (FR-043).
func (q *Queries) ListPaymentRecordsForWorkOrder(ctx context.Context, workOrderID pgtype.UUID) ([]PaymentRecord, error) {
	rows, err := q.db.Query(ctx, listPaymentRecordsForWorkOrder, workOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentRecord{}
	for rows.Next() {
		var i PaymentRecord
		if err := rows.Scan(
			&i.ID,
			&i.WorkOrderID,
			&i.ProfileID,
			&i.Direction,
			&i.Date,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippedApproachingAutoConfirm = `-- name: ListShippedApproachingAutoConfirm :many
SELECT wo.id, buyer.account_id AS buyer_account,
    COALESCE(wo.auto_confirm_base_at, wo.shipped_at)::timestamptz AS auto_confirm_base
FROM work_order wo
JOIN business_profile buyer ON buyer.id = wo.buyer_id
WHERE wo.status = 'shipped'
  AND wo.confirm_warn_sent_at IS NULL
  AND COALESCE(wo.auto_confirm_base_at, wo.shipped_at) > $1::timestamptz
  AND COALESCE(wo.auto_confirm_base_at, wo.shipped_at) <= $2::timestamptz
  AND NOT EXISTS (
        SELECT 1 FROM dispute d
        WHERE d.work_order_id = wo.id AND d.status <> 'resolved'
  )
ORDER BY COALESCE(wo.auto_confirm_base_at, wo.shipped_at)
`

type ListShippedApproachingAutoConfirmParams struct {
	DueBefore  pgtype.Timestamptz
	WarnBefore pgtype.Timestamptz
}

type ListShippedApproachingAutoConfirmRow struct {
	ID              pgtype.UUID
	BuyerAccount    pgtype.UUID
	AutoConfirmBase pgtype.Timestamptz
}

// The shipped orders inside the FR-069 warning lead that have not yet been warned:
// the effective base COALESCE(auto_confirm_base_at, shipped_at) is within
// (warn_after, due_after] so the auto-confirm instant is between AutoConfirmWarnLead
// and now, and confirm_warn_sent_at IS NULL dedups so the ticker warns each order
// once, not on every tick. The caller passes warn_after = now - AutoConfirmWindow +
// AutoConfirmWarnLead and due_after = now - AutoConfirmWindow, both from the Clock,
// so the window matches order.IsAutoConfirmApproaching over the same effective base.
// Normally the base is shipped_at; on an order whose dispute closed "continued"
// after shipment it is the mediation-close instant, so the warning tracks the
// restarted clock (FR-070). An order with an open dispute is excluded by the NOT
// EXISTS guard, so a disputed order is neither warned about nor auto-closed
// (FR-070). Rides idx_order_auto_confirm on the same COALESCE expression. Returns
// the id, the buyer account (the only party FR-069 warns), and the effective base
// so the caller can name the auto-confirm date in the notice.
func (q *Queries) ListShippedApproachingAutoConfirm(ctx context.Context, arg ListShippedApproachingAutoConfirmParams) ([]ListShippedApproachingAutoConfirmRow, error) {
	rows, err := q.db.Query(ctx, listShippedApproachingAutoConfirm, arg.DueBefore, arg.WarnBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShippedApproachingAutoConfirmRow{}
	for rows.Next() {
		var i ListShippedApproachingAutoConfirmRow
		if err := rows.Scan(&i.ID, &i.BuyerAccount, &i.AutoConfirmBase); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippedDueForAutoConfirm = `-- name: ListShippedDueForAutoConfirm :many
SELECT wo.id, buyer.account_id AS buyer_account, sub.account_id AS subcontractor_account
FROM work_order wo
JOIN business_profile buyer ON buyer.id = wo.buyer_id
JOIN business_profile sub   ON sub.id = wo.subcontractor_id
WHERE wo.status = 'shipped'
  AND COALESCE(wo.auto_confirm_base_at, wo.shipped_at) <= $1::timestamptz
  AND NOT EXISTS (
        SELECT 1 FROM dispute d
        WHERE d.work_order_id = wo.id AND d.status <> 'resolved'
  )
ORDER BY COALESCE(wo.auto_confirm_base_at, wo.shipped_at)
`

type ListShippedDueForAutoConfirmRow struct {
	ID                   pgtype.UUID
	BuyerAccount         pgtype.UUID
	SubcontractorAccount pgtype.UUID
}

// The shipped orders whose 7-day auto-confirm instant has arrived (FR-068),
// for the in-process ticker to close. The due test is on the effective base
// COALESCE(auto_confirm_base_at, shipped_at) <= $1 with $1 = now -
// AutoConfirmWindow computed by the caller from the injected Clock, so the
// boundary matches order.AutoConfirmBase + order.IsAutoConfirmDue exactly and no
// wall clock is read in SQL. Normally the base is shipped_at; on an order whose
// dispute closed "continued" after shipment it is the mediation-close instant, so
// the clock restarts from mediation, not from the original shipment (FR-070,
// data-model.md). Rides idx_order_auto_confirm on the same COALESCE expression
// WHERE status='shipped'. An order with an open dispute is excluded by the NOT
// EXISTS guard, so reporting a dispute stops the auto-confirm count without moving
// the order off 'shipped' (FR-070): the dispute row, not the work-order status, is
// what halts the clock, and admin moves the order to in_mediation separately
// (T071). Returns each order's id and both parties' account ids for the closure
// notice.
func (q *Queries) ListShippedDueForAutoConfirm(ctx context.Context, dueBefore pgtype.Timestamptz) ([]ListShippedDueForAutoConfirmRow, error) {
	rows, err := q.db.Query(ctx, listShippedDueForAutoConfirm, dueBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShippedDueForAutoConfirmRow{}
	for rows.Next() {
		var i ListShippedDueForAutoConfirmRow
		if err := rows.Scan(&i.ID, &i.BuyerAccount, &i.SubcontractorAccount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkOrderAllocations = `-- name: ListWorkOrderAllocations :many
SELECT p.week_start, p.total_capacity, p.used_capacity, p.marked_full
FROM capacity_allocation a
JOIN availability_period p ON p.id = a.period_id
WHERE a.work_order_id = $1 AND a.reversed_at IS NULL
ORDER BY p.week_start
`

type ListWorkOrderAllocationsRow struct {
	WeekStart     pgtype.Date
	TotalCapacity int32
	UsedCapacity  int32
	MarkedFull    bool
}

// The still-active allocation periods of one work order with the period figures
// WorkOrderDetail renders, ordered ascending by week_start. Reversed rows are
// left out so a cancelled order shows no live allocation.
func (q *Queries) ListWorkOrderAllocations(ctx context.Context, workOrderID pgtype.UUID) ([]ListWorkOrderAllocationsRow, error) {
	rows, err := q.db.Query(ctx, listWorkOrderAllocations, workOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkOrderAllocationsRow{}
	for rows.Next() {
		var i ListWorkOrderAllocationsRow
		if err := rows.Scan(
			&i.WeekStart,
			&i.TotalCapacity,
			&i.UsedCapacity,
			&i.MarkedFull,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkOrderStatusHistory = `-- name: ListWorkOrderStatusHistory :many
SELECT new_status, created_at, note
FROM work_order_status_history
WHERE work_order_id = $1
ORDER BY created_at, id
`

type ListWorkOrderStatusHistoryRow struct {
	NewStatus WorkOrderStatus
	CreatedAt pgtype.Timestamptz
	Note      pgtype.Text
}

// The status trail of one work order, oldest first, for WorkOrderDetail. Rides
// idx_status_history_order (work_order_id, created_at) so it stays ordered
// without a sort.
func (q *Queries) ListWorkOrderStatusHistory(ctx context.Context, workOrderID pgtype.UUID) ([]ListWorkOrderStatusHistoryRow, error) {
	rows, err := q.db.Query(ctx, listWorkOrderStatusHistory, workOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkOrderStatusHistoryRow{}
	for rows.Next() {
		var i ListWorkOrderStatusHistoryRow
		if err := rows.Scan(&i.NewStatus, &i.CreatedAt, &i.Note); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkOrdersForParty = `-- name: ListWorkOrdersForParty :many
SELECT wo.id, wo.candidate_id, wo.offer_id, wo.buyer_id, wo.subcontractor_id, wo.quantity, wo.total_price, wo.deadline, wo.readiness_week_start, wo.status, wo.shipped_at, wo.confirmed_at, wo.auto_confirmed, wo.cancelled_by_id, wo.cancellation_reason, wo.cancelled_at, wo.created_at, wo.confirm_warn_sent_at, wo.late_notified_at, wo.auto_confirm_base_at,
    EXISTS (
        SELECT 1 FROM dispute d
        WHERE d.work_order_id = wo.id AND d.status <> 'resolved'
    ) AS has_open_dispute
FROM work_order wo
WHERE (
        ($1::text = 'as_buyer' AND wo.buyer_id = $2::uuid)
        OR ($1::text = 'as_subcontractor' AND wo.subcontractor_id = $2::uuid)
        OR ($1::text NOT IN ('as_buyer', 'as_subcontractor')
            AND (wo.buyer_id = $2::uuid OR wo.subcontractor_id = $2::uuid))
    )
  AND (
        cardinality($3::text[]) = 0
        OR wo.status::text = ANY($3::text[])
    )
  AND (
        $4::timestamptz IS NULL
        OR (wo.created_at, wo.id) < ($4::timestamptz, $5::uuid)
    )
ORDER BY wo.created_at DESC, wo.id DESC
LIMIT $6::int
`

type ListWorkOrdersForPartyParams struct {
	RoleFilter    string
	ProfileID     pgtype.UUID
	StatusFilter  []string
	BeforeCreated pgtype.Timestamptz
	BeforeID      pgtype.UUID
	PageLimit     int32
}

type ListWorkOrdersForPartyRow struct {
	ID                 pgtype.UUID
	CandidateID        pgtype.UUID
	OfferID            pgtype.UUID
	BuyerID            pgtype.UUID
	SubcontractorID    pgtype.UUID
	Quantity           int32
	TotalPrice         int64
	Deadline           pgtype.Date
	ReadinessWeekStart pgtype.Date
	Status             WorkOrderStatus
	ShippedAt          pgtype.Timestamptz
	ConfirmedAt        pgtype.Timestamptz
	AutoConfirmed      bool
	CancelledByID      pgtype.UUID
	CancellationReason pgtype.Text
	CancelledAt        pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	ConfirmWarnSentAt  pgtype.Timestamptz
	LateNotifiedAt     pgtype.Timestamptz
	AutoConfirmBaseAt  pgtype.Timestamptz
	HasOpenDispute     bool
}

// One party's work orders newest first, keyset paginated on (created_at, id) so
// the order is stable across pages (FR-038). role_filter selects the side:
// 'as_buyer' matches the buyer profile, 'as_subcontractor' the subcontractor
// profile, any other value matches either. An empty status_filter array means no
// status restriction; otherwise only the listed statuses pass. The filter is a
// text[] cast against wo.status::text, not a work_order_status[]: pgx cannot encode
// a slice of the named enum type without the enum OID registered on the pool, so an
// enum-array parameter fails to encode on every request (empty slice included). The
// text cast sidesteps that with no per-connection type registration (Principle IV).
// A null before_created is the first page. has_open_dispute rides along so
// listItemView feeds it to order.IsAutoConfirmDue, keeping the list's lazy
// auto-confirm in step with the detail view and the ticker on a disputed order
// (FR-070).
func (q *Queries) ListWorkOrdersForParty(ctx context.Context, arg ListWorkOrdersForPartyParams) ([]ListWorkOrdersForPartyRow, error) {
	rows, err := q.db.Query(ctx, listWorkOrdersForParty,
		arg.RoleFilter,
		arg.ProfileID,
		arg.StatusFilter,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkOrdersForPartyRow{}
	for rows.Next() {
		var i ListWorkOrdersForPartyRow
		if err := rows.Scan(
			&i.ID,
			&i.CandidateID,
			&i.OfferID,
			&i.BuyerID,
			&i.SubcontractorID,
			&i.Quantity,
			&i.TotalPrice,
			&i.Deadline,
			&i.ReadinessWeekStart,
			&i.Status,
			&i.ShippedAt,
			&i.ConfirmedAt,
			&i.AutoConfirmed,
			&i.CancelledByID,
			&i.CancellationReason,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.ConfirmWarnSentAt,
			&i.LateNotifiedAt,
			&i.AutoConfirmBaseAt,
			&i.HasOpenDispute,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockListingByID = `-- name: LockListingByID :one
SELECT id, profile_id, weekly_capacity, readiness_lead_days, published, calendar_updated_at, horizon_until, created_at, updated_at FROM capacity_listing WHERE id = $1 FOR UPDATE
`

// Takes a row lock on a listing by its own id, so the accept path can extend the
// calendar horizon (FR-088) under the same lock the listing owner's edits take.
func (q *Queries) LockListingByID(ctx context.Context, id pgtype.UUID) (CapacityListing, error) {
	row := q.db.QueryRow(ctx, lockListingByID, id)
	var i CapacityListing
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WeeklyCapacity,
		&i.ReadinessLeadDays,
		&i.Published,
		&i.CalendarUpdatedAt,
		&i.HorizonUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPeriodsInRange = `-- name: LockPeriodsInRange :many
SELECT id, listing_id, week_start, total_capacity, used_capacity, marked_full, created_at, updated_at FROM availability_period
WHERE listing_id = $1 AND week_start BETWEEN $2 AND $3
ORDER BY week_start
FOR UPDATE
`

type LockPeriodsInRangeParams struct {
	ListingID   pgtype.UUID
	WeekStart   pgtype.Date
	WeekStart_2 pgtype.Date
}

// Locks every candidate period in the readiness..deadline range at once, ordered
// ascending by week_start. The order is the deadlock preventer of R-04, not tidy
// housekeeping: two agreements touching the same periods always lock them in the
// same order, so the second waits and then sees the reduced capacity.
func (q *Queries) LockPeriodsInRange(ctx context.Context, arg LockPeriodsInRangeParams) ([]AvailabilityPeriod, error) {
	rows, err := q.db.Query(ctx, lockPeriodsInRange, arg.ListingID, arg.WeekStart, arg.WeekStart_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilityPeriod{}
	for rows.Next() {
		var i AvailabilityPeriod
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.WeekStart,
			&i.TotalCapacity,
			&i.UsedCapacity,
			&i.MarkedFull,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkOrderForReversal = `-- name: LockWorkOrderForReversal :one
SELECT id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at, confirm_warn_sent_at, late_notified_at, auto_confirm_base_at FROM work_order WHERE id = $1 FOR UPDATE
`

// Takes a row lock on the work order whose allocation is being reversed, so the
// reversal runs under a lock in the same spirit as formation locking the listing.
func (q *Queries) LockWorkOrderForReversal(ctx context.Context, id pgtype.UUID) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, lockWorkOrderForReversal, id)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.ConfirmWarnSentAt,
		&i.LateNotifiedAt,
		&i.AutoConfirmBaseAt,
	)
	return i, err
}

const lockWorkOrderForStatusChange = `-- name: LockWorkOrderForStatusChange :one
SELECT id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at, confirm_warn_sent_at, late_notified_at, auto_confirm_base_at FROM work_order WHERE id = $1 FOR UPDATE
`

// Row-locks a work order before a status transition so a concurrent status
// change or cancellation on the same order serializes, matching the reversal
// lock spirit (R-04).
func (q *Queries) LockWorkOrderForStatusChange(ctx context.Context, id pgtype.UUID) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, lockWorkOrderForStatusChange, id)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.ConfirmWarnSentAt,
		&i.LateNotifiedAt,
		&i.AutoConfirmBaseAt,
	)
	return i, err
}

const lowerUsedCapacity = `-- name: LowerUsedCapacity :one
UPDATE availability_period
SET used_capacity = used_capacity - $2, updated_at = $3
WHERE id = $1
RETURNING id, listing_id, week_start, total_capacity, used_capacity, marked_full, created_at, updated_at
`

type LowerUsedCapacityParams struct {
	ID           pgtype.UUID
	UsedCapacity int32
	UpdatedAt    pgtype.Timestamptz
}

// Returns a period's used_capacity to its pre-order value by subtracting the
// reversed amount. The inverse of RaiseUsedCapacity; the quantity comes from the
// allocation row being reversed, so used_capacity never drops below zero.
func (q *Queries) LowerUsedCapacity(ctx context.Context, arg LowerUsedCapacityParams) (AvailabilityPeriod, error) {
	row := q.db.QueryRow(ctx, lowerUsedCapacity, arg.ID, arg.UsedCapacity, arg.UpdatedAt)
	var i AvailabilityPeriod
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.WeekStart,
		&i.TotalCapacity,
		&i.UsedCapacity,
		&i.MarkedFull,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAllocationReversed = `-- name: MarkAllocationReversed :exec
UPDATE capacity_allocation
SET reversed_at = $2
WHERE id = $1 AND reversed_at IS NULL
`

type MarkAllocationReversedParams struct {
	ID         pgtype.UUID
	ReversedAt pgtype.Timestamptz
}

// Marks one allocation row reversed without deleting it (FR-020), keeping the
// audit trail. The reversed_at guard makes the write idempotent under a repeat.
func (q *Queries) MarkAllocationReversed(ctx context.Context, arg MarkAllocationReversedParams) error {
	_, err := q.db.Exec(ctx, markAllocationReversed, arg.ID, arg.ReversedAt)
	return err
}

const markConfirmWarnSent = `-- name: MarkConfirmWarnSent :exec
UPDATE work_order
SET confirm_warn_sent_at = $2
WHERE id = $1 AND confirm_warn_sent_at IS NULL
`

type MarkConfirmWarnSentParams struct {
	ID                pgtype.UUID
	ConfirmWarnSentAt pgtype.Timestamptz
}

// Stamps confirm_warn_sent_at so the FR-069 approaching notice is sent to the
// buyer once. The IS NULL guard keeps it idempotent if two overlapping ticker
// instances both scanned before either stamped (the advisory lock makes that
// rare, but the guard removes the race entirely).
func (q *Queries) MarkConfirmWarnSent(ctx context.Context, arg MarkConfirmWarnSentParams) error {
	_, err := q.db.Exec(ctx, markConfirmWarnSent, arg.ID, arg.ConfirmWarnSentAt)
	return err
}

const markDisputeInMediation = `-- name: MarkDisputeInMediation :exec
UPDATE dispute
SET status = 'in_mediation'
WHERE id = $1 AND status = 'reported'
`

// Marks a reported dispute as in_mediation when the admin takes up the case
// (FR-046). Runs in the same transaction as MoveWorkOrderToMediation so an order
// in mediation always has its dispute in mediation. The status = 'reported' guard
// keeps this from re-opening a dispute the admin already resolved; a resolved
// dispute is rejected earlier by the handler's GetDisputeForAdmin status check, so
// in practice this only ever advances 'reported' -> 'in_mediation'.
func (q *Queries) MarkDisputeInMediation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDisputeInMediation, id)
	return err
}

const markLateNotified = `-- name: MarkLateNotified :exec
UPDATE work_order
SET late_notified_at = $2
WHERE id = $1 AND late_notified_at IS NULL
`

type MarkLateNotifiedParams struct {
	ID             pgtype.UUID
	LateNotifiedAt pgtype.Timestamptz
}

// Stamps late_notified_at so the FR-045 late-delivery notice is sent once per
// order. The IS NULL guard keeps it idempotent if two overlapping ticker
// instances both scanned before either stamped (the advisory lock makes that
// rare, but the guard removes the race entirely). The stamp is never cleared,
// even when mediation later closes, so a resolved late order is not re-notified.
func (q *Queries) MarkLateNotified(ctx context.Context, arg MarkLateNotifiedParams) error {
	_, err := q.db.Exec(ctx, markLateNotified, arg.ID, arg.LateNotifiedAt)
	return err
}

const moveWorkOrderToMediation = `-- name: MoveWorkOrderToMediation :one
UPDATE work_order
SET status = 'in_mediation'
WHERE id = $1 AND status IN ('accepted', 'production', 'completed', 'shipped')
RETURNING id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at, confirm_warn_sent_at, late_notified_at, auto_confirm_base_at
`

// Moves a shipped or otherwise-active order into 'in_mediation' when a dispute is
// reported (FR-070). The status = 'shipped' scan of ListShippedDueForAutoConfirm
// excludes 'in_mediation', so opening a dispute before the 7-day deadline stops
// the auto-confirm count. confirm_warn_sent_at is deliberately left untouched: a
// buyer already warned stays warned even if the dispute later closes without
// cancelling (data-model.md). The status guard rejects moving a terminal order
// (confirmed/cancelled), so a returned row means this call did the move.
func (q *Queries) MoveWorkOrderToMediation(ctx context.Context, id pgtype.UUID) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, moveWorkOrderToMediation, id)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.ConfirmWarnSentAt,
		&i.LateNotifiedAt,
		&i.AutoConfirmBaseAt,
	)
	return i, err
}

const partyConfirmWorkOrder = `-- name: PartyConfirmWorkOrder :one
UPDATE work_order
SET status = 'confirmed', auto_confirmed = false, confirmed_at = $2
WHERE work_order.id = $1 AND work_order.status = 'shipped'
  AND NOT EXISTS (
        SELECT 1 FROM dispute d
        WHERE d.work_order_id = work_order.id AND d.status <> 'resolved'
  )
RETURNING id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at, confirm_warn_sent_at, late_notified_at, auto_confirm_base_at
`

type PartyConfirmWorkOrderParams struct {
	ID          pgtype.UUID
	ConfirmedAt pgtype.Timestamptz
}

// Closes one shipped order as buyer-confirmed (FR-047, FR-068): status to
// 'confirmed', auto_confirmed false (this is the buyer's manual acceptance, not
// the system's 7-day closure, so the two are distinguishable in the trail), and
// confirmed_at stamped from the caller's Clock instant. The status = 'shipped'
// guard makes the write a no-op if the order left 'shipped' since the caller read
// it (e.g. the ticker already auto-confirmed, or a dispute moved it to mediation),
// so a returned row means this call did the closing. The NOT EXISTS open-dispute
// guard mirrors AutoConfirmWorkOrder: an order with an unresolved dispute stays
// open even while its status is still 'shipped' (FR-070). confirmed_at >= shipped_at
// holds by the shipped_before_confirmed CHECK since the order had shipped.
func (q *Queries) PartyConfirmWorkOrder(ctx context.Context, arg PartyConfirmWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, partyConfirmWorkOrder, arg.ID, arg.ConfirmedAt)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.ConfirmWarnSentAt,
		&i.LateNotifiedAt,
		&i.AutoConfirmBaseAt,
	)
	return i, err
}

const raiseUsedCapacity = `-- name: RaiseUsedCapacity :one
UPDATE availability_period
SET used_capacity = used_capacity + $2, updated_at = $3
WHERE id = $1
RETURNING id, listing_id, week_start, total_capacity, used_capacity, marked_full, created_at, updated_at
`

type RaiseUsedCapacityParams struct {
	ID           pgtype.UUID
	UsedCapacity int32
	UpdatedAt    pgtype.Timestamptz
}

// Raises a period's used_capacity by the allocated amount. The
// used_capacity_within_total CHECK is the FR-079/SC-018 storage-level safety net:
// if the fill logic ever over-allocates, this fails hard instead of corrupting.
func (q *Queries) RaiseUsedCapacity(ctx context.Context, arg RaiseUsedCapacityParams) (AvailabilityPeriod, error) {
	row := q.db.QueryRow(ctx, raiseUsedCapacity, arg.ID, arg.UsedCapacity, arg.UpdatedAt)
	var i AvailabilityPeriod
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.WeekStart,
		&i.TotalCapacity,
		&i.UsedCapacity,
		&i.MarkedFull,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveDispute = `-- name: ResolveDispute :one
UPDATE dispute
SET status = 'resolved',
    result = $2,
    allocation_reversed = $3,
    liable_party_id = $4,
    admin_note = $5,
    handled_by = $6,
    resolved_at = $7
WHERE id = $1 AND status <> 'resolved'
RETURNING id, work_order_id, reporter_id, report_body, status, admin_note, allocation_reversed, liable_party_id, handled_by, resolved_at, created_at, result
`

type ResolveDisputeParams struct {
	ID                 pgtype.UUID
	Result             NullDisputeResult
	AllocationReversed pgtype.Bool
	LiablePartyID      pgtype.UUID
	AdminNote          pgtype.Text
	HandledBy          pgtype.UUID
	ResolvedAt         pgtype.Timestamptz
}

// Records the admin's mediation decision and closes the dispute (FR-067, FR-072).
// status moves to 'resolved'; result is the explicit outcome (cancelled /
// continued / confirmed) the resolution_complete CHECK now requires; admin_note
// carries the mandated note; allocation_reversed and liable_party_id record
// whether capacity was returned and which party bears the cancellation in the
// completion rate (FR-072); handled_by is the admin account and resolved_at the
// Clock instant. The status <> 'resolved' guard makes a repeat resolve a no-op so
// two admins cannot close the same dispute twice. The work-order side effects
// (cancel + reversal, restore, or force-confirm) run in the same transaction.
func (q *Queries) ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, resolveDispute,
		arg.ID,
		arg.Result,
		arg.AllocationReversed,
		arg.LiablePartyID,
		arg.AdminNote,
		arg.HandledBy,
		arg.ResolvedAt,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.ReporterID,
		&i.ReportBody,
		&i.Status,
		&i.AdminNote,
		&i.AllocationReversed,
		&i.LiablePartyID,
		&i.HandledBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.Result,
	)
	return i, err
}

const restartAutoConfirmClock = `-- name: RestartAutoConfirmClock :exec
UPDATE work_order
SET auto_confirm_base_at = $2, confirm_warn_sent_at = NULL
WHERE id = $1
`

type RestartAutoConfirmClockParams struct {
	ID                pgtype.UUID
	AutoConfirmBaseAt pgtype.Timestamptz
}

// Restarts the 7-day auto-confirm clock from the mediation-close instant on an
// order restored to 'shipped' by a 'continued' resolution (FR-068, data-model.md).
// auto_confirm_base_at becomes the mediation-close time, so AutoConfirmBase reads
// it instead of shipped_at and the window counts from mediation, not the original
// shipment; shipped_at is left as the historical shipment fact. confirm_warn_sent_at
// is reset to NULL so the buyer is warned afresh before the new deadline. Called
// only on the continued+shipped branch, where the restored status is 'shipped' so
// the auto_confirm_base_after_shipped CHECK (base >= shipped_at) holds.
func (q *Queries) RestartAutoConfirmClock(ctx context.Context, arg RestartAutoConfirmClockParams) error {
	_, err := q.db.Exec(ctx, restartAutoConfirmClock, arg.ID, arg.AutoConfirmBaseAt)
	return err
}

const restoreWorkOrderStatus = `-- name: RestoreWorkOrderStatus :one
UPDATE work_order
SET status = $2
WHERE id = $1 AND status = 'in_mediation'
RETURNING id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at, confirm_warn_sent_at, late_notified_at, auto_confirm_base_at
`

type RestoreWorkOrderStatusParams struct {
	ID     pgtype.UUID
	Status WorkOrderStatus
}

// Returns a mediated order to a prior status when a dispute closes 'continued'
// (FR-067): the order rejoins its production chain at the status it left. The
// status = 'in_mediation' guard means only an order actually in mediation is
// restored, so a returned row confirms this call did the move. auto_confirm_base_at
// and confirm_warn_sent_at are left untouched here; RestartAutoConfirmClock handles
// them separately, and only when the restored status is 'shipped'.
func (q *Queries) RestoreWorkOrderStatus(ctx context.Context, arg RestoreWorkOrderStatusParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, restoreWorkOrderStatus, arg.ID, arg.Status)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.ConfirmWarnSentAt,
		&i.LateNotifiedAt,
		&i.AutoConfirmBaseAt,
	)
	return i, err
}

const setCandidateAgreed = `-- name: SetCandidateAgreed :exec
UPDATE request_candidate
SET status = 'agreed', updated_at = $2
WHERE id = $1
`

type SetCandidateAgreedParams struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

// Marks the winning candidate agreed. The partial unique index
// idx_one_agreement_per_request enforces at most one agreement per request, so a
// concurrent second agreement violates it and the transaction fails (FR-036).
func (q *Queries) SetCandidateAgreed(ctx context.Context, arg SetCandidateAgreedParams) error {
	_, err := q.db.Exec(ctx, setCandidateAgreed, arg.ID, arg.UpdatedAt)
	return err
}

const updateWorkOrderStatus = `-- name: UpdateWorkOrderStatus :one
UPDATE work_order
SET status = $2,
    shipped_at = CASE WHEN $2 = 'shipped'::work_order_status THEN $3 ELSE shipped_at END
WHERE id = $1
RETURNING id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at, confirm_warn_sent_at, late_notified_at, auto_confirm_base_at
`

type UpdateWorkOrderStatusParams struct {
	ID        pgtype.UUID
	Status    WorkOrderStatus
	ShippedAt pgtype.Timestamptz
}

// Advances a work order to its next forward status. shipped_at is stamped only
// on the move into 'shipped' and left untouched otherwise, so it records the
// moment shipment was declared (the auto-confirm clock start, FR-068).
func (q *Queries) UpdateWorkOrderStatus(ctx context.Context, arg UpdateWorkOrderStatusParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, updateWorkOrderStatus, arg.ID, arg.Status, arg.ShippedAt)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.ConfirmWarnSentAt,
		&i.LateNotifiedAt,
		&i.AutoConfirmBaseAt,
	)
	return i, err
}
