// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeOtherCandidates = `-- name: CloseOtherCandidates :exec
UPDATE request_candidate
SET status = 'not_continued', updated_at = $3
WHERE request_id = $1 AND id <> $2 AND status NOT IN ('rejected', 'expired', 'agreed')
`

type CloseOtherCandidatesParams struct {
	RequestID pgtype.UUID
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

// Closes the request's other candidates once one is agreed (FR-034): they move to
// not_continued, leaving already rejected, expired, or agreed rows untouched.
func (q *Queries) CloseOtherCandidates(ctx context.Context, arg CloseOtherCandidatesParams) error {
	_, err := q.db.Exec(ctx, closeOtherCandidates, arg.RequestID, arg.ID, arg.UpdatedAt)
	return err
}

const estimateCapacityInRange = `-- name: EstimateCapacityInRange :one
WITH param AS (
    SELECT
        $1::uuid    AS listing_id,
        $2::date AS readiness_week,
        $3::date  AS deadline_week
)
SELECT
    coalesce(sum(pk.total_capacity - pk.used_capacity), 0)::bigint AS recorded_remaining,
    (greatest(0, (p.deadline_week - greatest(p.readiness_week, l.horizon_until + 7)) / 7 + 1) * l.weekly_capacity)::bigint AS uncreated_remaining
FROM capacity_listing l
CROSS JOIN param p
LEFT JOIN availability_period pk
       ON pk.listing_id = l.id
      AND NOT pk.marked_full
      AND pk.week_start BETWEEN p.readiness_week AND p.deadline_week
WHERE l.id = p.listing_id
GROUP BY l.id, l.weekly_capacity, l.horizon_until, p.readiness_week, p.deadline_week
`

type EstimateCapacityInRangeParams struct {
	ListingID     pgtype.UUID
	ReadinessWeek pgtype.Date
	DeadlineWeek  pgtype.Date
}

type EstimateCapacityInRangeRow struct {
	RecordedRemaining  int64
	UncreatedRemaining int64
}

// Optimistic remaining capacity across the readiness..deadline range, read BEFORE
// the accept path takes any lock. It mirrors search's formula (search.sql,
// FR-080/FR-088): recorded remaining over not-full periods plus an optimistic
// estimate for weeks past horizon_until counted at weekly_capacity. A shortfall
// here means the offer never had enough capacity, so accept fails fast with
// INSUFFICIENT_CAPACITY without locking. If this passes but the post-lock read is
// short, the capacity was definitively taken between the two reads
// (CAPACITY_ALREADY_TAKEN). Deadline is rounded to Monday in Go before calling.
func (q *Queries) EstimateCapacityInRange(ctx context.Context, arg EstimateCapacityInRangeParams) (EstimateCapacityInRangeRow, error) {
	row := q.db.QueryRow(ctx, estimateCapacityInRange, arg.ListingID, arg.ReadinessWeek, arg.DeadlineWeek)
	var i EstimateCapacityInRangeRow
	err := row.Scan(&i.RecordedRemaining, &i.UncreatedRemaining)
	return i, err
}

const getOfferForAccept = `-- name: GetOfferForAccept :one
SELECT
    o.id                        AS offer_id,
    o.candidate_id,
    o.total_price,
    o.readiness_lead_days,
    o.proposed_by,
    o.sequence,
    (SELECT max(sequence) FROM offer WHERE candidate_id = o.candidate_id)::int AS latest_sequence,
    c.status                    AS candidate_status,
    c.subcontractor_id,
    r.id                        AS request_id,
    r.buyer_id,
    r.product_item_id,
    r.quantity,
    r.deadline,
    r.reply_due_at,
    buyer.account_id            AS buyer_account,
    sub.account_id              AS subcontractor_account,
    l.id                        AS listing_id,
    l.weekly_capacity,
    l.horizon_until,
    EXISTS (
        SELECT 1 FROM request_candidate rc
        WHERE rc.request_id = r.id AND rc.status = 'agreed'
    ) AS request_has_agreement
FROM offer o
JOIN request_candidate c    ON c.id = o.candidate_id
JOIN quota_request r        ON r.id = c.request_id
JOIN capacity_listing l     ON l.id = c.listing_id
JOIN business_profile buyer ON buyer.id = r.buyer_id
JOIN business_profile sub   ON sub.id = c.subcontractor_id
WHERE o.id = $1
`

type GetOfferForAcceptRow struct {
	OfferID              pgtype.UUID
	CandidateID          pgtype.UUID
	TotalPrice           int64
	ReadinessLeadDays    int32
	ProposedBy           OfferParty
	Sequence             int32
	LatestSequence       int32
	CandidateStatus      CandidateStatus
	SubcontractorID      pgtype.UUID
	RequestID            pgtype.UUID
	BuyerID              pgtype.UUID
	ProductItemID        pgtype.UUID
	Quantity             int32
	Deadline             pgtype.Date
	ReplyDueAt           pgtype.Timestamptz
	BuyerAccount         pgtype.UUID
	SubcontractorAccount pgtype.UUID
	ListingID            pgtype.UUID
	WeeklyCapacity       int32
	HorizonUntil         pgtype.Date
	RequestHasAgreement  bool
}

// Loads everything the accept path needs about one offer: the offer terms, the
// candidate and its owning listing, the request and both parties, the listing
// capacity fields, whether the offer is the standing (latest) one, and whether
// any candidate of the request already reached an agreement. Keyed on the offer
// id the buyer accepts.
func (q *Queries) GetOfferForAccept(ctx context.Context, id pgtype.UUID) (GetOfferForAcceptRow, error) {
	row := q.db.QueryRow(ctx, getOfferForAccept, id)
	var i GetOfferForAcceptRow
	err := row.Scan(
		&i.OfferID,
		&i.CandidateID,
		&i.TotalPrice,
		&i.ReadinessLeadDays,
		&i.ProposedBy,
		&i.Sequence,
		&i.LatestSequence,
		&i.CandidateStatus,
		&i.SubcontractorID,
		&i.RequestID,
		&i.BuyerID,
		&i.ProductItemID,
		&i.Quantity,
		&i.Deadline,
		&i.ReplyDueAt,
		&i.BuyerAccount,
		&i.SubcontractorAccount,
		&i.ListingID,
		&i.WeeklyCapacity,
		&i.HorizonUntil,
		&i.RequestHasAgreement,
	)
	return i, err
}

const insertAllocation = `-- name: InsertAllocation :one
INSERT INTO capacity_allocation (work_order_id, period_id, quantity, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, work_order_id, period_id, quantity, created_at, reversed_at
`

type InsertAllocationParams struct {
	WorkOrderID pgtype.UUID
	PeriodID    pgtype.UUID
	Quantity    int32
	CreatedAt   pgtype.Timestamptz
}

// One capacity allocation row per used period (FR-077).
func (q *Queries) InsertAllocation(ctx context.Context, arg InsertAllocationParams) (CapacityAllocation, error) {
	row := q.db.QueryRow(ctx, insertAllocation,
		arg.WorkOrderID,
		arg.PeriodID,
		arg.Quantity,
		arg.CreatedAt,
	)
	var i CapacityAllocation
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.PeriodID,
		&i.Quantity,
		&i.CreatedAt,
		&i.ReversedAt,
	)
	return i, err
}

const insertOrderStatusHistory = `-- name: InsertOrderStatusHistory :exec
INSERT INTO work_order_status_history (
    work_order_id, old_status, new_status, changed_by, by_system, note, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOrderStatusHistoryParams struct {
	WorkOrderID pgtype.UUID
	OldStatus   NullWorkOrderStatus
	NewStatus   WorkOrderStatus
	ChangedBy   pgtype.UUID
	BySystem    bool
	Note        pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

// Records the opening status transition of a work order for its history trail.
func (q *Queries) InsertOrderStatusHistory(ctx context.Context, arg InsertOrderStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, insertOrderStatusHistory,
		arg.WorkOrderID,
		arg.OldStatus,
		arg.NewStatus,
		arg.ChangedBy,
		arg.BySystem,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const insertWorkOrder = `-- name: InsertWorkOrder :one
INSERT INTO work_order (
    candidate_id, offer_id, buyer_id, subcontractor_id,
    quantity, total_price, deadline, readiness_week_start, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, candidate_id, offer_id, buyer_id, subcontractor_id, quantity, total_price, deadline, readiness_week_start, status, shipped_at, confirmed_at, auto_confirmed, cancelled_by_id, cancellation_reason, cancelled_at, created_at
`

type InsertWorkOrderParams struct {
	CandidateID        pgtype.UUID
	OfferID            pgtype.UUID
	BuyerID            pgtype.UUID
	SubcontractorID    pgtype.UUID
	Quantity           int32
	TotalPrice         int64
	Deadline           pgtype.Date
	ReadinessWeekStart pgtype.Date
	CreatedAt          pgtype.Timestamptz
}

// Inserts the work order at agreement formation. readiness_week_start is stored,
// not recomputed later (FR-084); status takes its 'accepted' default.
func (q *Queries) InsertWorkOrder(ctx context.Context, arg InsertWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, insertWorkOrder,
		arg.CandidateID,
		arg.OfferID,
		arg.BuyerID,
		arg.SubcontractorID,
		arg.Quantity,
		arg.TotalPrice,
		arg.Deadline,
		arg.ReadinessWeekStart,
		arg.CreatedAt,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.OfferID,
		&i.BuyerID,
		&i.SubcontractorID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Deadline,
		&i.ReadinessWeekStart,
		&i.Status,
		&i.ShippedAt,
		&i.ConfirmedAt,
		&i.AutoConfirmed,
		&i.CancelledByID,
		&i.CancellationReason,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOtherCandidatesToNotify = `-- name: ListOtherCandidatesToNotify :many
SELECT c.id AS candidate_id, sub.account_id AS subcontractor_account
FROM request_candidate c
JOIN business_profile sub ON sub.id = c.subcontractor_id
WHERE c.request_id = $1 AND c.id <> $2 AND c.status NOT IN ('rejected', 'expired')
`

type ListOtherCandidatesToNotifyParams struct {
	RequestID pgtype.UUID
	ID        pgtype.UUID
}

type ListOtherCandidatesToNotifyRow struct {
	CandidateID          pgtype.UUID
	SubcontractorAccount pgtype.UUID
}

// The other still-open candidates of the request, so their subcontractors learn
// the request was agreed elsewhere. Rejected and expired candidates are left out.
func (q *Queries) ListOtherCandidatesToNotify(ctx context.Context, arg ListOtherCandidatesToNotifyParams) ([]ListOtherCandidatesToNotifyRow, error) {
	rows, err := q.db.Query(ctx, listOtherCandidatesToNotify, arg.RequestID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOtherCandidatesToNotifyRow{}
	for rows.Next() {
		var i ListOtherCandidatesToNotifyRow
		if err := rows.Scan(&i.CandidateID, &i.SubcontractorAccount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockListingByID = `-- name: LockListingByID :one
SELECT id, profile_id, weekly_capacity, readiness_lead_days, published, calendar_updated_at, horizon_until, created_at, updated_at FROM capacity_listing WHERE id = $1 FOR UPDATE
`

// Takes a row lock on a listing by its own id, so the accept path can extend the
// calendar horizon (FR-088) under the same lock the listing owner's edits take.
func (q *Queries) LockListingByID(ctx context.Context, id pgtype.UUID) (CapacityListing, error) {
	row := q.db.QueryRow(ctx, lockListingByID, id)
	var i CapacityListing
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WeeklyCapacity,
		&i.ReadinessLeadDays,
		&i.Published,
		&i.CalendarUpdatedAt,
		&i.HorizonUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPeriodsInRange = `-- name: LockPeriodsInRange :many
SELECT id, listing_id, week_start, total_capacity, used_capacity, marked_full, created_at, updated_at FROM availability_period
WHERE listing_id = $1 AND week_start BETWEEN $2 AND $3
ORDER BY week_start
FOR UPDATE
`

type LockPeriodsInRangeParams struct {
	ListingID   pgtype.UUID
	WeekStart   pgtype.Date
	WeekStart_2 pgtype.Date
}

// Locks every candidate period in the readiness..deadline range at once, ordered
// ascending by week_start. The order is the deadlock preventer of R-04, not tidy
// housekeeping: two agreements touching the same periods always lock them in the
// same order, so the second waits and then sees the reduced capacity.
func (q *Queries) LockPeriodsInRange(ctx context.Context, arg LockPeriodsInRangeParams) ([]AvailabilityPeriod, error) {
	rows, err := q.db.Query(ctx, lockPeriodsInRange, arg.ListingID, arg.WeekStart, arg.WeekStart_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilityPeriod{}
	for rows.Next() {
		var i AvailabilityPeriod
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.WeekStart,
			&i.TotalCapacity,
			&i.UsedCapacity,
			&i.MarkedFull,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const raiseUsedCapacity = `-- name: RaiseUsedCapacity :one
UPDATE availability_period
SET used_capacity = used_capacity + $2, updated_at = $3
WHERE id = $1
RETURNING id, listing_id, week_start, total_capacity, used_capacity, marked_full, created_at, updated_at
`

type RaiseUsedCapacityParams struct {
	ID           pgtype.UUID
	UsedCapacity int32
	UpdatedAt    pgtype.Timestamptz
}

// Raises a period's used_capacity by the allocated amount. The
// used_capacity_within_total CHECK is the FR-079/SC-018 storage-level safety net:
// if the fill logic ever over-allocates, this fails hard instead of corrupting.
func (q *Queries) RaiseUsedCapacity(ctx context.Context, arg RaiseUsedCapacityParams) (AvailabilityPeriod, error) {
	row := q.db.QueryRow(ctx, raiseUsedCapacity, arg.ID, arg.UsedCapacity, arg.UpdatedAt)
	var i AvailabilityPeriod
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.WeekStart,
		&i.TotalCapacity,
		&i.UsedCapacity,
		&i.MarkedFull,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCandidateAgreed = `-- name: SetCandidateAgreed :exec
UPDATE request_candidate
SET status = 'agreed', updated_at = $2
WHERE id = $1
`

type SetCandidateAgreedParams struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

// Marks the winning candidate agreed. The partial unique index
// idx_one_agreement_per_request enforces at most one agreement per request, so a
// concurrent second agreement violates it and the transaction fails (FR-036).
func (q *Queries) SetCandidateAgreed(ctx context.Context, arg SetCandidateAgreedParams) error {
	_, err := q.db.Exec(ctx, setCandidateAgreed, arg.ID, arg.UpdatedAt)
	return err
}
