// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cityExists = `-- name: CityExists :one
SELECT EXISTS (SELECT 1 FROM city WHERE code = $1)
`

// CityExists reports whether a city code is known, so registration and profile
// edits can answer 422 on an unknown city instead of surfacing a foreign key
// violation as a 500.
func (q *Queries) CityExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, cityExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO business_profile (
    id, account_id, business_name, city_code,
    created_at, updated_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $4
)
RETURNING id, account_id, business_name, city_code, latitude, longitude, description, verified, created_at, updated_at
`

type CreateProfileParams struct {
	AccountID    pgtype.UUID
	BusinessName string
	CityCode     string
	CreatedAt    pgtype.Timestamptz
}

// CreateProfile inserts the business profile that is born together with the
// account inside the registration transaction. latitude and longitude arrive
// null at registration; the owner sets them later through PUT /profile/me. The
// coordinates_complete_or_empty and coordinates_within_indonesia constraints
// accept a null pair, so a fresh profile carries no location yet.
func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (BusinessProfile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.AccountID,
		arg.BusinessName,
		arg.CityCode,
		arg.CreatedAt,
	)
	var i BusinessProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.BusinessName,
		&i.CityCode,
		&i.Latitude,
		&i.Longitude,
		&i.Description,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByAccount = `-- name: GetProfileByAccount :one
SELECT p.id, p.account_id, p.business_name, p.city_code, p.latitude, p.longitude, p.description, p.verified, p.created_at, p.updated_at, c.name AS city_name, c.province_code, pr.name AS province_name
FROM business_profile p
JOIN city c ON c.code = p.city_code
JOIN province pr ON pr.code = c.province_code
WHERE p.account_id = $1
`

type GetProfileByAccountRow struct {
	ID           pgtype.UUID
	AccountID    pgtype.UUID
	BusinessName string
	CityCode     string
	Latitude     pgtype.Numeric
	Longitude    pgtype.Numeric
	Description  pgtype.Text
	Verified     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	CityName     string
	ProvinceCode string
	ProvinceName string
}

// GetProfileByAccount loads the caller's own profile by account id, backing
// GET /profile/me. The city join resolves the human-readable city and province
// names the contract returns as read-only fields, so the client never has to
// look them up separately.
func (q *Queries) GetProfileByAccount(ctx context.Context, accountID pgtype.UUID) (GetProfileByAccountRow, error) {
	row := q.db.QueryRow(ctx, getProfileByAccount, accountID)
	var i GetProfileByAccountRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.BusinessName,
		&i.CityCode,
		&i.Latitude,
		&i.Longitude,
		&i.Description,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CityName,
		&i.ProvinceCode,
		&i.ProvinceName,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT p.id, p.account_id, p.business_name, p.city_code, p.latitude, p.longitude, p.description, p.verified, p.created_at, p.updated_at, c.name AS city_name, c.province_code, pr.name AS province_name
FROM business_profile p
JOIN city c ON c.code = p.city_code
JOIN province pr ON pr.code = c.province_code
WHERE p.id = $1
`

type GetProfileByIDRow struct {
	ID           pgtype.UUID
	AccountID    pgtype.UUID
	BusinessName string
	CityCode     string
	Latitude     pgtype.Numeric
	Longitude    pgtype.Numeric
	Description  pgtype.Text
	Verified     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	CityName     string
	ProvinceCode string
	ProvinceName string
}

// GetProfileByID loads any profile by its id for the public view, joining city
// and province for their names. The public handler decides which columns to
// expose; this query returns the full row and the caller projects it.
func (q *Queries) GetProfileByID(ctx context.Context, id pgtype.UUID) (GetProfileByIDRow, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i GetProfileByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.BusinessName,
		&i.CityCode,
		&i.Latitude,
		&i.Longitude,
		&i.Description,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CityName,
		&i.ProvinceCode,
		&i.ProvinceName,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE business_profile
SET business_name = $2,
    city_code     = $3,
    latitude      = $4,
    longitude     = $5,
    description   = $6,
    updated_at    = $7
WHERE id = $1
RETURNING id, account_id, business_name, city_code, latitude, longitude, description, verified, created_at, updated_at
`

type UpdateProfileParams struct {
	ID           pgtype.UUID
	BusinessName string
	CityCode     string
	Latitude     pgtype.Numeric
	Longitude    pgtype.Numeric
	Description  pgtype.Text
	UpdatedAt    pgtype.Timestamptz
}

// UpdateProfile writes the fields the owner may change through PUT /profile/me:
// the business name, the chosen city, the map coordinates, and the free-text
// description. account_id and verified are never touched here.
func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (BusinessProfile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.BusinessName,
		arg.CityCode,
		arg.Latitude,
		arg.Longitude,
		arg.Description,
		arg.UpdatedAt,
	)
	var i BusinessProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.BusinessName,
		&i.CityCode,
		&i.Latitude,
		&i.Longitude,
		&i.Description,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
