// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Closes one shipped order as system-confirmed (FR-068): status to 'confirmed',
	// auto_confirmed true (marking this closure as the system's, not a party's), and
	// confirmed_at stamped from the caller's Clock instant. The status = 'shipped'
	// guard makes the write a no-op if a party confirmed the order since the scan. The
	// NOT EXISTS open-dispute guard closes the race where a dispute is reported between
	// the scan and this update: a disputed order stays open even though its status is
	// still 'shipped' (FR-070). A returned row means this call did the closing.
	// Together the columns satisfy the auto_confirm_needs_confirmation and
	// shipped_before_confirmed CHECKs.
	AutoConfirmWorkOrder(ctx context.Context, arg AutoConfirmWorkOrderParams) (WorkOrder, error)
	// Records a pre-production self-cancellation on the order itself (FR-065): the
	// cancelling party's profile id, the reason, and the moment, moving status to
	// 'cancelled'. Together the four columns satisfy the cancellation_complete
	// CHECK. The allocation reversal (FR-020) runs separately under the same tx.
	CancelWorkOrder(ctx context.Context, arg CancelWorkOrderParams) (WorkOrder, error)
	// CityExists reports whether a city code is known, so registration and profile
	// edits can answer 422 on an unknown city instead of surfacing a foreign key
	// violation as a 500.
	CityExists(ctx context.Context, code string) (bool, error)
	// ClaimPendingChannels returns channels still awaiting delivery, oldest first
	// (attempted_at NULLS FIRST puts never-tried rows ahead of retried ones), with
	// the recipient address and message text joined in so the delivery job needs no
	// second query. The attempts < 3 guard skips rows already exhausted; the
	// delivery job runs under an advisory lock, so no row lock is needed to keep two
	// instances off the same channel.
	ClaimPendingChannels(ctx context.Context, limit int32) ([]ClaimPendingChannelsRow, error)
	// Closes the request's other candidates once one is agreed (FR-034): they move to
	// not_continued, leaving already rejected, expired, or agreed rows untouched.
	CloseOtherCandidates(ctx context.Context, arg CloseOtherCandidatesParams) error
	// ConsumeVerificationCode marks a code used so it cannot be replayed. The
	// consumed_at IS NULL guard makes double-consume a no-op, and the returned row
	// count lets the caller detect a code already spent.
	ConsumeVerificationCode(ctx context.Context, arg ConsumeVerificationCodeParams) (int64, error)
	// CountActiveCatalogItemsOfType counts how many of the given ids are active
	// items of the expected type. The service compares this to the number of ids it
	// sent: any shortfall means an unknown, inactive, or wrong-type id, which it
	// reports as a 422 before the type-checking trigger would raise a bare 500.
	CountActiveCatalogItemsOfType(ctx context.Context, arg CountActiveCatalogItemsOfTypeParams) (int64, error)
	// CountActiveOrdersAsBuyer counts a profile's orders that are not terminal, on
	// the buyer side. Revoking the buyer role while any of these exist is refused,
	// because it would strip a party from an order still in flight.
	CountActiveOrdersAsBuyer(ctx context.Context, buyerID pgtype.UUID) (int64, error)
	// CountActiveOrdersAsSubcontractor counts a profile's non-terminal orders on the
	// subcontractor side, guarding subcontractor-role revocation the same way.
	CountActiveOrdersAsSubcontractor(ctx context.Context, subcontractorID pgtype.UUID) (int64, error)
	CountCatalogByType(ctx context.Context, type_ ItemType) (int64, error)
	CountCities(ctx context.Context) (int64, error)
	// CountDistinctMembers counts the distinct members recorded under an address in
	// the current window. Each (address, member) pair is one row, so the row count
	// is the distinct-member count. The pattern is address + separator + '%'.
	CountDistinctMembers(ctx context.Context, arg CountDistinctMembersParams) (int64, error)
	// CountProvinces, CountCities, CountCatalogByType back the seed verification and
	// the "count is greater than zero" done-check.
	CountProvinces(ctx context.Context) (int64, error)
	// CountUnreadNotifications backs the unread_count field of NotificationList. It
	// rides the partial idx_notification_unread index.
	CountUnreadNotifications(ctx context.Context, accountID pgtype.UUID) (int64, error)
	// CreateAccount inserts a new account. business role columns default false at
	// the table level; the caller passes only the roles chosen at registration.
	// password_hash is a bcrypt digest, never the plaintext password.
	CreateAccount(ctx context.Context, arg CreateAccountParams) (UserAccount, error)
	// Capacity listing and its availability calendar. One listing per profile
	// (one_listing_per_profile); the weekly capacity is the central number
	// (FR-012/FR-014) propagated to future periods on edit (FR-089). Periods are
	// stored as the Monday date of each week (week_start_is_monday); the horizon is
	// the furthest Monday that already has a period.
	// CreateListing inserts the single listing a profile may own. horizon_until is
	// seeded to the current week's Monday (it is NOT NULL and must be a Monday);
	// EnsureHorizon raises it and generates the calendar in the same transaction.
	// calendar_updated_at starts at creation time; only an owner edit to the
	// calendar advances it afterward (FR-021).
	CreateListing(ctx context.Context, arg CreateListingParams) (CapacityListing, error)
	// CreateProfile inserts the business profile that is born together with the
	// account inside the registration transaction. latitude and longitude arrive
	// null at registration; the owner sets them later through PUT /profile/me. The
	// coordinates_complete_or_empty and coordinates_within_indonesia constraints
	// accept a null pair, so a fresh profile carries no location yet.
	CreateProfile(ctx context.Context, arg CreateProfileParams) (BusinessProfile, error)
	// CreateSession stores a new session row keyed by the SHA-256 hash of the
	// opaque token. The raw token lives only in the cookie; the database never
	// sees it, so a database read cannot reconstruct a usable session token.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// CreateUploadedFile records one stored file. The storage_path is a
	// system-generated UUID name, never the client's filename; original_name is
	// kept as display metadata only. size_bytes and mime_type are the values the
	// application verified (magic bytes, re-encoded length), not what the client
	// claimed, so the DB CHECK constraints see the trusted values.
	CreateUploadedFile(ctx context.Context, arg CreateUploadedFileParams) (UploadedFile, error)
	// CreateVerificationCode stores one six-digit code as its SHA-256 hash for a
	// given account and purpose. The plaintext code is delivered out of band (email
	// or WhatsApp) and never persisted, so a database read cannot reveal it.
	CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error)
	// CreateVerificationRequest records one pending verification submission for a
	// profile. status defaults to 'pending' in the schema, so it is not set here;
	// decided_by, decided_at and admin_note stay NULL until an admin decides. The
	// idx_one_pending_verification partial unique index rejects a second pending row
	// for the same profile with a 23505, which the handler turns into a 409
	// (FR-011: re-submission is allowed only after a rejection).
	CreateVerificationRequest(ctx context.Context, arg CreateVerificationRequestParams) (VerificationRequest, error)
	// DecideItemProposal applies an admin decision to a still-pending proposal
	// (FR-058, driven by T068). It sets status, admin_note, decided_by, decided_at,
	// and the resulting item_id (non-null only on approval), guarding on the current
	// 'pending' status so a second decision on the same row affects nothing and
	// RETURNING yields no row. The decision_complete and approved_yields_item table
	// constraints enforce the shape of an approved versus rejected decision.
	DecideItemProposal(ctx context.Context, arg DecideItemProposalParams) (ItemProposal, error)
	// DeleteAllSessions removes every session for an account, used when no session
	// is retained (recovery confirmed without an active caller session).
	DeleteAllSessions(ctx context.Context, accountID pgtype.UUID) error
	// DeleteListingMachines clears a listing's machine links before rewriting them.
	DeleteListingMachines(ctx context.Context, listingID pgtype.UUID) error
	// DeleteListingProducts clears a listing's product links before rewriting them
	// on an edit.
	DeleteListingProducts(ctx context.Context, listingID pgtype.UUID) error
	// DeleteOtherSessions removes every session for an account except the one whose
	// hash is kept. Recovery confirmation uses this to end all other sessions after
	// a password reset, without logging the current caller out mid-request.
	DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error
	// DeleteSession removes one session by token hash, backing logout.
	DeleteSession(ctx context.Context, tokenHash []byte) error
	// EmailExists reports whether an email is already registered, so registration
	// can answer 409 without leaking through a full row read.
	EmailExists(ctx context.Context, email string) (bool, error)
	// Optimistic remaining capacity across the readiness..deadline range, read BEFORE
	// the accept path takes any lock. It mirrors search's formula (search.sql,
	// FR-080/FR-088): recorded remaining over not-full periods plus an optimistic
	// estimate for weeks past horizon_until counted at weekly_capacity. A shortfall
	// here means the offer never had enough capacity, so accept fails fast with
	// INSUFFICIENT_CAPACITY without locking. If this passes but the post-lock read is
	// short, the capacity was definitively taken between the two reads
	// (CAPACITY_ALREADY_TAKEN). Deadline is rounded to Monday in Go before calling.
	EstimateCapacityInRange(ctx context.Context, arg EstimateCapacityInRangeParams) (EstimateCapacityInRangeRow, error)
	// FindFutureAllocatedPeriodOverCapacity returns the earliest future period whose
	// used capacity already exceeds the proposed new weekly capacity, so a listing
	// edit that would strand a running order is rejected with a 409 that names the
	// offending week and amount rather than silently corrupting the calendar.
	FindFutureAllocatedPeriodOverCapacity(ctx context.Context, arg FindFutureAllocatedPeriodOverCapacityParams) (FindFutureAllocatedPeriodOverCapacityRow, error)
	// GetAccountByEmail loads one account by its case-insensitive email. Used by
	// login and recovery; both must run the rate limit before this lookup.
	GetAccountByEmail(ctx context.Context, email string) (UserAccount, error)
	// GetAccountByID loads one account by id, backing GET /me and session refresh.
	GetAccountByID(ctx context.Context, id pgtype.UUID) (UserAccount, error)
	// GetAccountByPhone loads one account by phone, backing WhatsApp verification
	// and the emergency user:verify --phone subcommand.
	GetAccountByPhone(ctx context.Context, phone string) (UserAccount, error)
	// GetCandidateForOffer loads one candidate with everything the offer and reject
	// paths need in a single read: the candidate's status and its owning
	// subcontractor account (for the role check), the request's quantity, deadline,
	// and reply window (FR-035, FR-090, expiry), and the listing's capacity shape
	// (weekly_capacity, readiness_lead_days, horizon_until) plus the buyer account to
	// notify. It is the incoming-side counterpart to GetCandidateListings.
	GetCandidateForOffer(ctx context.Context, id pgtype.UUID) (GetCandidateForOfferRow, error)
	// GetCandidateListings resolves each listing id to its owning profile and that
	// profile's account, and reports whether the listing is published. The service
	// uses this to reject unknown or unpublished listings (422) and to detect a
	// listing owned by the searcher's own profile (FR-083) before any insert.
	GetCandidateListings(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetCandidateListingsRow, error)
	// GetItemProposalByID loads one proposal, joined with the proposer's account id
	// so the decision path knows whom to notify. account_id is the business
	// profile's owner, the recipient of the item_proposal_decision notification.
	GetItemProposalByID(ctx context.Context, id pgtype.UUID) (GetItemProposalByIDRow, error)
	// GetLatestVerificationCode returns the most recent unconsumed code for an
	// account and purpose. Verification compares the submitted code's hash against
	// this row and checks expiry in Go against the injected Clock.
	GetLatestVerificationCode(ctx context.Context, arg GetLatestVerificationCodeParams) (VerificationCode, error)
	// GetListingByID loads any listing by its own id, for the public profile join.
	GetListingByID(ctx context.Context, id pgtype.UUID) (CapacityListing, error)
	// GetListingByProfile loads a profile's listing, backing GET /listing/me. A
	// missing row is a genuine 404 (the profile has not created a listing yet), not
	// an invariant violation.
	GetListingByProfile(ctx context.Context, profileID pgtype.UUID) (CapacityListing, error)
	// GetNotifPreferences reads the two non-transactional channel toggles for one
	// account, backing GET /notifications/preferences (FR-054).
	GetNotifPreferences(ctx context.Context, id pgtype.UUID) (GetNotifPreferencesRow, error)
	// Loads everything the accept path needs about one offer: the offer terms, the
	// candidate and its owning listing, the request and both parties, the listing
	// capacity fields, whether the offer is the standing (latest) one, and whether
	// any candidate of the request already reached an agreement. Keyed on the offer
	// id the buyer accepts.
	GetOfferForAccept(ctx context.Context, id pgtype.UUID) (GetOfferForAcceptRow, error)
	// GetOfferForCounter loads one offer with the context the counter-offer path
	// needs: the candidate it belongs to, that candidate's status, and both parties'
	// accounts so the service can check the caller alternates with the last proposer
	// and notify the other side (FR-033).
	GetOfferForCounter(ctx context.Context, id pgtype.UUID) (GetOfferForCounterRow, error)
	// GetProfileByAccount loads the caller's own profile by account id, backing
	// GET /profile/me. The city join resolves the human-readable city and province
	// names the contract returns as read-only fields, so the client never has to
	// look them up separately.
	GetProfileByAccount(ctx context.Context, accountID pgtype.UUID) (GetProfileByAccountRow, error)
	// GetProfileByID loads any profile by its id for the public view, joining city
	// and province for their names. The public handler decides which columns to
	// expose; this query returns the full row and the caller projects it.
	GetProfileByID(ctx context.Context, id pgtype.UUID) (GetProfileByIDRow, error)
	// GetProfileIDByAccount returns the business profile id for an account, or no
	// rows when none exists yet. MyAccount carries profile_id as nullable, so the
	// caller treats pgx.ErrNoRows as a null profile_id rather than an error.
	GetProfileIDByAccount(ctx context.Context, accountID pgtype.UUID) (pgtype.UUID, error)
	// GetRequestForBuyer loads one request owned by a buyer account, for the detail
	// view (FR-032). The buyer account guard makes a request that is not the
	// caller's a 404 rather than leaking its existence.
	GetRequestForBuyer(ctx context.Context, arg GetRequestForBuyerParams) (QuotaRequest, error)
	// GetSessionByTokenHash loads a live session by token hash. The expiry check is
	// in SQL so an expired row is treated as absent without a second round trip.
	GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (Session, error)
	// GetUploadedFile returns one file row by id. The handler resolves the caller's
	// profile and admin flag and compares against owner_profile_id before streaming
	// the bytes, so this query carries no access check of its own (FR-009 is
	// enforced in Go, not SQL).
	GetUploadedFile(ctx context.Context, id pgtype.UUID) (UploadedFile, error)
	// Loads one work order with the fields WorkOrderDetail needs beyond the row
	// itself: both parties' account ids (for the party guard), the request's product
	// item, and the offer's readiness lead. Keyed on the work order id; the caller
	// checks the account ids against the principal so a non-party sees a 404.
	// has_open_dispute carries whether any unresolved dispute exists on the order, so
	// the read layer feeds it to order.IsAutoConfirmDue: an open dispute halts the
	// lazy auto-confirm exactly as the NOT EXISTS guard halts the ticker, so the two
	// layers never disagree on a disputed order (FR-070).
	GetWorkOrderForView(ctx context.Context, id pgtype.UUID) (GetWorkOrderForViewRow, error)
	// One capacity allocation row per used period (FR-077).
	InsertAllocation(ctx context.Context, arg InsertAllocationParams) (CapacityAllocation, error)
	// Opens a dispute on a work order (FR-046). status takes its 'reported' default.
	// The idx_one_open_dispute partial unique index (work_order_id WHERE status <>
	// 'resolved') means at most one dispute may be open per order; a second report
	// violates it and the caller turns the 23505 into a readable DISPUTE_ALREADY_OPEN
	// 409 (FR-046). reporter_id is the reporting party's business profile id.
	InsertDispute(ctx context.Context, arg InsertDisputeParams) (Dispute, error)
	// InsertItemProposal records a user's proposal for a new catalog item (FR-061).
	// profile_id is the proposer's business profile, type is product or machine, and
	// created_at comes from the Clock since the column has no DB default. status
	// defaults to 'pending'; decided_* stay null until an admin decides.
	InsertItemProposal(ctx context.Context, arg InsertItemProposalParams) (ItemProposal, error)
	// InsertListingMachine links a machine item and its unit count to the listing.
	InsertListingMachine(ctx context.Context, arg InsertListingMachineParams) error
	// InsertListingProduct links a product item to the listing. The
	// trg_reject_wrong_product_item trigger rejects a machine id here, but the
	// service checks the item type first so a mismatch is a 422, not a 500.
	InsertListingProduct(ctx context.Context, arg InsertListingProductParams) error
	// InsertNotification writes the in-platform notification row. It is always
	// called inside the triggering event's transaction (Enqueue takes a pgx.Tx),
	// so the notification is committed with the event or not at all (FR-086): a
	// rolled-back order change leaves no orphan notification. created_at comes from
	// the Clock, never a DB default (Rule 5).
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (pgtype.UUID, error)
	// InsertNotificationChannel queues one external delivery channel for a
	// notification. The row starts pending with zero attempts; the delivery job
	// claims it later. The in-platform notification itself needs no channel row,
	// it is always visible (FR-054); these rows track only email and WhatsApp fan
	// out.
	InsertNotificationChannel(ctx context.Context, arg InsertNotificationChannelParams) error
	// InsertOffer appends one offer to a candidate's chain, computing the next
	// sequence as max+1 so every counter-offer is a new row and the full history is
	// preserved (FR-033). created_at comes from the injected Clock (Rule 5).
	InsertOffer(ctx context.Context, arg InsertOfferParams) (Offer, error)
	// Records the opening status transition of a work order for its history trail.
	InsertOrderStatusHistory(ctx context.Context, arg InsertOrderStatusHistoryParams) error
	// Records one party's payment statement on a work order (FR-041). No money amount
	// is stored: the platform neither holds nor verifies funds (FR-040, FR-042), so
	// the row carries only the direction (sent/received), the date the party states,
	// an optional free note, and the Clock-stamped created_at. The
	// one_statement_per_party_per_direction unique constraint means a party can state
	// each direction at most once; a repeat violates it and the caller turns the
	// 23505 into a readable PAYMENT_STATEMENT_EXISTS 409.
	InsertPaymentRecord(ctx context.Context, arg InsertPaymentRecordParams) (PaymentRecord, error)
	// ── availability calendar ──
	// InsertPeriodsUpToWeek generates every missing weekly period from the current
	// horizon forward to untilWeek in one statement. The series runs on date, not
	// timestamptz, so there is no timezone shift that could nudge a Monday to
	// Sunday. Each new period starts at the listing's weekly_capacity, zero used.
	// ON CONFLICT keeps it idempotent and safe under concurrent calls: a week that
	// already exists is left untouched (one_period_per_week). The lower bound is
	// passed in already clamped to at least the current week's Monday so past weeks
	// are never created.
	InsertPeriodsUpToWeek(ctx context.Context, arg InsertPeriodsUpToWeekParams) error
	// InsertQuotaRequest creates one quota request. Both created_at and reply_due_at
	// are supplied by the caller from the injected Clock (FR-082, Rule 5): the table
	// has no DEFAULT now(), and its only time constraint enforces reply_due_at >
	// created_at. The 72-hour window is computed in the service, not here.
	InsertQuotaRequest(ctx context.Context, arg InsertQuotaRequestParams) (QuotaRequest, error)
	// InsertRequestCandidate links one listing to a request as a candidate. status
	// defaults to 'awaiting_reply'. The trg_reject_self_request trigger raises when
	// subcontractor_id equals the request's buyer_id; the service rejects that case
	// first (FR-083), so this insert is the safety net.
	InsertRequestCandidate(ctx context.Context, arg InsertRequestCandidateParams) (RequestCandidate, error)
	// Inserts the work order at agreement formation. readiness_week_start is stored,
	// not recomputed later (FR-084); status takes its 'accepted' default.
	InsertWorkOrder(ctx context.Context, arg InsertWorkOrderParams) (WorkOrder, error)
	// InvalidateVerificationCodes consumes all outstanding codes for an account and
	// purpose, so issuing a fresh code retires the previous ones in the same
	// transaction and only the newest can be redeemed.
	InvalidateVerificationCodes(ctx context.Context, arg InvalidateVerificationCodesParams) error
	// Locks the order's still-active allocation rows together with their periods,
	// ordered ascending by week_start. The order mirrors the formation lock order of
	// R-04 (LockPeriodsInRange), the deadlock preventer: two transactions touching
	// the same periods always take them in the same order. Already reversed rows are
	// left out, so a repeat reversal refunds nothing rather than double-crediting.
	ListActiveAllocationsForReversal(ctx context.Context, workOrderID pgtype.UUID) ([]ListActiveAllocationsForReversalRow, error)
	// ListActiveCatalogItems returns the active items of one type ordered for
	// display, for GET /master/products and /master/machines.
	ListActiveCatalogItems(ctx context.Context, type_ ItemType) ([]ListActiveCatalogItemsRow, error)
	// ListCandidatesByRequests returns every candidate of the given requests, joined
	// to its subcontractor profile for the business name, ordered so a request's
	// candidates group together deterministically.
	ListCandidatesByRequests(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListCandidatesByRequestsRow, error)
	// ListCities returns every city ordered by code, for GET /regions/cities with no
	// province filter.
	ListCities(ctx context.Context) ([]City, error)
	// ListCitiesByProvince returns the cities of one province, for
	// GET /regions/cities?province=.
	ListCitiesByProvince(ctx context.Context, provinceCode string) ([]City, error)
	// ListIncomingCandidates returns one keyset page of candidates whose listing the
	// subcontractor account owns, newest request first (FR-030). An optional status
	// filter narrows to one candidate_status. The cursor tuple is (created_at, id)
	// of the request, matching the buyer-side list.
	ListIncomingCandidates(ctx context.Context, arg ListIncomingCandidatesParams) ([]ListIncomingCandidatesRow, error)
	// ListListingMachines returns the machine items of a listing with their counts.
	ListListingMachines(ctx context.Context, listingID pgtype.UUID) ([]ListListingMachinesRow, error)
	// ListListingProducts returns the product items of a listing joined to their
	// catalog rows, so the response carries names, not bare ids.
	ListListingProducts(ctx context.Context, listingID pgtype.UUID) ([]ListListingProductsRow, error)
	// ListNotifications returns one account's notifications newest first, keyset
	// paginated on (created_at, id) so the order is stable across pages even as new
	// rows arrive. unread_only filters to still-unread rows (FR-051 list). A null
	// before_created is the first page; later pages pass the last row's cursor.
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	// ListOffersByRequest returns every offer across all candidates of a request so
	// the detail view attaches each candidate's chain in one query (FR-032).
	ListOffersByRequest(ctx context.Context, requestID pgtype.UUID) ([]Offer, error)
	// The other still-open candidates of the request, so their subcontractors learn
	// the request was agreed elsewhere. Rejected and expired candidates are left out.
	ListOtherCandidatesToNotify(ctx context.Context, arg ListOtherCandidatesToNotifyParams) ([]ListOtherCandidatesToNotifyRow, error)
	// Every payment statement on one work order for WorkOrderDetail (FR-041). Ordered
	// by created_at so the two parties' statements read in the order they were made;
	// both directions from both parties are visible, so a disagreement (one party
	// states sent, the counterparty never states received) is apparent to the parties
	// and to admin when a dispute is reported (FR-043).
	ListPaymentRecordsForWorkOrder(ctx context.Context, workOrderID pgtype.UUID) ([]PaymentRecord, error)
	// ListPeriodsInRange returns the periods of a listing within an inclusive
	// week_start range, ordered ascending, for GET /listing/me/periods. allocated
	// is the sum of active allocation quantities on each period; remaining is the
	// capacity left, floored at zero and forced to zero when the week is marked
	// full.
	ListPeriodsInRange(ctx context.Context, arg ListPeriodsInRangeParams) ([]ListPeriodsInRangeRow, error)
	// ListProvinces returns every province ordered by code, for GET /regions/provinces.
	ListProvinces(ctx context.Context) ([]Province, error)
	// ListQuotaRequestsByBuyer returns one keyset page of a buyer's own requests,
	// newest first, ordered by (created_at, id) so the order is total and stable
	// across pages (FR-030, FR-080). The cursor tuple admits every row on the first
	// page via sentinels above the maxima.
	ListQuotaRequestsByBuyer(ctx context.Context, arg ListQuotaRequestsByBuyerParams) ([]QuotaRequest, error)
	// The shipped orders inside the FR-069 warning lead that have not yet been warned:
	// shipped_at is within (warn_after, due_after] so the auto-confirm instant is
	// between AutoConfirmWarnLead and now, and confirm_warn_sent_at IS NULL dedups so
	// the ticker warns each order once, not on every tick. The caller passes
	// warn_after = now - AutoConfirmWindow + AutoConfirmWarnLead and due_after =
	// now - AutoConfirmWindow, both from the Clock, so the window matches
	// order.IsAutoConfirmApproaching. An order with an open dispute is excluded by the
	// NOT EXISTS guard, so a disputed order is neither warned about nor auto-closed
	// (FR-070). Rides idx_order_auto_confirm. Returns the id, the buyer account (the
	// only party FR-069 warns), and shipped_at so the caller can name the auto-confirm
	// date in the notice.
	ListShippedApproachingAutoConfirm(ctx context.Context, arg ListShippedApproachingAutoConfirmParams) ([]ListShippedApproachingAutoConfirmRow, error)
	// The shipped orders whose 7-day auto-confirm instant has arrived (FR-068),
	// for the in-process ticker to close. shipped_at <= $1 is the due test with $1 =
	// now - AutoConfirmWindow computed by the caller from the injected Clock, so the
	// boundary matches order.IsAutoConfirmDue exactly and no wall clock is read in
	// SQL. Rides idx_order_auto_confirm (shipped_at) WHERE status='shipped'. An order
	// with an open dispute is excluded by the NOT EXISTS guard, so reporting a dispute
	// stops the auto-confirm count without moving the order off 'shipped' (FR-070):
	// the dispute row, not the work-order status, is what halts the clock, and admin
	// moves the order to in_mediation separately (T071). Returns each order's id and
	// both parties' account ids for the closure notice.
	ListShippedDueForAutoConfirm(ctx context.Context, dueBefore pgtype.Timestamptz) ([]ListShippedDueForAutoConfirmRow, error)
	// ListVerificationRequestsByProfile returns every submission a profile has made,
	// newest first, joined to business_profile for the business_name the contract's
	// VerificationRequest carries (the verification_request table has no such
	// column). The caller sees only their own submissions (FR-006).
	ListVerificationRequestsByProfile(ctx context.Context, profileID pgtype.UUID) ([]ListVerificationRequestsByProfileRow, error)
	// The still-active allocation periods of one work order with the period figures
	// WorkOrderDetail renders, ordered ascending by week_start. Reversed rows are
	// left out so a cancelled order shows no live allocation.
	ListWorkOrderAllocations(ctx context.Context, workOrderID pgtype.UUID) ([]ListWorkOrderAllocationsRow, error)
	// The status trail of one work order, oldest first, for WorkOrderDetail. Rides
	// idx_status_history_order (work_order_id, created_at) so it stays ordered
	// without a sort.
	ListWorkOrderStatusHistory(ctx context.Context, workOrderID pgtype.UUID) ([]ListWorkOrderStatusHistoryRow, error)
	// One party's work orders newest first, keyset paginated on (created_at, id) so
	// the order is stable across pages (FR-038). role_filter selects the side:
	// 'as_buyer' matches the buyer profile, 'as_subcontractor' the subcontractor
	// profile, any other value matches either. An empty status_filter array means no
	// status restriction; otherwise only the listed statuses pass. The filter is a
	// text[] cast against wo.status::text, not a work_order_status[]: pgx cannot encode
	// a slice of the named enum type without the enum OID registered on the pool, so an
	// enum-array parameter fails to encode on every request (empty slice included). The
	// text cast sidesteps that with no per-connection type registration (Principle IV).
	// A null before_created is the first page. has_open_dispute rides along so
	// listItemView feeds it to order.IsAutoConfirmDue, keeping the list's lazy
	// auto-confirm in step with the detail view and the ticker on a disputed order
	// (FR-070).
	ListWorkOrdersForParty(ctx context.Context, arg ListWorkOrdersForPartyParams) ([]ListWorkOrdersForPartyRow, error)
	// Takes a row lock on a listing by its own id, so the accept path can extend the
	// calendar horizon (FR-088) under the same lock the listing owner's edits take.
	LockListingByID(ctx context.Context, id pgtype.UUID) (CapacityListing, error)
	// LockListingByProfile takes a row lock on the profile's listing so a capacity
	// edit and its propagation to future periods run as one serialized unit. The
	// listing row is always locked before any availability_period row, and that
	// order is fixed across the codebase to prevent deadlocks.
	LockListingByProfile(ctx context.Context, profileID pgtype.UUID) (CapacityListing, error)
	// LockPeriodByWeek locks a single period row for an owner edit, returning its
	// current capacity and usage. A missing row means the week is beyond the
	// horizon and must be generated first. Taken only after the listing row is
	// locked, keeping the fixed lock order.
	LockPeriodByWeek(ctx context.Context, arg LockPeriodByWeekParams) (AvailabilityPeriod, error)
	// Locks every candidate period in the readiness..deadline range at once, ordered
	// ascending by week_start. The order is the deadlock preventer of R-04, not tidy
	// housekeeping: two agreements touching the same periods always lock them in the
	// same order, so the second waits and then sees the reduced capacity.
	LockPeriodsInRange(ctx context.Context, arg LockPeriodsInRangeParams) ([]AvailabilityPeriod, error)
	// LockRateLimitKey takes a transaction-scoped advisory lock so the distinct
	// counting path (otp_address) serializes per source address. Without it, two
	// new numbers from the same address could both pass the distinct-count check.
	LockRateLimitKey(ctx context.Context, pgAdvisoryXactLock int64) error
	// Takes a row lock on the work order whose allocation is being reversed, so the
	// reversal runs under a lock in the same spirit as formation locking the listing.
	LockWorkOrderForReversal(ctx context.Context, id pgtype.UUID) (WorkOrder, error)
	// Row-locks a work order before a status transition so a concurrent status
	// change or cancellation on the same order serializes, matching the reversal
	// lock spirit (R-04).
	LockWorkOrderForStatusChange(ctx context.Context, id pgtype.UUID) (WorkOrder, error)
	// Returns a period's used_capacity to its pre-order value by subtracting the
	// reversed amount. The inverse of RaiseUsedCapacity; the quantity comes from the
	// allocation row being reversed, so used_capacity never drops below zero.
	LowerUsedCapacity(ctx context.Context, arg LowerUsedCapacityParams) (AvailabilityPeriod, error)
	// Marks one allocation row reversed without deleting it (FR-020), keeping the
	// audit trail. The reversed_at guard makes the write idempotent under a repeat.
	MarkAllocationReversed(ctx context.Context, arg MarkAllocationReversedParams) error
	// MarkChannelFailed records a failed attempt: attempts bumped, last_error and
	// attempted_at stamped. The third failure (attempts reaching 3) flips status to
	// failed_permanent (FR-085); earlier failures stay pending for the next tick.
	// The CASE keeps status and attempts consistent with failed_after_three_attempts.
	MarkChannelFailed(ctx context.Context, arg MarkChannelFailedParams) error
	// MarkChannelSent records a successful delivery: status sent, attempts bumped to
	// reflect the try that worked, sent_at and attempted_at stamped from the Clock.
	// A claimed row had attempts <= 2, so the +1 stays within attempts_max_three.
	MarkChannelSent(ctx context.Context, arg MarkChannelSentParams) error
	// Stamps confirm_warn_sent_at so the FR-069 approaching notice is sent to the
	// buyer once. The IS NULL guard keeps it idempotent if two overlapping ticker
	// instances both scanned before either stamped (the advisory lock makes that
	// rare, but the guard removes the race entirely).
	MarkConfirmWarnSent(ctx context.Context, arg MarkConfirmWarnSentParams) error
	// MarkNotificationRead stamps read_at on one notification the caller owns. The
	// account_id predicate is the ownership check: a caller marking another
	// account's id affects zero rows, which the handler turns into a 404, so the
	// endpoint never confirms a notification the caller cannot see. COALESCE keeps
	// the first read time, so re-marking an already-read notification still matches
	// one row (idempotent 204) instead of a false 404.
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error)
	// MemberRecorded reports whether member was already recorded under key in the
	// current window. A re-send to a number already counted is not a new distinct
	// number, so it does not consume more of the address budget.
	MemberRecorded(ctx context.Context, arg MemberRecordedParams) (bool, error)
	// Moves a shipped or otherwise-active order into 'in_mediation' when a dispute is
	// reported (FR-070). The status = 'shipped' scan of ListShippedDueForAutoConfirm
	// excludes 'in_mediation', so opening a dispute before the 7-day deadline stops
	// the auto-confirm count. confirm_warn_sent_at is deliberately left untouched: a
	// buyer already warned stays warned even if the dispute later closes without
	// cancelling (data-model.md). The status guard rejects moving a terminal order
	// (confirmed/cancelled), so a returned row means this call did the move.
	MoveWorkOrderToMediation(ctx context.Context, id pgtype.UUID) (WorkOrder, error)
	// PeriodHasActiveAllocation reports whether a period carries any unreversed
	// allocation, gating the "cannot mark full" and "cannot lower below used" edits.
	PeriodHasActiveAllocation(ctx context.Context, periodID pgtype.UUID) (bool, error)
	// PhoneExists reports whether a phone is already registered.
	PhoneExists(ctx context.Context, phone string) (bool, error)
	Ping(ctx context.Context) (int32, error)
	// PropagateCapacityToFuturePeriods sets total_capacity on every future period
	// that carries no active allocation (FR-089): a capacity change flows to weeks
	// the owner has not committed yet, while allocated weeks keep their agreed
	// number. The EXISTS predicate uses idx_allocation_period. week_start >= the
	// current Monday keeps past weeks frozen.
	PropagateCapacityToFuturePeriods(ctx context.Context, arg PropagateCapacityToFuturePeriodsParams) error
	// RaiseHorizonUntil moves the horizon forward, never back: GREATEST keeps the
	// result independent of commit order when two requests extend it at once.
	RaiseHorizonUntil(ctx context.Context, arg RaiseHorizonUntilParams) error
	// Raises a period's used_capacity by the allocated amount. The
	// used_capacity_within_total CHECK is the FR-079/SC-018 storage-level safety net:
	// if the fill logic ever over-allocates, this fails hard instead of corrupting.
	RaiseUsedCapacity(ctx context.Context, arg RaiseUsedCapacityParams) (AvailabilityPeriod, error)
	// RecordMember records that member was used under key in the current window.
	// DO NOTHING keeps it idempotent within the window.
	RecordMember(ctx context.Context, arg RecordMemberParams) error
	// RejectCandidate marks a candidate rejected with the subcontractor's reason
	// (FR-031), stamping updated_at from the Clock.
	RejectCandidate(ctx context.Context, arg RejectCandidateParams) error
	// RemainingCapacityForOffer sums the subcontractor's remaining capacity across
	// the readiness..deadline week range for FR-035, mirroring the capacity CTE of
	// SearchCandidates: recorded remaining over non-full availability periods in
	// range, plus periods past horizon_until counted optimistically as full weekly
	// capacity (FR-088). The caller computes readiness_week and deadline_week in Go
	// so week rounding stays in one place (Rule 4).
	RemainingCapacityForOffer(ctx context.Context, arg RemainingCapacityForOfferParams) (int64, error)
	// RenewSession slides the expiry forward and records access time, implementing
	// rolling 7-day renewal on each authenticated request.
	RenewSession(ctx context.Context, arg RenewSessionParams) error
	// SearchCandidates ranks published listings against the four hard criteria
	// (FR-023..FR-025) and returns one keyset page. The query shape follows
	// data-model.md section 10: score lives in the `ranked` CTE so the keyset WHERE
	// can filter on it, capacity is summed across the readiness..deadline range
	// (FR-080), and periods past horizon_until are counted optimistically as full
	// (FR-088). The application rounds the deadline to Monday before calling this,
	// so Go stays the single source of truth for that rounding, and horizon
	// extension happens outside this read query for passing candidates only. A NULL
	// product/machine/lead filter counts as satisfied (FR-023, decision C-4) so the
	// score stays 0..4 with no weighting or normalization (FR-024). The keyset tuple
	// ends in listing_id to make the order total and repeatable across pages.
	// Keyset "after the cursor" expanded as an explicit lexicographic OR chain
	// because the sort mixes directions: score and remaining_capacity descend while
	// lead, business_name, and listing_id ascend. A single row-value "<" comparison
	// cannot express mixed directions, so each tier compares in its own direction
	// (DESC via "<", ASC via ">") after the higher tiers tie. listing_id is the
	// final ASC tiebreaker that makes the order total and repeatable (FR-025). The
	// first page passes a score sentinel of 5, above the 0..4 maximum, so the first
	// clause admits every row.
	SearchCandidates(ctx context.Context, arg SearchCandidatesParams) ([]SearchCandidatesRow, error)
	// SearchReputation computes reputation for the profiles on one search page,
	// read at query time and never stored as a column (data-model.md section 19,
	// FR-071). It mirrors the two derived-value formulas the public profile uses:
	// average_rating and review_count from visible reviews, completed_jobs from
	// confirmed orders where the profile is subcontractor (FR-048), and the
	// completion-rate numerator/denominator (FR-071/FR-072). The FR-073 threshold
	// (divisor >= 3 before a percentage is shown) is applied in the service, not
	// here, so the raw counts stay visible. One query over the whole page avoids an
	// N+1 across candidates.
	SearchReputation(ctx context.Context, profileIds []pgtype.UUID) ([]SearchReputationRow, error)
	// Marks the winning candidate agreed. The partial unique index
	// idx_one_agreement_per_request enforces at most one agreement per request, so a
	// concurrent second agreement violates it and the transaction fails (FR-036).
	SetCandidateAgreed(ctx context.Context, arg SetCandidateAgreedParams) error
	// SetCandidateStatus moves a candidate to a new status (offered on a reply,
	// FR-031), stamping updated_at from the Clock.
	SetCandidateStatus(ctx context.Context, arg SetCandidateStatusParams) error
	// SetEmailVerified marks the email verified after a valid code is consumed.
	SetEmailVerified(ctx context.Context, arg SetEmailVerifiedParams) error
	// SetListingPublished toggles visibility for PUT /listing/me/visibility. A
	// hidden listing keeps its calendar and allocations; it simply drops out of
	// search until re-enabled.
	SetListingPublished(ctx context.Context, arg SetListingPublishedParams) (CapacityListing, error)
	// SetPhoneVerified marks the phone verified after a valid code is consumed.
	SetPhoneVerified(ctx context.Context, arg SetPhoneVerifiedParams) error
	// SumUploadedBytesByOwner totals the bytes a profile already holds, so a new
	// upload can be rejected before it pushes the owner past the 500MB quota.
	// COALESCE keeps the result 0 rather than NULL for an owner with no files yet.
	SumUploadedBytesByOwner(ctx context.Context, ownerProfileID pgtype.UUID) (int64, error)
	// TouchCalendarUpdatedAt stamps the calendar as freshly edited. This is the
	// only path that advances calendar_updated_at, so a listing whose owner never
	// edits the calendar reads as stale and FR-021 keeps working.
	TouchCalendarUpdatedAt(ctx context.Context, arg TouchCalendarUpdatedAtParams) error
	// TouchRateLimit increments the counter for one (target, key) in the current
	// window bucket, creating the row on first use, and returns the new count. The
	// ON CONFLICT DO UPDATE is atomic and takes a row lock, so two concurrent
	// callers cannot both read the same count and both slip through: the second
	// serializes behind the first and sees the incremented value.
	TouchRateLimit(ctx context.Context, arg TouchRateLimitParams) (int32, error)
	// UpdateBusinessRoles sets the two business role flags. admin is never touched
	// here; the admin_has_no_business_role constraint rejects granting a business
	// role to an admin account, so the update fails loudly instead of silently
	// corrupting the role model.
	UpdateBusinessRoles(ctx context.Context, arg UpdateBusinessRolesParams) (UserAccount, error)
	// UpdateListing writes the owner-editable listing fields. Publication state is
	// changed through SetListingPublished, not here, so a capacity edit never flips
	// visibility by accident.
	UpdateListing(ctx context.Context, arg UpdateListingParams) (CapacityListing, error)
	// UpdateNotifPreferences writes the two non-transactional channel toggles and
	// returns them, backing PUT /notifications/preferences. Transactional
	// notifications ignore these flags, so only the non-transactional channels are
	// affected (FR-091).
	UpdateNotifPreferences(ctx context.Context, arg UpdateNotifPreferencesParams) (UpdateNotifPreferencesRow, error)
	// UpdatePassword replaces the bcrypt hash during recovery confirmation.
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	// UpdateProfile writes the fields the owner may change through PUT /profile/me:
	// the business name, the chosen city, the map coordinates, and the free-text
	// description. account_id and verified are never touched here.
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (BusinessProfile, error)
	// Advances a work order to its next forward status. shipped_at is stamped only
	// on the move into 'shipped' and left untouched otherwise, so it records the
	// moment shipment was declared (the auto-confirm clock start, FR-068).
	UpdateWorkOrderStatus(ctx context.Context, arg UpdateWorkOrderStatusParams) (WorkOrder, error)
	// UpsertAdmin creates the admin account or, when the email already exists,
	// resets its password. Idempotent so admin:create can run twice without a
	// duplicate. role_admin is set true and the two business roles false, which the
	// admin_has_no_business_role and has_at_least_one_role constraints both accept.
	UpsertAdmin(ctx context.Context, arg UpsertAdminParams) (UserAccount, error)
	// UpsertCatalogItem inserts a baseline product or machine type, or reactivates
	// and reorders an existing one. Idempotent on (type, name): the seed can run
	// twice without duplicating. created_at is supplied by the caller from the Clock
	// since the column has no DB default.
	UpsertCatalogItem(ctx context.Context, arg UpsertCatalogItemParams) error
	// UpsertCity inserts a city or updates its name. The code is already normalized
	// (dots stripped, four digits) by the seeder before it reaches here, so the
	// city_code_format and city_belongs_to_province constraints hold.
	UpsertCity(ctx context.Context, arg UpsertCityParams) error
	// UpsertPeriod writes one period's capacity and full flag on an owner edit. The
	// period row is expected to exist (EnsureHorizon generated it); ON CONFLICT
	// updates it in place, keeping used_capacity untouched so an in-flight order is
	// never disturbed.
	UpsertPeriod(ctx context.Context, arg UpsertPeriodParams) error
	// Master data queries: reference regions (province, city) and the baseline
	// catalog of product and machine types. The seeders upsert by code/name so
	// running them twice never duplicates and never deletes; business_profile
	// references these rows, so a delete would orphan real data.
	// UpsertProvince inserts a province or updates its name when the code already
	// exists. Idempotent on code: the seed can run repeatedly without duplicating.
	UpsertProvince(ctx context.Context, arg UpsertProvinceParams) error
}

var _ Querier = (*Queries)(nil)
