// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// CityExists reports whether a city code is known, so registration and profile
	// edits can answer 422 on an unknown city instead of surfacing a foreign key
	// violation as a 500.
	CityExists(ctx context.Context, code string) (bool, error)
	// ClaimPendingChannels returns channels still awaiting delivery, oldest first
	// (attempted_at NULLS FIRST puts never-tried rows ahead of retried ones), with
	// the recipient address and message text joined in so the delivery job needs no
	// second query. The attempts < 3 guard skips rows already exhausted; the
	// delivery job runs under an advisory lock, so no row lock is needed to keep two
	// instances off the same channel.
	ClaimPendingChannels(ctx context.Context, limit int32) ([]ClaimPendingChannelsRow, error)
	// ConsumeVerificationCode marks a code used so it cannot be replayed. The
	// consumed_at IS NULL guard makes double-consume a no-op, and the returned row
	// count lets the caller detect a code already spent.
	ConsumeVerificationCode(ctx context.Context, arg ConsumeVerificationCodeParams) (int64, error)
	// CountActiveCatalogItemsOfType counts how many of the given ids are active
	// items of the expected type. The service compares this to the number of ids it
	// sent: any shortfall means an unknown, inactive, or wrong-type id, which it
	// reports as a 422 before the type-checking trigger would raise a bare 500.
	CountActiveCatalogItemsOfType(ctx context.Context, arg CountActiveCatalogItemsOfTypeParams) (int64, error)
	// CountActiveOrdersAsBuyer counts a profile's orders that are not terminal, on
	// the buyer side. Revoking the buyer role while any of these exist is refused,
	// because it would strip a party from an order still in flight.
	CountActiveOrdersAsBuyer(ctx context.Context, buyerID pgtype.UUID) (int64, error)
	// CountActiveOrdersAsSubcontractor counts a profile's non-terminal orders on the
	// subcontractor side, guarding subcontractor-role revocation the same way.
	CountActiveOrdersAsSubcontractor(ctx context.Context, subcontractorID pgtype.UUID) (int64, error)
	CountCatalogByType(ctx context.Context, type_ ItemType) (int64, error)
	CountCities(ctx context.Context) (int64, error)
	// CountDistinctMembers counts the distinct members recorded under an address in
	// the current window. Each (address, member) pair is one row, so the row count
	// is the distinct-member count. The pattern is address + separator + '%'.
	CountDistinctMembers(ctx context.Context, arg CountDistinctMembersParams) (int64, error)
	// CountPeriods counts a listing's periods, backing the FR-088 "at least 13
	// periods" check.
	CountPeriods(ctx context.Context, listingID pgtype.UUID) (int64, error)
	// CountProvinces, CountCities, CountCatalogByType back the seed verification and
	// the "count is greater than zero" done-check.
	CountProvinces(ctx context.Context) (int64, error)
	// CountUnreadNotifications backs the unread_count field of NotificationList. It
	// rides the partial idx_notification_unread index.
	CountUnreadNotifications(ctx context.Context, accountID pgtype.UUID) (int64, error)
	// CreateAccount inserts a new account. business role columns default false at
	// the table level; the caller passes only the roles chosen at registration.
	// password_hash is a bcrypt digest, never the plaintext password.
	CreateAccount(ctx context.Context, arg CreateAccountParams) (UserAccount, error)
	// Capacity listing and its availability calendar. One listing per profile
	// (one_listing_per_profile); the weekly capacity is the central number
	// (FR-012/FR-014) propagated to future periods on edit (FR-089). Periods are
	// stored as the Monday date of each week (week_start_is_monday); the horizon is
	// the furthest Monday that already has a period.
	// CreateListing inserts the single listing a profile may own. horizon_until is
	// seeded to the current week's Monday (it is NOT NULL and must be a Monday);
	// EnsureHorizon raises it and generates the calendar in the same transaction.
	// calendar_updated_at starts at creation time; only an owner edit to the
	// calendar advances it afterward (FR-021).
	CreateListing(ctx context.Context, arg CreateListingParams) (CapacityListing, error)
	// CreateProfile inserts the business profile that is born together with the
	// account inside the registration transaction. latitude and longitude arrive
	// null at registration; the owner sets them later through PUT /profile/me. The
	// coordinates_complete_or_empty and coordinates_within_indonesia constraints
	// accept a null pair, so a fresh profile carries no location yet.
	CreateProfile(ctx context.Context, arg CreateProfileParams) (BusinessProfile, error)
	// CreateSession stores a new session row keyed by the SHA-256 hash of the
	// opaque token. The raw token lives only in the cookie; the database never
	// sees it, so a database read cannot reconstruct a usable session token.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// CreateUploadedFile records one stored file. The storage_path is a
	// system-generated UUID name, never the client's filename; original_name is
	// kept as display metadata only. size_bytes and mime_type are the values the
	// application verified (magic bytes, re-encoded length), not what the client
	// claimed, so the DB CHECK constraints see the trusted values.
	CreateUploadedFile(ctx context.Context, arg CreateUploadedFileParams) (UploadedFile, error)
	// CreateVerificationCode stores one six-digit code as its SHA-256 hash for a
	// given account and purpose. The plaintext code is delivered out of band (email
	// or WhatsApp) and never persisted, so a database read cannot reveal it.
	CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error)
	// DecideItemProposal applies an admin decision to a still-pending proposal
	// (FR-058, driven by T068). It sets status, admin_note, decided_by, decided_at,
	// and the resulting item_id (non-null only on approval), guarding on the current
	// 'pending' status so a second decision on the same row affects nothing and
	// RETURNING yields no row. The decision_complete and approved_yields_item table
	// constraints enforce the shape of an approved versus rejected decision.
	DecideItemProposal(ctx context.Context, arg DecideItemProposalParams) (ItemProposal, error)
	// DeleteAllSessions removes every session for an account, used when no session
	// is retained (recovery confirmed without an active caller session).
	DeleteAllSessions(ctx context.Context, accountID pgtype.UUID) error
	// DeleteListingMachines clears a listing's machine links before rewriting them.
	DeleteListingMachines(ctx context.Context, listingID pgtype.UUID) error
	// DeleteListingProducts clears a listing's product links before rewriting them
	// on an edit.
	DeleteListingProducts(ctx context.Context, listingID pgtype.UUID) error
	// DeleteOtherSessions removes every session for an account except the one whose
	// hash is kept. Recovery confirmation uses this to end all other sessions after
	// a password reset, without logging the current caller out mid-request.
	DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error
	// DeleteSession removes one session by token hash, backing logout.
	DeleteSession(ctx context.Context, tokenHash []byte) error
	// EmailExists reports whether an email is already registered, so registration
	// can answer 409 without leaking through a full row read.
	EmailExists(ctx context.Context, email string) (bool, error)
	// FindFutureAllocatedPeriodOverCapacity returns the earliest future period whose
	// used capacity already exceeds the proposed new weekly capacity, so a listing
	// edit that would strand a running order is rejected with a 409 that names the
	// offending week and amount rather than silently corrupting the calendar.
	FindFutureAllocatedPeriodOverCapacity(ctx context.Context, arg FindFutureAllocatedPeriodOverCapacityParams) (FindFutureAllocatedPeriodOverCapacityRow, error)
	// GetAccountByEmail loads one account by its case-insensitive email. Used by
	// login and recovery; both must run the rate limit before this lookup.
	GetAccountByEmail(ctx context.Context, email string) (UserAccount, error)
	// GetAccountByID loads one account by id, backing GET /me and session refresh.
	GetAccountByID(ctx context.Context, id pgtype.UUID) (UserAccount, error)
	// GetAccountByPhone loads one account by phone, backing WhatsApp verification
	// and the emergency user:verify --phone subcommand.
	GetAccountByPhone(ctx context.Context, phone string) (UserAccount, error)
	// GetItemProposalByID loads one proposal, joined with the proposer's account id
	// so the decision path knows whom to notify. account_id is the business
	// profile's owner, the recipient of the item_proposal_decision notification.
	GetItemProposalByID(ctx context.Context, id pgtype.UUID) (GetItemProposalByIDRow, error)
	// GetLatestVerificationCode returns the most recent unconsumed code for an
	// account and purpose. Verification compares the submitted code's hash against
	// this row and checks expiry in Go against the injected Clock.
	GetLatestVerificationCode(ctx context.Context, arg GetLatestVerificationCodeParams) (VerificationCode, error)
	// GetListingByID loads any listing by its own id, for the public profile join.
	GetListingByID(ctx context.Context, id pgtype.UUID) (CapacityListing, error)
	// GetListingByProfile loads a profile's listing, backing GET /listing/me. A
	// missing row is a genuine 404 (the profile has not created a listing yet), not
	// an invariant violation.
	GetListingByProfile(ctx context.Context, profileID pgtype.UUID) (CapacityListing, error)
	// GetNotifPreferences reads the two non-transactional channel toggles for one
	// account, backing GET /notifications/preferences (FR-054).
	GetNotifPreferences(ctx context.Context, id pgtype.UUID) (GetNotifPreferencesRow, error)
	// GetProfileByAccount loads the caller's own profile by account id, backing
	// GET /profile/me. The city join resolves the human-readable city and province
	// names the contract returns as read-only fields, so the client never has to
	// look them up separately.
	GetProfileByAccount(ctx context.Context, accountID pgtype.UUID) (GetProfileByAccountRow, error)
	// GetProfileByID loads any profile by its id for the public view, joining city
	// and province for their names. The public handler decides which columns to
	// expose; this query returns the full row and the caller projects it.
	GetProfileByID(ctx context.Context, id pgtype.UUID) (GetProfileByIDRow, error)
	// GetProfileIDByAccount returns the business profile id for an account, or no
	// rows when none exists yet. MyAccount carries profile_id as nullable, so the
	// caller treats pgx.ErrNoRows as a null profile_id rather than an error.
	GetProfileIDByAccount(ctx context.Context, accountID pgtype.UUID) (pgtype.UUID, error)
	// GetSessionByTokenHash loads a live session by token hash. The expiry check is
	// in SQL so an expired row is treated as absent without a second round trip.
	GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (Session, error)
	// GetUploadedFile returns one file row by id. The handler resolves the caller's
	// profile and admin flag and compares against owner_profile_id before streaming
	// the bytes, so this query carries no access check of its own (FR-009 is
	// enforced in Go, not SQL).
	GetUploadedFile(ctx context.Context, id pgtype.UUID) (UploadedFile, error)
	// InsertItemProposal records a user's proposal for a new catalog item (FR-061).
	// profile_id is the proposer's business profile, type is product or machine, and
	// created_at comes from the Clock since the column has no DB default. status
	// defaults to 'pending'; decided_* stay null until an admin decides.
	InsertItemProposal(ctx context.Context, arg InsertItemProposalParams) (ItemProposal, error)
	// InsertListingMachine links a machine item and its unit count to the listing.
	InsertListingMachine(ctx context.Context, arg InsertListingMachineParams) error
	// InsertListingProduct links a product item to the listing. The
	// trg_reject_wrong_product_item trigger rejects a machine id here, but the
	// service checks the item type first so a mismatch is a 422, not a 500.
	InsertListingProduct(ctx context.Context, arg InsertListingProductParams) error
	// InsertNotification writes the in-platform notification row. It is always
	// called inside the triggering event's transaction (Enqueue takes a pgx.Tx),
	// so the notification is committed with the event or not at all (FR-086): a
	// rolled-back order change leaves no orphan notification. created_at comes from
	// the Clock, never a DB default (Rule 5).
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (pgtype.UUID, error)
	// InsertNotificationChannel queues one external delivery channel for a
	// notification. The row starts pending with zero attempts; the delivery job
	// claims it later. The in-platform notification itself needs no channel row,
	// it is always visible (FR-054); these rows track only email and WhatsApp fan
	// out.
	InsertNotificationChannel(ctx context.Context, arg InsertNotificationChannelParams) error
	// ── availability calendar ──
	// InsertPeriodsUpToWeek generates every missing weekly period from the current
	// horizon forward to untilWeek in one statement. The series runs on date, not
	// timestamptz, so there is no timezone shift that could nudge a Monday to
	// Sunday. Each new period starts at the listing's weekly_capacity, zero used.
	// ON CONFLICT keeps it idempotent and safe under concurrent calls: a week that
	// already exists is left untouched (one_period_per_week). The lower bound is
	// passed in already clamped to at least the current week's Monday so past weeks
	// are never created.
	InsertPeriodsUpToWeek(ctx context.Context, arg InsertPeriodsUpToWeekParams) error
	// InvalidateVerificationCodes consumes all outstanding codes for an account and
	// purpose, so issuing a fresh code retires the previous ones in the same
	// transaction and only the newest can be redeemed.
	InvalidateVerificationCodes(ctx context.Context, arg InvalidateVerificationCodesParams) error
	// ListActiveCatalogItems returns the active items of one type ordered for
	// display, for GET /master/products and /master/machines.
	ListActiveCatalogItems(ctx context.Context, type_ ItemType) ([]ListActiveCatalogItemsRow, error)
	// ListCities returns every city ordered by code, for GET /regions/cities with no
	// province filter.
	ListCities(ctx context.Context) ([]City, error)
	// ListCitiesByProvince returns the cities of one province, for
	// GET /regions/cities?province=.
	ListCitiesByProvince(ctx context.Context, provinceCode string) ([]City, error)
	// ListListingMachines returns the machine items of a listing with their counts.
	ListListingMachines(ctx context.Context, listingID pgtype.UUID) ([]ListListingMachinesRow, error)
	// ListListingProducts returns the product items of a listing joined to their
	// catalog rows, so the response carries names, not bare ids.
	ListListingProducts(ctx context.Context, listingID pgtype.UUID) ([]ListListingProductsRow, error)
	// ListNotifications returns one account's notifications newest first, keyset
	// paginated on (created_at, id) so the order is stable across pages even as new
	// rows arrive. unread_only filters to still-unread rows (FR-051 list). A null
	// before_created is the first page; later pages pass the last row's cursor.
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	// ListPeriodsInRange returns the periods of a listing within an inclusive
	// week_start range, ordered ascending, for GET /listing/me/periods. allocated
	// is the sum of active allocation quantities on each period; remaining is the
	// capacity left, floored at zero and forced to zero when the week is marked
	// full.
	ListPeriodsInRange(ctx context.Context, arg ListPeriodsInRangeParams) ([]ListPeriodsInRangeRow, error)
	// ListProvinces returns every province ordered by code, for GET /regions/provinces.
	ListProvinces(ctx context.Context) ([]Province, error)
	// LockListingByProfile takes a row lock on the profile's listing so a capacity
	// edit and its propagation to future periods run as one serialized unit. The
	// listing row is always locked before any availability_period row, and that
	// order is fixed across the codebase to prevent deadlocks.
	LockListingByProfile(ctx context.Context, profileID pgtype.UUID) (CapacityListing, error)
	// LockPeriodByWeek locks a single period row for an owner edit, returning its
	// current capacity and usage. A missing row means the week is beyond the
	// horizon and must be generated first. Taken only after the listing row is
	// locked, keeping the fixed lock order.
	LockPeriodByWeek(ctx context.Context, arg LockPeriodByWeekParams) (AvailabilityPeriod, error)
	// LockRateLimitKey takes a transaction-scoped advisory lock so the distinct
	// counting path (otp_address) serializes per source address. Without it, two
	// new numbers from the same address could both pass the distinct-count check.
	LockRateLimitKey(ctx context.Context, pgAdvisoryXactLock int64) error
	// MarkChannelFailed records a failed attempt: attempts bumped, last_error and
	// attempted_at stamped. The third failure (attempts reaching 3) flips status to
	// failed_permanent (FR-085); earlier failures stay pending for the next tick.
	// The CASE keeps status and attempts consistent with failed_after_three_attempts.
	MarkChannelFailed(ctx context.Context, arg MarkChannelFailedParams) error
	// MarkChannelSent records a successful delivery: status sent, attempts bumped to
	// reflect the try that worked, sent_at and attempted_at stamped from the Clock.
	// A claimed row had attempts <= 2, so the +1 stays within attempts_max_three.
	MarkChannelSent(ctx context.Context, arg MarkChannelSentParams) error
	// MarkNotificationRead stamps read_at on one notification the caller owns. The
	// account_id predicate is the ownership check: a caller marking another
	// account's id affects zero rows, which the handler turns into a 404, so the
	// endpoint never confirms a notification the caller cannot see. COALESCE keeps
	// the first read time, so re-marking an already-read notification still matches
	// one row (idempotent 204) instead of a false 404.
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error)
	// MaxPeriodWeek returns the furthest week_start a listing has, so a test can
	// assert horizon_until equals the last generated period.
	MaxPeriodWeek(ctx context.Context, listingID pgtype.UUID) (pgtype.Date, error)
	// MemberRecorded reports whether member was already recorded under key in the
	// current window. A re-send to a number already counted is not a new distinct
	// number, so it does not consume more of the address budget.
	MemberRecorded(ctx context.Context, arg MemberRecordedParams) (bool, error)
	// PeriodHasActiveAllocation reports whether a period carries any unreversed
	// allocation, gating the "cannot mark full" and "cannot lower below used" edits.
	PeriodHasActiveAllocation(ctx context.Context, periodID pgtype.UUID) (bool, error)
	// PhoneExists reports whether a phone is already registered.
	PhoneExists(ctx context.Context, phone string) (bool, error)
	Ping(ctx context.Context) (int32, error)
	// PropagateCapacityToFuturePeriods sets total_capacity on every future period
	// that carries no active allocation (FR-089): a capacity change flows to weeks
	// the owner has not committed yet, while allocated weeks keep their agreed
	// number. The EXISTS predicate uses idx_allocation_period. week_start >= the
	// current Monday keeps past weeks frozen.
	PropagateCapacityToFuturePeriods(ctx context.Context, arg PropagateCapacityToFuturePeriodsParams) error
	// RaiseHorizonUntil moves the horizon forward, never back: GREATEST keeps the
	// result independent of commit order when two requests extend it at once.
	RaiseHorizonUntil(ctx context.Context, arg RaiseHorizonUntilParams) error
	// RecordMember records that member was used under key in the current window.
	// DO NOTHING keeps it idempotent within the window.
	RecordMember(ctx context.Context, arg RecordMemberParams) error
	// RenewSession slides the expiry forward and records access time, implementing
	// rolling 7-day renewal on each authenticated request.
	RenewSession(ctx context.Context, arg RenewSessionParams) error
	// SearchCandidates ranks published listings against the four hard criteria
	// (FR-023..FR-025) and returns one keyset page. The query shape follows
	// data-model.md section 10: score lives in the `ranked` CTE so the keyset WHERE
	// can filter on it, capacity is summed across the readiness..deadline range
	// (FR-080), and periods past horizon_until are counted optimistically as full
	// (FR-088). The application rounds the deadline to Monday before calling this,
	// so Go stays the single source of truth for that rounding, and horizon
	// extension happens outside this read query for passing candidates only. A NULL
	// product/machine/lead filter counts as satisfied (FR-023, decision C-4) so the
	// score stays 0..4 with no weighting or normalization (FR-024). The keyset tuple
	// ends in listing_id to make the order total and repeatable across pages.
	// Keyset "after the cursor" expanded as an explicit lexicographic OR chain
	// because the sort mixes directions: score and remaining_capacity descend while
	// lead, business_name, and listing_id ascend. A single row-value "<" comparison
	// cannot express mixed directions, so each tier compares in its own direction
	// (DESC via "<", ASC via ">") after the higher tiers tie. listing_id is the
	// final ASC tiebreaker that makes the order total and repeatable (FR-025). The
	// first page passes a score sentinel of 5, above the 0..4 maximum, so the first
	// clause admits every row.
	SearchCandidates(ctx context.Context, arg SearchCandidatesParams) ([]SearchCandidatesRow, error)
	// SetEmailVerified marks the email verified after a valid code is consumed.
	SetEmailVerified(ctx context.Context, arg SetEmailVerifiedParams) error
	// SetListingPublished toggles visibility for PUT /listing/me/visibility. A
	// hidden listing keeps its calendar and allocations; it simply drops out of
	// search until re-enabled.
	SetListingPublished(ctx context.Context, arg SetListingPublishedParams) (CapacityListing, error)
	// SetPhoneVerified marks the phone verified after a valid code is consumed.
	SetPhoneVerified(ctx context.Context, arg SetPhoneVerifiedParams) error
	// SumUploadedBytesByOwner totals the bytes a profile already holds, so a new
	// upload can be rejected before it pushes the owner past the 500MB quota.
	// COALESCE keeps the result 0 rather than NULL for an owner with no files yet.
	SumUploadedBytesByOwner(ctx context.Context, ownerProfileID pgtype.UUID) (int64, error)
	// TouchCalendarUpdatedAt stamps the calendar as freshly edited. This is the
	// only path that advances calendar_updated_at, so a listing whose owner never
	// edits the calendar reads as stale and FR-021 keeps working.
	TouchCalendarUpdatedAt(ctx context.Context, arg TouchCalendarUpdatedAtParams) error
	// TouchRateLimit increments the counter for one (target, key) in the current
	// window bucket, creating the row on first use, and returns the new count. The
	// ON CONFLICT DO UPDATE is atomic and takes a row lock, so two concurrent
	// callers cannot both read the same count and both slip through: the second
	// serializes behind the first and sees the incremented value.
	TouchRateLimit(ctx context.Context, arg TouchRateLimitParams) (int32, error)
	// UpdateBusinessRoles sets the two business role flags. admin is never touched
	// here; the admin_has_no_business_role constraint rejects granting a business
	// role to an admin account, so the update fails loudly instead of silently
	// corrupting the role model.
	UpdateBusinessRoles(ctx context.Context, arg UpdateBusinessRolesParams) (UserAccount, error)
	// UpdateListing writes the owner-editable listing fields. Publication state is
	// changed through SetListingPublished, not here, so a capacity edit never flips
	// visibility by accident.
	UpdateListing(ctx context.Context, arg UpdateListingParams) (CapacityListing, error)
	// UpdateNotifPreferences writes the two non-transactional channel toggles and
	// returns them, backing PUT /notifications/preferences. Transactional
	// notifications ignore these flags, so only the non-transactional channels are
	// affected (FR-091).
	UpdateNotifPreferences(ctx context.Context, arg UpdateNotifPreferencesParams) (UpdateNotifPreferencesRow, error)
	// UpdatePassword replaces the bcrypt hash during recovery confirmation.
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	// UpdateProfile writes the fields the owner may change through PUT /profile/me:
	// the business name, the chosen city, the map coordinates, and the free-text
	// description. account_id and verified are never touched here.
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (BusinessProfile, error)
	// UpsertAdmin creates the admin account or, when the email already exists,
	// resets its password. Idempotent so admin:create can run twice without a
	// duplicate. role_admin is set true and the two business roles false, which the
	// admin_has_no_business_role and has_at_least_one_role constraints both accept.
	UpsertAdmin(ctx context.Context, arg UpsertAdminParams) (UserAccount, error)
	// UpsertCatalogItem inserts a baseline product or machine type, or reactivates
	// and reorders an existing one. Idempotent on (type, name): the seed can run
	// twice without duplicating. created_at is supplied by the caller from the Clock
	// since the column has no DB default.
	UpsertCatalogItem(ctx context.Context, arg UpsertCatalogItemParams) error
	// UpsertCity inserts a city or updates its name. The code is already normalized
	// (dots stripped, four digits) by the seeder before it reaches here, so the
	// city_code_format and city_belongs_to_province constraints hold.
	UpsertCity(ctx context.Context, arg UpsertCityParams) error
	// UpsertPeriod writes one period's capacity and full flag on an owner edit. The
	// period row is expected to exist (EnsureHorizon generated it); ON CONFLICT
	// updates it in place, keeping used_capacity untouched so an in-flight order is
	// never disturbed.
	UpsertPeriod(ctx context.Context, arg UpsertPeriodParams) error
	// Master data queries: reference regions (province, city) and the baseline
	// catalog of product and machine types. The seeders upsert by code/name so
	// running them twice never duplicates and never deletes; business_profile
	// references these rows, so a delete would orphan real data.
	// UpsertProvince inserts a province or updates its name when the code already
	// exists. Idempotent on code: the seed can run repeatedly without duplicating.
	UpsertProvince(ctx context.Context, arg UpsertProvinceParams) error
}

var _ Querier = (*Queries)(nil)
