// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratelimit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDistinctMembers = `-- name: CountDistinctMembers :one
SELECT count(*) FROM rate_limit
WHERE target = $1 AND key LIKE $2 AND window_start = $3
`

type CountDistinctMembersParams struct {
	Target      RateLimitTarget
	Key         string
	WindowStart pgtype.Timestamptz
}

// CountDistinctMembers counts the distinct members recorded under an address in
// the current window. Each (address, member) pair is one row, so the row count
// is the distinct-member count. The pattern is address + separator + '%'.
func (q *Queries) CountDistinctMembers(ctx context.Context, arg CountDistinctMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDistinctMembers, arg.Target, arg.Key, arg.WindowStart)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const lockRateLimitKey = `-- name: LockRateLimitKey :exec
SELECT pg_advisory_xact_lock($1)
`

// LockRateLimitKey takes a transaction-scoped advisory lock so the distinct
// counting path (otp_address) serializes per source address. Without it, two
// new numbers from the same address could both pass the distinct-count check.
func (q *Queries) LockRateLimitKey(ctx context.Context, pgAdvisoryXactLock int64) error {
	_, err := q.db.Exec(ctx, lockRateLimitKey, pgAdvisoryXactLock)
	return err
}

const memberRecorded = `-- name: MemberRecorded :one
SELECT EXISTS (
    SELECT 1 FROM rate_limit
    WHERE target = $1 AND key = $2 AND window_start = $3
)
`

type MemberRecordedParams struct {
	Target      RateLimitTarget
	Key         string
	WindowStart pgtype.Timestamptz
}

// MemberRecorded reports whether member was already recorded under key in the
// current window. A re-send to a number already counted is not a new distinct
// number, so it does not consume more of the address budget.
func (q *Queries) MemberRecorded(ctx context.Context, arg MemberRecordedParams) (bool, error) {
	row := q.db.QueryRow(ctx, memberRecorded, arg.Target, arg.Key, arg.WindowStart)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordMember = `-- name: RecordMember :exec
INSERT INTO rate_limit (id, target, key, window_start, count)
VALUES (gen_random_uuid(), $1, $2, $3, 1)
ON CONFLICT (target, key, window_start) DO NOTHING
`

type RecordMemberParams struct {
	Target      RateLimitTarget
	Key         string
	WindowStart pgtype.Timestamptz
}

// RecordMember records that member was used under key in the current window.
// DO NOTHING keeps it idempotent within the window.
func (q *Queries) RecordMember(ctx context.Context, arg RecordMemberParams) error {
	_, err := q.db.Exec(ctx, recordMember, arg.Target, arg.Key, arg.WindowStart)
	return err
}

const touchRateLimit = `-- name: TouchRateLimit :one
INSERT INTO rate_limit (id, target, key, window_start, count)
VALUES (gen_random_uuid(), $1, $2, $3, 1)
ON CONFLICT (target, key, window_start)
DO UPDATE SET count = rate_limit.count + 1
RETURNING count
`

type TouchRateLimitParams struct {
	Target      RateLimitTarget
	Key         string
	WindowStart pgtype.Timestamptz
}

// TouchRateLimit increments the counter for one (target, key) in the current
// window bucket, creating the row on first use, and returns the new count. The
// ON CONFLICT DO UPDATE is atomic and takes a row lock, so two concurrent
// callers cannot both read the same count and both slip through: the second
// serializes behind the first and sees the incremented value.
func (q *Queries) TouchRateLimit(ctx context.Context, arg TouchRateLimitParams) (int32, error) {
	row := q.db.QueryRow(ctx, touchRateLimit, arg.Target, arg.Key, arg.WindowStart)
	var count int32
	err := row.Scan(&count)
	return count, err
}
