// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reputation.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReviewForResponse = `-- name: GetReviewForResponse :one
SELECT
    r.id,
    r.work_order_id,
    r.reviewer_id,
    r.reviewee_id,
    r.rating,
    r.text,
    r.hidden,
    r.created_at,
    author.business_name AS author_business_name,
    coalesce(wo.confirmed_at, wo.created_at)::date AS transaction_date
FROM review r
JOIN business_profile author ON author.id = r.reviewer_id
JOIN work_order wo           ON wo.id = r.work_order_id
WHERE r.id = $1
`

type GetReviewForResponseRow struct {
	ID                 pgtype.UUID
	WorkOrderID        pgtype.UUID
	ReviewerID         pgtype.UUID
	RevieweeID         pgtype.UUID
	Rating             int16
	Text               pgtype.Text
	Hidden             bool
	CreatedAt          pgtype.Timestamptz
	AuthorBusinessName string
	TransactionDate    pgtype.Date
}

// Reloads one review with the author's business name and the transaction date,
// so the 201 body carries the same shape the public list returns. Keyed on the
// review id just inserted.
func (q *Queries) GetReviewForResponse(ctx context.Context, id pgtype.UUID) (GetReviewForResponseRow, error) {
	row := q.db.QueryRow(ctx, getReviewForResponse, id)
	var i GetReviewForResponseRow
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.ReviewerID,
		&i.RevieweeID,
		&i.Rating,
		&i.Text,
		&i.Hidden,
		&i.CreatedAt,
		&i.AuthorBusinessName,
		&i.TransactionDate,
	)
	return i, err
}

const insertReview = `-- name: InsertReview :one
INSERT INTO review (
    work_order_id, reviewer_id, reviewee_id, rating, text, created_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, work_order_id, reviewer_id, reviewee_id, rating, text, hidden, hidden_by, hidden_at, hidden_reason, created_at
`

type InsertReviewParams struct {
	WorkOrderID pgtype.UUID
	ReviewerID  pgtype.UUID
	RevieweeID  pgtype.UUID
	Rating      int16
	Text        pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

// Records one party's review of the other on a finished work order (FR-047).
// rating is 1..5 (enforced by the rating_one_to_five CHECK), text is optional.
// The one_review_per_order_per_reviewer unique constraint means each party may
// review an order once; a repeat violates it and the caller turns the 23505 into
// a readable REVIEW_ALREADY_SUBMITTED 409 (FR-049). Reviews are never anonymous:
// reviewer_id is stored and shown (FR-050). hidden takes its false default;
// admin hiding is a later moderation action (T069), not a field the author sets.
func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, insertReview,
		arg.WorkOrderID,
		arg.ReviewerID,
		arg.RevieweeID,
		arg.Rating,
		arg.Text,
		arg.CreatedAt,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.ReviewerID,
		&i.RevieweeID,
		&i.Rating,
		&i.Text,
		&i.Hidden,
		&i.HiddenBy,
		&i.HiddenAt,
		&i.HiddenReason,
		&i.CreatedAt,
	)
	return i, err
}

const listReviewsForProfile = `-- name: ListReviewsForProfile :many
SELECT
    r.id,
    r.work_order_id,
    r.reviewer_id,
    r.reviewee_id,
    r.rating,
    r.text,
    r.hidden,
    r.created_at,
    author.business_name AS author_business_name,
    coalesce(wo.confirmed_at, wo.created_at)::date AS transaction_date
FROM review r
JOIN business_profile author ON author.id = r.reviewer_id
JOIN work_order wo           ON wo.id = r.work_order_id
WHERE r.reviewee_id = $1::uuid
  AND NOT r.hidden
  AND (
        $2::timestamptz IS NULL
        OR (r.created_at, r.id) < ($2::timestamptz, $3::uuid)
    )
ORDER BY r.created_at DESC, r.id DESC
LIMIT $4::int
`

type ListReviewsForProfileParams struct {
	RevieweeID    pgtype.UUID
	BeforeCreated pgtype.Timestamptz
	BeforeID      pgtype.UUID
	PageLimit     int32
}

type ListReviewsForProfileRow struct {
	ID                 pgtype.UUID
	WorkOrderID        pgtype.UUID
	ReviewerID         pgtype.UUID
	RevieweeID         pgtype.UUID
	Rating             int16
	Text               pgtype.Text
	Hidden             bool
	CreatedAt          pgtype.Timestamptz
	AuthorBusinessName string
	TransactionDate    pgtype.Date
}

// One profile's received reviews, newest first, keyset paginated on
// (created_at, id) so the order is stable across pages (FR-048). Hidden reviews
// are excluded: a review admin took down must not reappear in the public list,
// and the same NOT hidden filter is what SearchReputation applies to the average,
// so the list and the average never disagree (FR-050). Rides
// idx_review_reviewee (reviewee_id) WHERE NOT hidden. A null before_created is
// the first page. The author's business name rides along because reviews are not
// anonymous, and transaction_date names the order the review is about.
func (q *Queries) ListReviewsForProfile(ctx context.Context, arg ListReviewsForProfileParams) ([]ListReviewsForProfileRow, error) {
	rows, err := q.db.Query(ctx, listReviewsForProfile,
		arg.RevieweeID,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsForProfileRow{}
	for rows.Next() {
		var i ListReviewsForProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkOrderID,
			&i.ReviewerID,
			&i.RevieweeID,
			&i.Rating,
			&i.Text,
			&i.Hidden,
			&i.CreatedAt,
			&i.AuthorBusinessName,
			&i.TransactionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
