// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCandidateListings = `-- name: GetCandidateListings :many
SELECT l.id AS listing_id, l.profile_id, l.published, p.account_id, p.business_name
FROM capacity_listing l
JOIN business_profile p ON p.id = l.profile_id
WHERE l.id = ANY($1::uuid[])
`

type GetCandidateListingsRow struct {
	ListingID    pgtype.UUID
	ProfileID    pgtype.UUID
	Published    bool
	AccountID    pgtype.UUID
	BusinessName string
}

// GetCandidateListings resolves each listing id to its owning profile and that
// profile's account, and reports whether the listing is published. The service
// uses this to reject unknown or unpublished listings (422) and to detect a
// listing owned by the searcher's own profile (FR-083) before any insert.
func (q *Queries) GetCandidateListings(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetCandidateListingsRow, error) {
	rows, err := q.db.Query(ctx, getCandidateListings, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCandidateListingsRow{}
	for rows.Next() {
		var i GetCandidateListingsRow
		if err := rows.Scan(
			&i.ListingID,
			&i.ProfileID,
			&i.Published,
			&i.AccountID,
			&i.BusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertQuotaRequest = `-- name: InsertQuotaRequest :one
INSERT INTO quota_request (buyer_id, product_item_id, quantity, material, deadline, note, reply_due_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, buyer_id, product_item_id, quantity, material, deadline, note, reply_due_at, created_at
`

type InsertQuotaRequestParams struct {
	BuyerID       pgtype.UUID
	ProductItemID pgtype.UUID
	Quantity      int32
	Material      string
	Deadline      pgtype.Date
	Note          pgtype.Text
	ReplyDueAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

// InsertQuotaRequest creates one quota request. Both created_at and reply_due_at
// are supplied by the caller from the injected Clock (FR-082, Rule 5): the table
// has no DEFAULT now(), and its only time constraint enforces reply_due_at >
// created_at. The 72-hour window is computed in the service, not here.
func (q *Queries) InsertQuotaRequest(ctx context.Context, arg InsertQuotaRequestParams) (QuotaRequest, error) {
	row := q.db.QueryRow(ctx, insertQuotaRequest,
		arg.BuyerID,
		arg.ProductItemID,
		arg.Quantity,
		arg.Material,
		arg.Deadline,
		arg.Note,
		arg.ReplyDueAt,
		arg.CreatedAt,
	)
	var i QuotaRequest
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.ProductItemID,
		&i.Quantity,
		&i.Material,
		&i.Deadline,
		&i.Note,
		&i.ReplyDueAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRequestCandidate = `-- name: InsertRequestCandidate :one
INSERT INTO request_candidate (request_id, listing_id, subcontractor_id, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, request_id, listing_id, subcontractor_id, status, rejection_reason, updated_at
`

type InsertRequestCandidateParams struct {
	RequestID       pgtype.UUID
	ListingID       pgtype.UUID
	SubcontractorID pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
}

// InsertRequestCandidate links one listing to a request as a candidate. status
// defaults to 'awaiting_reply'. The trg_reject_self_request trigger raises when
// subcontractor_id equals the request's buyer_id; the service rejects that case
// first (FR-083), so this insert is the safety net.
func (q *Queries) InsertRequestCandidate(ctx context.Context, arg InsertRequestCandidateParams) (RequestCandidate, error) {
	row := q.db.QueryRow(ctx, insertRequestCandidate,
		arg.RequestID,
		arg.ListingID,
		arg.SubcontractorID,
		arg.UpdatedAt,
	)
	var i RequestCandidate
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ListingID,
		&i.SubcontractorID,
		&i.Status,
		&i.RejectionReason,
		&i.UpdatedAt,
	)
	return i, err
}

const listCandidatesByRequests = `-- name: ListCandidatesByRequests :many
SELECT c.id AS candidate_id, c.request_id, c.listing_id, c.subcontractor_id,
       c.status, c.rejection_reason, p.business_name
FROM request_candidate c
JOIN business_profile p ON p.id = c.subcontractor_id
WHERE c.request_id = ANY($1::uuid[])
ORDER BY c.request_id, c.id
`

type ListCandidatesByRequestsRow struct {
	CandidateID     pgtype.UUID
	RequestID       pgtype.UUID
	ListingID       pgtype.UUID
	SubcontractorID pgtype.UUID
	Status          CandidateStatus
	RejectionReason pgtype.Text
	BusinessName    string
}

// ListCandidatesByRequests returns every candidate of the given requests, joined
// to its subcontractor profile for the business name, ordered so a request's
// candidates group together deterministically.
func (q *Queries) ListCandidatesByRequests(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListCandidatesByRequestsRow, error) {
	rows, err := q.db.Query(ctx, listCandidatesByRequests, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCandidatesByRequestsRow{}
	for rows.Next() {
		var i ListCandidatesByRequestsRow
		if err := rows.Scan(
			&i.CandidateID,
			&i.RequestID,
			&i.ListingID,
			&i.SubcontractorID,
			&i.Status,
			&i.RejectionReason,
			&i.BusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotaRequestsByBuyer = `-- name: ListQuotaRequestsByBuyer :many
SELECT id, buyer_id, product_item_id, quantity, material, deadline, note, reply_due_at, created_at
FROM quota_request
WHERE buyer_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListQuotaRequestsByBuyerParams struct {
	BuyerID pgtype.UUID
	Column2 pgtype.Timestamptz
	Column3 pgtype.UUID
	Limit   int32
}

// ListQuotaRequestsByBuyer returns one keyset page of a buyer's own requests,
// newest first, ordered by (created_at, id) so the order is total and stable
// across pages (FR-030, FR-080). The cursor tuple admits every row on the first
// page via sentinels above the maxima.
func (q *Queries) ListQuotaRequestsByBuyer(ctx context.Context, arg ListQuotaRequestsByBuyerParams) ([]QuotaRequest, error) {
	rows, err := q.db.Query(ctx, listQuotaRequestsByBuyer,
		arg.BuyerID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuotaRequest{}
	for rows.Next() {
		var i QuotaRequest
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.ProductItemID,
			&i.Quantity,
			&i.Material,
			&i.Deadline,
			&i.Note,
			&i.ReplyDueAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
