// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO session (
    id, account_id, token_hash, source_address,
    expires_at, created_at, accessed_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $5
)
RETURNING id, account_id, token_hash, source_address, expires_at, created_at, accessed_at
`

type CreateSessionParams struct {
	AccountID     pgtype.UUID
	TokenHash     []byte
	SourceAddress *netip.Addr
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

// CreateSession stores a new session row keyed by the SHA-256 hash of the
// opaque token. The raw token lives only in the cookie; the database never
// sees it, so a database read cannot reconstruct a usable session token.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.AccountID,
		arg.TokenHash,
		arg.SourceAddress,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.SourceAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AccessedAt,
	)
	return i, err
}

const deleteAllSessions = `-- name: DeleteAllSessions :exec
DELETE FROM session WHERE account_id = $1
`

// DeleteAllSessions removes every session for an account, used when no session
// is retained (recovery confirmed without an active caller session).
func (q *Queries) DeleteAllSessions(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllSessions, accountID)
	return err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :exec
DELETE FROM session
WHERE account_id = $1 AND token_hash <> $2
`

type DeleteOtherSessionsParams struct {
	AccountID pgtype.UUID
	TokenHash []byte
}

// DeleteOtherSessions removes every session for an account except the one whose
// hash is kept. Recovery confirmation uses this to end all other sessions after
// a password reset, without logging the current caller out mid-request.
func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherSessions, arg.AccountID, arg.TokenHash)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session WHERE token_hash = $1
`

// DeleteSession removes one session by token hash, backing logout.
func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, account_id, token_hash, source_address, expires_at, created_at, accessed_at FROM session
WHERE token_hash = $1 AND expires_at > $2
`

type GetSessionByTokenHashParams struct {
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

// GetSessionByTokenHash loads a live session by token hash. The expiry check is
// in SQL so an expired row is treated as absent without a second round trip.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.SourceAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AccessedAt,
	)
	return i, err
}

const renewSession = `-- name: RenewSession :exec
UPDATE session
SET expires_at = $2, accessed_at = $3
WHERE id = $1
`

type RenewSessionParams struct {
	ID         pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
	AccessedAt pgtype.Timestamptz
}

// RenewSession slides the expiry forward and records access time, implementing
// rolling 7-day renewal on each authenticated request.
func (q *Queries) RenewSession(ctx context.Context, arg RenewSessionParams) error {
	_, err := q.db.Exec(ctx, renewSession, arg.ID, arg.ExpiresAt, arg.AccessedAt)
	return err
}
