// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploaded_file.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUploadedFile = `-- name: CreateUploadedFile :one
INSERT INTO uploaded_file (
    id, owner_profile_id, type, original_name, mime_type, size_bytes, storage_path, created_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, owner_profile_id, type, original_name, mime_type, size_bytes, storage_path, created_at
`

type CreateUploadedFileParams struct {
	OwnerProfileID pgtype.UUID
	Type           FileType
	OriginalName   string
	MimeType       string
	SizeBytes      int32
	StoragePath    string
	CreatedAt      pgtype.Timestamptz
}

// CreateUploadedFile records one stored file. The storage_path is a
// system-generated UUID name, never the client's filename; original_name is
// kept as display metadata only. size_bytes and mime_type are the values the
// application verified (magic bytes, re-encoded length), not what the client
// claimed, so the DB CHECK constraints see the trusted values.
func (q *Queries) CreateUploadedFile(ctx context.Context, arg CreateUploadedFileParams) (UploadedFile, error) {
	row := q.db.QueryRow(ctx, createUploadedFile,
		arg.OwnerProfileID,
		arg.Type,
		arg.OriginalName,
		arg.MimeType,
		arg.SizeBytes,
		arg.StoragePath,
		arg.CreatedAt,
	)
	var i UploadedFile
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.Type,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadedFile = `-- name: GetUploadedFile :one
SELECT id, owner_profile_id, type, original_name, mime_type, size_bytes, storage_path, created_at FROM uploaded_file WHERE id = $1
`

// GetUploadedFile returns one file row by id. The handler resolves the caller's
// profile and admin flag and compares against owner_profile_id before streaming
// the bytes, so this query carries no access check of its own (FR-009 is
// enforced in Go, not SQL).
func (q *Queries) GetUploadedFile(ctx context.Context, id pgtype.UUID) (UploadedFile, error) {
	row := q.db.QueryRow(ctx, getUploadedFile, id)
	var i UploadedFile
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.Type,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const sumUploadedBytesByOwner = `-- name: SumUploadedBytesByOwner :one
SELECT COALESCE(SUM(size_bytes), 0)::bigint FROM uploaded_file WHERE owner_profile_id = $1
`

// SumUploadedBytesByOwner totals the bytes a profile already holds, so a new
// upload can be rejected before it pushes the owner past the 500MB quota.
// COALESCE keeps the result 0 rather than NULL for an owner with no files yet.
func (q *Queries) SumUploadedBytesByOwner(ctx context.Context, ownerProfileID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumUploadedBytesByOwner, ownerProfileID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
