// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_code.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeVerificationCode = `-- name: ConsumeVerificationCode :execrows
UPDATE verification_code
SET consumed_at = $2
WHERE id = $1 AND consumed_at IS NULL
`

type ConsumeVerificationCodeParams struct {
	ID         pgtype.UUID
	ConsumedAt pgtype.Timestamptz
}

// ConsumeVerificationCode marks a code used so it cannot be replayed. The
// consumed_at IS NULL guard makes double-consume a no-op, and the returned row
// count lets the caller detect a code already spent.
func (q *Queries) ConsumeVerificationCode(ctx context.Context, arg ConsumeVerificationCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeVerificationCode, arg.ID, arg.ConsumedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO verification_code (
    id, account_id, purpose, code_hash, expires_at, created_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5
)
RETURNING id, account_id, purpose, code_hash, expires_at, consumed_at, created_at
`

type CreateVerificationCodeParams struct {
	AccountID pgtype.UUID
	Purpose   VerificationPurpose
	CodeHash  []byte
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// CreateVerificationCode stores one six-digit code as its SHA-256 hash for a
// given account and purpose. The plaintext code is delivered out of band (email
// or WhatsApp) and never persisted, so a database read cannot reveal it.
func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, createVerificationCode,
		arg.AccountID,
		arg.Purpose,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestVerificationCode = `-- name: GetLatestVerificationCode :one
SELECT id, account_id, purpose, code_hash, expires_at, consumed_at, created_at FROM verification_code
WHERE account_id = $1 AND purpose = $2 AND consumed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestVerificationCodeParams struct {
	AccountID pgtype.UUID
	Purpose   VerificationPurpose
}

// GetLatestVerificationCode returns the most recent unconsumed code for an
// account and purpose. Verification compares the submitted code's hash against
// this row and checks expiry in Go against the injected Clock.
func (q *Queries) GetLatestVerificationCode(ctx context.Context, arg GetLatestVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getLatestVerificationCode, arg.AccountID, arg.Purpose)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateVerificationCodes = `-- name: InvalidateVerificationCodes :exec
UPDATE verification_code
SET consumed_at = $3
WHERE account_id = $1 AND purpose = $2 AND consumed_at IS NULL
`

type InvalidateVerificationCodesParams struct {
	AccountID  pgtype.UUID
	Purpose    VerificationPurpose
	ConsumedAt pgtype.Timestamptz
}

// InvalidateVerificationCodes consumes all outstanding codes for an account and
// purpose, so issuing a fresh code retires the previous ones in the same
// transaction and only the newest can be redeemed.
func (q *Queries) InvalidateVerificationCodes(ctx context.Context, arg InvalidateVerificationCodesParams) error {
	_, err := q.db.Exec(ctx, invalidateVerificationCodes, arg.AccountID, arg.Purpose, arg.ConsumedAt)
	return err
}
