// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_request.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerificationRequest = `-- name: CreateVerificationRequest :one
INSERT INTO verification_request (
    id, profile_id, identity_number, identity_file_id, location_file_id,
    applicant_source_address, created_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6
)
RETURNING id, profile_id, identity_number, identity_file_id, location_file_id, status, admin_note, decided_by, decided_at, applicant_source_address, created_at
`

type CreateVerificationRequestParams struct {
	ProfileID              pgtype.UUID
	IdentityNumber         string
	IdentityFileID         pgtype.UUID
	LocationFileID         pgtype.UUID
	ApplicantSourceAddress *netip.Addr
	CreatedAt              pgtype.Timestamptz
}

// CreateVerificationRequest records one pending verification submission for a
// profile. status defaults to 'pending' in the schema, so it is not set here;
// decided_by, decided_at and admin_note stay NULL until an admin decides. The
// idx_one_pending_verification partial unique index rejects a second pending row
// for the same profile with a 23505, which the handler turns into a 409
// (FR-011: re-submission is allowed only after a rejection).
func (q *Queries) CreateVerificationRequest(ctx context.Context, arg CreateVerificationRequestParams) (VerificationRequest, error) {
	row := q.db.QueryRow(ctx, createVerificationRequest,
		arg.ProfileID,
		arg.IdentityNumber,
		arg.IdentityFileID,
		arg.LocationFileID,
		arg.ApplicantSourceAddress,
		arg.CreatedAt,
	)
	var i VerificationRequest
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.IdentityNumber,
		&i.IdentityFileID,
		&i.LocationFileID,
		&i.Status,
		&i.AdminNote,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ApplicantSourceAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listVerificationRequestsByProfile = `-- name: ListVerificationRequestsByProfile :many
SELECT
    vr.id, vr.profile_id, vr.identity_number, vr.identity_file_id,
    vr.location_file_id, vr.status, vr.admin_note, vr.decided_at, vr.created_at,
    bp.business_name
FROM verification_request vr
JOIN business_profile bp ON bp.id = vr.profile_id
WHERE vr.profile_id = $1
ORDER BY vr.created_at DESC
`

type ListVerificationRequestsByProfileRow struct {
	ID             pgtype.UUID
	ProfileID      pgtype.UUID
	IdentityNumber string
	IdentityFileID pgtype.UUID
	LocationFileID pgtype.UUID
	Status         VerificationStatus
	AdminNote      pgtype.Text
	DecidedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	BusinessName   string
}

// ListVerificationRequestsByProfile returns every submission a profile has made,
// newest first, joined to business_profile for the business_name the contract's
// VerificationRequest carries (the verification_request table has no such
// column). The caller sees only their own submissions (FR-006).
func (q *Queries) ListVerificationRequestsByProfile(ctx context.Context, profileID pgtype.UUID) ([]ListVerificationRequestsByProfileRow, error) {
	rows, err := q.db.Query(ctx, listVerificationRequestsByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVerificationRequestsByProfileRow{}
	for rows.Next() {
		var i ListVerificationRequestsByProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.IdentityNumber,
			&i.IdentityFileID,
			&i.LocationFileID,
			&i.Status,
			&i.AdminNote,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.BusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
