// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_request.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerificationRequest = `-- name: CreateVerificationRequest :one
INSERT INTO verification_request (
    id, profile_id, identity_number, identity_file_id, location_file_id,
    applicant_source_address, created_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6
)
RETURNING id, profile_id, identity_number, identity_file_id, location_file_id, status, admin_note, decided_by, decided_at, applicant_source_address, created_at
`

type CreateVerificationRequestParams struct {
	ProfileID              pgtype.UUID
	IdentityNumber         string
	IdentityFileID         pgtype.UUID
	LocationFileID         pgtype.UUID
	ApplicantSourceAddress *netip.Addr
	CreatedAt              pgtype.Timestamptz
}

// CreateVerificationRequest records one pending verification submission for a
// profile. status defaults to 'pending' in the schema, so it is not set here;
// decided_by, decided_at and admin_note stay NULL until an admin decides. The
// idx_one_pending_verification partial unique index rejects a second pending row
// for the same profile with a 23505, which the handler turns into a 409
// (FR-011: re-submission is allowed only after a rejection).
func (q *Queries) CreateVerificationRequest(ctx context.Context, arg CreateVerificationRequestParams) (VerificationRequest, error) {
	row := q.db.QueryRow(ctx, createVerificationRequest,
		arg.ProfileID,
		arg.IdentityNumber,
		arg.IdentityFileID,
		arg.LocationFileID,
		arg.ApplicantSourceAddress,
		arg.CreatedAt,
	)
	var i VerificationRequest
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.IdentityNumber,
		&i.IdentityFileID,
		&i.LocationFileID,
		&i.Status,
		&i.AdminNote,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ApplicantSourceAddress,
		&i.CreatedAt,
	)
	return i, err
}

const decideVerificationRequest = `-- name: DecideVerificationRequest :one
UPDATE verification_request
SET status = $1::verification_status,
    admin_note = $2,
    decided_by = $3::uuid,
    decided_at = $4::timestamptz
WHERE id = $5::uuid AND status = 'pending'
RETURNING id, profile_id, identity_number, identity_file_id, location_file_id, status, admin_note, decided_by, decided_at, applicant_source_address, created_at,
    (SELECT business_name FROM business_profile WHERE id = profile_id) AS business_name,
    (SELECT account_id FROM business_profile WHERE id = profile_id) AS applicant_account
`

type DecideVerificationRequestParams struct {
	Status    VerificationStatus
	AdminNote pgtype.Text
	DecidedBy pgtype.UUID
	DecidedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

type DecideVerificationRequestRow struct {
	ID                     pgtype.UUID
	ProfileID              pgtype.UUID
	IdentityNumber         string
	IdentityFileID         pgtype.UUID
	LocationFileID         pgtype.UUID
	Status                 VerificationStatus
	AdminNote              pgtype.Text
	DecidedBy              pgtype.UUID
	DecidedAt              pgtype.Timestamptz
	ApplicantSourceAddress *netip.Addr
	CreatedAt              pgtype.Timestamptz
	BusinessName           string
	ApplicantAccount       pgtype.UUID
}

// DecideVerificationRequest records an admin's approval or rejection: it stamps
// status, admin_note, decided_by and decided_at in one statement, only while the
// request is still pending (FR-007). The verification_decision_complete and
// rejection_needs_reason CHECKs are the storage-level safety net; the handler
// rejects a reasonless rejection first so the applicant reads a field error, not
// a 500. business_name rides along for the response.
func (q *Queries) DecideVerificationRequest(ctx context.Context, arg DecideVerificationRequestParams) (DecideVerificationRequestRow, error) {
	row := q.db.QueryRow(ctx, decideVerificationRequest,
		arg.Status,
		arg.AdminNote,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.ID,
	)
	var i DecideVerificationRequestRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.IdentityNumber,
		&i.IdentityFileID,
		&i.LocationFileID,
		&i.Status,
		&i.AdminNote,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ApplicantSourceAddress,
		&i.CreatedAt,
		&i.BusinessName,
		&i.ApplicantAccount,
	)
	return i, err
}

const latestVerificationStatusByProfile = `-- name: LatestVerificationStatusByProfile :one
SELECT status
FROM verification_request
WHERE profile_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// LatestVerificationStatusByProfile returns the status of the profile's most
// recent verification submission, or no row when the profile never submitted one.
// The caller maps the no-row case to a null verification_status on MyProfile,
// distinct from a profile that has a pending or decided request (FR-006).
func (q *Queries) LatestVerificationStatusByProfile(ctx context.Context, profileID pgtype.UUID) (VerificationStatus, error) {
	row := q.db.QueryRow(ctx, latestVerificationStatusByProfile, profileID)
	var status VerificationStatus
	err := row.Scan(&status)
	return status, err
}

const listVerificationQueue = `-- name: ListVerificationQueue :many
SELECT
    vr.id, vr.profile_id, vr.identity_number, vr.identity_file_id,
    vr.location_file_id, vr.status, vr.admin_note, vr.decided_at, vr.created_at,
    bp.business_name
FROM verification_request vr
JOIN business_profile bp ON bp.id = vr.profile_id
WHERE (
        $1::verification_status IS NULL
        OR vr.status = $1::verification_status
    )
  AND (
        $2::timestamptz IS NULL
        OR (vr.created_at, vr.id) < ($2::timestamptz, $3::uuid)
    )
ORDER BY vr.created_at DESC, vr.id DESC
LIMIT $4::int
`

type ListVerificationQueueParams struct {
	StatusFilter  NullVerificationStatus
	BeforeCreated pgtype.Timestamptz
	BeforeID      pgtype.UUID
	PageLimit     int32
}

type ListVerificationQueueRow struct {
	ID             pgtype.UUID
	ProfileID      pgtype.UUID
	IdentityNumber string
	IdentityFileID pgtype.UUID
	LocationFileID pgtype.UUID
	Status         VerificationStatus
	AdminNote      pgtype.Text
	DecidedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	BusinessName   string
}

// ListVerificationQueue returns one keyset page of verification requests for the
// admin queue, newest first, joined to business_profile for the business name
// the contract's VerificationRequest carries (FR-007). An absent status_filter
// lists every status; a present one narrows to it, so the default view is the
// pending backlog. A null before_created is the first page; the (created_at, id)
// tuple comparison is the stable keyset the opaque cursor rides (FR-008 badge is
// granted from the decision this queue feeds, not here).
func (q *Queries) ListVerificationQueue(ctx context.Context, arg ListVerificationQueueParams) ([]ListVerificationQueueRow, error) {
	rows, err := q.db.Query(ctx, listVerificationQueue,
		arg.StatusFilter,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVerificationQueueRow{}
	for rows.Next() {
		var i ListVerificationQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.IdentityNumber,
			&i.IdentityFileID,
			&i.LocationFileID,
			&i.Status,
			&i.AdminNote,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.BusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationRequestsByProfile = `-- name: ListVerificationRequestsByProfile :many
SELECT
    vr.id, vr.profile_id, vr.identity_number, vr.identity_file_id,
    vr.location_file_id, vr.status, vr.admin_note, vr.decided_at, vr.created_at,
    bp.business_name
FROM verification_request vr
JOIN business_profile bp ON bp.id = vr.profile_id
WHERE vr.profile_id = $1
ORDER BY vr.created_at DESC
`

type ListVerificationRequestsByProfileRow struct {
	ID             pgtype.UUID
	ProfileID      pgtype.UUID
	IdentityNumber string
	IdentityFileID pgtype.UUID
	LocationFileID pgtype.UUID
	Status         VerificationStatus
	AdminNote      pgtype.Text
	DecidedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	BusinessName   string
}

// ListVerificationRequestsByProfile returns every submission a profile has made,
// newest first, joined to business_profile for the business_name the contract's
// VerificationRequest carries (the verification_request table has no such
// column). The caller sees only their own submissions (FR-006).
func (q *Queries) ListVerificationRequestsByProfile(ctx context.Context, profileID pgtype.UUID) ([]ListVerificationRequestsByProfileRow, error) {
	rows, err := q.db.Query(ctx, listVerificationRequestsByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVerificationRequestsByProfileRow{}
	for rows.Next() {
		var i ListVerificationRequestsByProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.IdentityNumber,
			&i.IdentityFileID,
			&i.LocationFileID,
			&i.Status,
			&i.AdminNote,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.BusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVerificationRequest = `-- name: LockVerificationRequest :one
SELECT vr.id, vr.profile_id, vr.identity_number, vr.identity_file_id, vr.location_file_id, vr.status, vr.admin_note, vr.decided_by, vr.decided_at, vr.applicant_source_address, vr.created_at, bp.business_name
FROM verification_request vr
JOIN business_profile bp ON bp.id = vr.profile_id
WHERE vr.id = $1::uuid
FOR UPDATE OF vr
`

type LockVerificationRequestRow struct {
	ID                     pgtype.UUID
	ProfileID              pgtype.UUID
	IdentityNumber         string
	IdentityFileID         pgtype.UUID
	LocationFileID         pgtype.UUID
	Status                 VerificationStatus
	AdminNote              pgtype.Text
	DecidedBy              pgtype.UUID
	DecidedAt              pgtype.Timestamptz
	ApplicantSourceAddress *netip.Addr
	CreatedAt              pgtype.Timestamptz
	BusinessName           string
}

// LockVerificationRequest takes a row lock on the target request so the decision
// runs under a lock: two admins deciding the same pending request serialize, and
// the second sees the status the first already set. business_name rides along via
// a scalar subquery so the decision response carries it without a second round
// trip (FR-007).
func (q *Queries) LockVerificationRequest(ctx context.Context, id pgtype.UUID) (LockVerificationRequestRow, error) {
	row := q.db.QueryRow(ctx, lockVerificationRequest, id)
	var i LockVerificationRequestRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.IdentityNumber,
		&i.IdentityFileID,
		&i.LocationFileID,
		&i.Status,
		&i.AdminNote,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ApplicantSourceAddress,
		&i.CreatedAt,
		&i.BusinessName,
	)
	return i, err
}

const markProfileVerified = `-- name: MarkProfileVerified :exec
UPDATE business_profile
SET verified = true, updated_at = $1::timestamptz
WHERE id = $2::uuid
`

type MarkProfileVerifiedParams struct {
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

// MarkProfileVerified flips the verified badge on approval (FR-008). It is called
// inside the same transaction as DecideVerificationRequest so an approved
// decision and the badge it grants land together or not at all. search.sql
// already selects verified, so the badge propagates to search results with no
// further change; a rejection never touches this, leaving the listing untouched
// (FR-010, FR-011).
func (q *Queries) MarkProfileVerified(ctx context.Context, arg MarkProfileVerifiedParams) error {
	_, err := q.db.Exec(ctx, markProfileVerified, arg.UpdatedAt, arg.ID)
	return err
}
